--pendiente
INSERT INTO CatSubscription (SubscriptionName, 
							 SubscriptionDescription, 
							 SubscriptionCost, 
							 SubscriptionFixedValue, 
							 SubscriptionMaxServiceFixedValue, 
							 SubscriptionValidity,
							 SubscriptionWeight,
							 RowStatus,
							 TokenCreated,
							 DateCreated,
							 Icon,
							 NextSalesPackageBanner,
							 CatTypeSubscriptionId,
							 CatProductCategoryId,
							 Tag,
							 Position,
							 IdCountry,
							 IdCatCurrencyCOD)
		VALUES ('Paquete B�sico','50 env�os L99.00 c/u',4950.27,0,3,6,2,1,'SYS-BHERRERA',GETDATE(),'hwa-planBasicoIcon','bannerSubsPlan2.png',2,9,'M�S VENDIDO',2,'HN',4),
			   ('Paquete Plus','100 env�os L92.62 c/u',9261.80,0,3,6,3,1,'SYS-BHERRERA',GETDATE(),'hwa-planBasicoPlusIcon','bannerSubsPlan3.png',2,9,NULL,NULL,'HN',4),
			   ('Paquete Gold','200 env�os L86.23 c/u',17246.10,0,3,6,4,1,'SYS-BHERRERA',GETDATE(),'hwa-planGoldIcon','bannerSubsPlan4.png',2,9,NULL,NULL,'HN',4),
			   ('Plan Amigo','Plan de descuentos',316.18,0,3,6,1,1,'SYS-BHERRERA',GETDATE(),'hwa-planAmigoIcon','bannerSubsPlan4.png',1,10,'M�S VENDIDO',6,'HN',4),
			   ('Paquete Petit','25 env�os L105.39 c/u',2634.82,0,3,6,0,1,'SYS-BHERRERA',GETDATE(),'hwa-planPetitIcon','bannerSubsPlan4.png',2,9,'M�S VENDIDO',1,'HN',4),
			   ('Paquete Platino','400 env�os L79.84 c/u',31937.23,0,3,6,0,1,'SYS-BHERRERA',GETDATE(),'hwa-planPlatinoIcon','bannerSubsPlan4.png',2,9,'NOVEDADES',1,'HN',4)