BEGIN TRY
BEGIN TRANSACTION

 DECLARE @IdSegmentMetro         INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'MEH'), --14
         @IdSegmentLocal          INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'LOH'), --15
         @IdSegmentDepart         INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'DEH'), --16
         @IdSegmentRegional       INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'REH'), --17
         @IdSegmentForOlancho     INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FOH'), --18
         @IdSegmentEspecial       INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'ESH'), --19
         @IdSegmentNacional       INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'NAH'), --21
         @IdSegmentForIslas       INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FIH'), --20
         @IdSegmentForGracias     INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FGH'); --33

DECLARE @IdRate          INT = (SELECT RheId FROM RateHeader WITH(NOLOCK) WHERE RheName ='Tarifario de servicio estandar' AND CountryId = 'HN'),
        @TypeServiceSTD  INT = (SELECT CtsId FROM CatTypeService WITH(NOLOCK) WHERE CtsShortName = 'STD'), --5
        @TypeServiceCOD  INT = (SELECT CtsId FROM CatTypeService WITH(NOLOCK) WHERE CtsShortName = 'COD'); --6

DECLARE @IdPeq   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Pequeño' and IdCountry = 'HN') AND Code = 'EXPHN076'),
        @IdMed   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Mediano' and IdCountry = 'HN') AND Code ='EXPHN077'),
        @IdGrand INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Grande' and IdCountry = 'HN') AND Code ='EXPHN078'),
        @IdExt   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Extra Grande' and IdCountry = 'HN') AND Code ='EXPHN079'),
        @IdSob   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Sobredimensionado' and IdCountry = 'HN') AND Code ='EXPHN080');


 --*********************  ESTANDAR  *********************

--INHABILITAR TARIFAS ANTIGUAS (ESTANDAR)
UPDATE RateData
SET RowStatus = 0,
    TokenUpdated = 'SYS-BPEDROZA',
    DateUpdated = GETDATE()
WHERE RateId = @IdRate AND RowStatus = 1 AND TypeServiceId IS NOT NULL AND TypeServiceId = @TypeServiceSTD;

--COBERTURA METRO
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdPeq,71,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdMed,80,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdGrand,105,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdExt,113,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdSob,122,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA LOCAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdPeq,83,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdMed,91,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdGrand,116,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdExt,125,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdSob,133,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA DEPARTAMENTAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdPeq,94,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdMed,102,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdGrand,128,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdExt,136,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdSob,144,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA REGIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdPeq,105,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdMed,113,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdGrand,139,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdExt,147,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdSob,155,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA NACIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdPeq,124,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdMed,132,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdGrand,158,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdExt,166,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdSob,174,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA OLANCHO
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdPeq,165,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdMed,173,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdGrand,199,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdExt,207,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdSob,215,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA ESPECIAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdPeq,225,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdMed,233,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdGrand,259,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdExt,267,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdSob,275,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA ISLAS
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdPeq,300,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdMed,308,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdGrand,334,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdExt,342,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdSob,350,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA GRACIAS A DIOS
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdPeq,375,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdMed,383,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdGrand,401,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdExt,410,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdSob,418,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


 --*********************  COD  *********************

--INHABILITAR TARIFAS ANTIGUAS (COD)
UPDATE RateData
SET RowStatus = 0,
    TokenUpdated = 'SYS-BPEDROZA',
    DateUpdated = GETDATE()
WHERE RateId = @IdRate AND RowStatus = 1 AND TypeServiceId IS NOT NULL AND TypeServiceId = @TypeServiceCOD;

--COBERTURA METRO
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdPeq,64,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdMed,72,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdGrand,98,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdExt,106,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdSob,114,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA LOCAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdPeq,75,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdMed,83,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdGrand,109,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdExt,117,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdSob,125,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA DEPARTAMENTAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdPeq,86,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdMed,95,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdGrand,120,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdExt,128,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdSob,137,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA REGIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdPeq,98,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdMed,106,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdGrand,131,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdExt,140,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdSob,148,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA NACIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdPeq,116,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdMed,125,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdGrand,150,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdExt,158,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdSob,167,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA OLANCHO
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdPeq,158,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdMed,166,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdGrand,191,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdExt,200,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdSob,208,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA ESPECIAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdPeq,218,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdMed,226,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdGrand,251,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdExt,260,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdSob,268,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA ISLAS
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdPeq,293,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdMed,301,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdGrand,326,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdExt,335,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdSob,343,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA GRACIAS A DIOS
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdPeq,368,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdMed,375,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdGrand,390,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdExt,398,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdSob,405,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


COMMIT TRANSACTION
    PRINT 'Actualización realizada correctamente.'
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION

    PRINT 'Ocurrió un error al ejecutar la actualización.'
    PRINT ERROR_MESSAGE()
END CATCH
