CREATE TABLE [dbo].[ConfirmedAddress] (
    [NirPhone]               NVARCHAR (4)   NOT NULL,
    [Phone]                  NVARCHAR (15)  NOT NULL,
    [TokenCreated]           VARCHAR (50)   NOT NULL,
    [DateCreated]            DATETIME       NOT NULL,
    [TokenUpdate]            VARCHAR (50)   NULL,
    [DateUpdate]             DATETIME       NULL,
    [RowStatus]              BIT            NOT NULL,
    [IdAccount]              BIGINT         NOT NULL,
    [IdTownship]             INT            NOT NULL,
    [NameAddress]            VARCHAR (100)  NOT NULL,
    [Address]                NVARCHAR (600) NOT NULL,
    [AdditionalInstructions] VARCHAR (250)  NULL,
    [IdCityPlace]            INT            NOT NULL,
    [CodeOfReference]        INT            NULL,
    [IdDeliveryOption]       BIGINT         NULL,
    [Latitude]               VARCHAR (20)   NULL,
    [Longitude]              VARCHAR (20)   NULL,
    [Neighborhood]           VARCHAR (50)   NULL,
    [Zone]                   SMALLINT       NULL,
    [IdModule]               INT            NULL,
    [IdStatusAddress]        INT            NOT NULL,
    CONSTRAINT [PK_ConfirmedAddress] PRIMARY KEY CLUSTERED ([NirPhone] ASC, [Phone] ASC),
    CONSTRAINT [FK_CADD_Account] FOREIGN KEY ([IdAccount]) REFERENCES [dbo].[Account] ([AccIdAccount]),
    CONSTRAINT [FK_CADD_CityPlace] FOREIGN KEY ([IdCityPlace]) REFERENCES [dbo].[CatCityPlace] ([IdCityPlace]),
    CONSTRAINT [FK_CADD_Module] FOREIGN KEY ([IdModule]) REFERENCES [dbo].[CatModule] ([ModIdModule]),
    CONSTRAINT [FK_CADD_State] FOREIGN KEY ([IdStatusAddress]) REFERENCES [dbo].[CatStateConfirmedAddress] ([IdStatus]),
    CONSTRAINT [FK_CADD_Township] FOREIGN KEY ([IdTownship]) REFERENCES [dbo].[Township] ([IdTownship]),
    CONSTRAINT [FK_CADD_VP] FOREIGN KEY ([CodeOfReference]) REFERENCES [dbo].[VisitPointClient] ([CodeOfReference])
);

