CREATE TABLE [dbo].[customer_68324] (
    [IdCustomer]              INT            IDENTITY (1, 1) NOT NULL,
    [Name]                    NVARCHAR (100) NOT NULL,
    [Description]             NVARCHAR (100) NULL,
    [Domain]                  NVARCHAR (50)  NOT NULL,
    [RegexSubject]            NVARCHAR (100) NOT NULL,
    [RegexEmail]              NVARCHAR (100) NOT NULL,
    [RegexFilename]           NVARCHAR (100) NOT NULL,
    [Abbreviation]            NVARCHAR (25)  NOT NULL,
    [IdCustomerType]          INT            NULL,
    [ConditionOfPaymentID]    INT            NULL,
    [CountryID]               VARCHAR (2)    NULL,
    [CommercialName]          NVARCHAR (50)  NULL,
    [CustomerPhone]           NVARCHAR (50)  NULL,
    [WebsiteURI]              NVARCHAR (50)  NULL,
    [ContactName]             NVARCHAR (50)  NULL,
    [ContactEmail]            NVARCHAR (50)  NULL,
    [NotificationAddress]     NVARCHAR (200) NULL,
    [SaleAdvisorID]           INT            NULL,
    [DateUpService]           DATETIME       NULL,
    [DateDownService]         DATETIME       NULL,
    [TypeOfBusinessID]        INT            NULL,
    [BusinessSegmentID]       INT            NULL,
    [BusinessActivityID]      INT            NULL,
    [CommercialSegmentID]     INT            NULL,
    [OperationContactName]    NVARCHAR (50)  NULL,
    [OperationContactPhone]   NVARCHAR (50)  NULL,
    [OperationContactEmail]   NVARCHAR (50)  NULL,
    [LegalSponsorName]        NVARCHAR (50)  NULL,
    [LegalSponsorLastName]    NVARCHAR (50)  NULL,
    [LegalSponsorDPI]         NVARCHAR (50)  NULL,
    [HasAgreement]            BIT            NULL,
    [AgreementNumber]         NVARCHAR (50)  NULL,
    [AgreementDateStart]      DATETIME       NULL,
    [AgreementDateEnd]        DATETIME       NULL,
    [InvoiceName]             NVARCHAR (100) NULL,
    [TaxIdentificationNumber] NVARCHAR (50)  NULL,
    [FiscalAddress]           NVARCHAR (200) NULL,
    [InvoiceEmail]            NVARCHAR (50)  NULL,
    [InvoiceContactName]      NVARCHAR (50)  NULL,
    [InvoiceContactPhone]     NVARCHAR (50)  NULL,
    [InvoiceContactEmail]     NVARCHAR (50)  NULL,
    [CODAccountBankID]        INT            NULL,
    [CODAccountNumber]        NVARCHAR (50)  NULL,
    [CODAccountName]          NVARCHAR (50)  NULL,
    [CODAccountTypeID]        INT            NULL,
    [CODCurrencyID]           INT            NULL,
    [CODContactName]          NVARCHAR (50)  NULL,
    [CODContactPhone]         NVARCHAR (50)  NULL,
    [CODContactEmail]         NVARCHAR (50)  NULL,
    [RowSatus]                BIT            NULL,
    [TokenCreated]            NVARCHAR (50)  NULL,
    [DateCreated]             DATETIME       NULL,
    [TokenUpdated]            NVARCHAR (50)  NULL,
    [DateUpdated]             DATETIME       NULL,
    [SAPCardCode]             NVARCHAR (50)  NULL,
    [ExcludePriceShippingCOD] BIT            NULL,
    [ExcludeCommissionCOD]    BIT            NULL,
    [CatBatchTypeCODId]       BIGINT         NULL,
    [CatBatchFrequencyCODId]  BIGINT         NULL,
    [CatTMSalesPersonId]      INT            NULL,
    [CutOffDate]              DATETIME       NULL,
    [UpgradeDate]             DATETIME       NULL,
    [CustomerGoalQuantity]    INT            NULL,
    [CatBillingTimeId]        INT            NULL,
    [CatBillingVolumeId]      INT            NULL,
    [BillingCut_offDate]      DATE           NULL,
    [NumImgEvidence]          INT            NULL,
    [IsCOD]                   INT            NULL
);

