CREATE TABLE [dbo].[PromoCardDetail] (
    [IdPromoCardDetail] BIGINT          IDENTITY (1, 1) NOT NULL,
    [PromoCardId]       INT             NOT NULL,
    [SystemId]          INT             NOT NULL,
    [ModuleId]          INT             NOT NULL,
    [RedeemTypeId]      INT             NULL,
    [AcumulationTypeId] INT             NULL,
    [CreditPoint]       DECIMAL (12, 2) NULL,
    [DebitPoint]        DECIMAL (12, 2) NULL,
    [RedeemAmount]      DECIMAL (12, 2) NULL,
    [GuidSerie]         NVARCHAR (2)    NULL,
    [GuidNumber]        INT             NULL,
    [GuideWeigth]       DECIMAL (12, 2) NULL,
    [GuideAmount]       DECIMAL (12, 2) NULL,
    [InvoiceHeaderId]   BIGINT          NULL,
    [RowStatus]         BIT             NOT NULL,
    [TokenCreated]      VARCHAR (50)    NOT NULL,
    [DateCreated]       DATETIME        NOT NULL,
    [TokenUpdated]      VARCHAR (50)    NULL,
    [DateUpdated]       DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([IdPromoCardDetail] ASC),
    CONSTRAINT [FKAcumulationPromoDet] FOREIGN KEY ([AcumulationTypeId]) REFERENCES [dbo].[AcumulationPointType] ([IdAcumulationPoint]),
    CONSTRAINT [FKPromoCardDet] FOREIGN KEY ([PromoCardId]) REFERENCES [dbo].[PromoCard] ([IdPromoCard]),
    CONSTRAINT [FKPromoGuide] FOREIGN KEY ([GuidSerie], [GuidNumber]) REFERENCES [dbo].[DeliveryOrder] ([Guide_Serie], [Guide_Number]),
    CONSTRAINT [FKPromoInvoiceDet] FOREIGN KEY ([InvoiceHeaderId]) REFERENCES [dbo].[invoiceHeader] ([inv_pk_id]),
    CONSTRAINT [FKPromoModuleDet] FOREIGN KEY ([ModuleId]) REFERENCES [dbo].[CatModule] ([ModIdModule]),
    CONSTRAINT [FKPromoSystemDet] FOREIGN KEY ([SystemId]) REFERENCES [dbo].[CatSystem] ([SysIdSystem]),
    CONSTRAINT [FKRedeemPromoDet] FOREIGN KEY ([RedeemTypeId]) REFERENCES [dbo].[RedeemType] ([IdRedeem])
);

