CREATE TABLE [dbo].[RateByHub] (
    [RbhId]                   INT             IDENTITY (1, 1) NOT NULL,
    [RbhIdRate]               INT             NOT NULL,
    [RbhIdHubSource]          INT             NOT NULL,
    [RbhIdHubDestiny]         INT             NOT NULL,
    [RbhIdTypeService]        INT             NOT NULL,
    [RbhRate]                 DECIMAL (12, 2) NOT NULL,
    [RbhFragileRate]          DECIMAL (14, 2) NULL,
    [RbhInsuranceRate]        DECIMAL (14, 2) NULL,
    [RbhCollectedRate]        DECIMAL (14, 2) NULL,
    [RbhWeightAdditionalRate] DECIMAL (14, 2) NULL,
    [RbhWeightLimit]          INT             NULL,
    [RbhWeightMeasure]        NVARCHAR (3)    NULL,
    [RbhDeliveryAttempts]     INT             NULL,
    [RbhCurrency]             NVARCHAR (3)    NOT NULL,
    [RbhRowStatus]            BIT             NOT NULL,
    [RbhTokenCreated]         VARCHAR (50)    NOT NULL,
    [RbhDateCreated]          DATETIME        NOT NULL,
    [RbhTokenUpdated]         VARCHAR (50)    NULL,
    [RvDateUpdated]           DATETIME        NULL,
    PRIMARY KEY CLUSTERED ([RbhId] ASC),
    CONSTRAINT [FKRbhHubDestiny] FOREIGN KEY ([RbhIdHubDestiny]) REFERENCES [dbo].[HubLogistics] ([IdHubLogistic]),
    CONSTRAINT [FKRbhHubSource] FOREIGN KEY ([RbhIdHubSource]) REFERENCES [dbo].[HubLogistics] ([IdHubLogistic]),
    CONSTRAINT [FKRbhRate] FOREIGN KEY ([RbhIdRate]) REFERENCES [dbo].[RateHeader] ([RheId]),
    CONSTRAINT [FKRbhTypeService] FOREIGN KEY ([RbhIdTypeService]) REFERENCES [dbo].[CatTypeService] ([CtsId])
);

