CREATE TABLE [dbo].[RateEstimateDetail] (
    [IdRateEstimateDetail] BIGINT          IDENTITY (1, 1) NOT NULL,
    [IdRateEstimate]       BIGINT          NULL,
    [IdSettlment]          BIGINT          NULL,
    [CountValue]           DECIMAL (18, 2) NULL,
    [IdSurcharge]          INT             NULL,
    [SurchargeDescription] NVARCHAR (50)   NULL,
    [PriceRate]            DECIMAL (18, 2) NULL,
    [PercentValue]         DECIMAL (18, 2) NULL,
    [TotalAmount]          DECIMAL (18, 2) NULL,
    [IdRateCategory]       INT             NULL,
    [Selected]             BIT             NULL,
    [DateExpire]           DATETIME        NULL,
    [EstimateDetailStatus] BIT             NULL,
    [TokenCreated]         NVARCHAR (50)   NULL,
    [DateCreated]          DATETIME        NULL,
    [TokenUpdated]         NVARCHAR (50)   NULL,
    [DateUpdated]          DATETIME        NULL,
    CONSTRAINT [PK_RateEstimateDetail] PRIMARY KEY CLUSTERED ([IdRateEstimateDetail] ASC),
    CONSTRAINT [FK_RateEstimateDetail_RateCategory] FOREIGN KEY ([IdRateCategory]) REFERENCES [dbo].[RateCategory] ([IdRateCategory]),
    CONSTRAINT [FK_RateEstimateDetail_RateEstimate] FOREIGN KEY ([IdRateEstimate]) REFERENCES [dbo].[RateEstimate] ([IdRateEstimated]),
    CONSTRAINT [FK_RateEstimateDetail_Settlement] FOREIGN KEY ([IdSettlment]) REFERENCES [dbo].[Settlement] ([IdSettlement]),
    CONSTRAINT [FK_RateEstimateDetail_Surcharge] FOREIGN KEY ([IdSurcharge]) REFERENCES [dbo].[Surcharge] ([IdSurcharge])
);

