--SELECT * FROM DeliveryBackOffice.dbo.CatRoute

BEGIN TRY
    BEGIN TRANSACTION;

    INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA302','USNA302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Ahuachapán Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA302','USNA302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Ahuachapán Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA302','USNA302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Ahuachapán Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA301','USNA301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Santa Ana Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA101','USNA101',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Santa Ana Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA101','USNA101',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Santa Ana Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA201','USNA201',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Santa Ana Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA301','USNA301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Santa Ana Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA303','USNA303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Sonsonate Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA303','USNA303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Sonsonate Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA303','USNA303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Sonsonate Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA303','USNA303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Sonsonate Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA201','USNA201',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Chalatenango Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA201','USNA201',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Chalatenango Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA201','USNA201',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Chalatenango Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('ULLB302','ULLB302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Libertad Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('ULLB301','ULLB301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Libertad Costa'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('ULLB101','ULLB101',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Libertad Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('ULLB302','ULLB302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Libertad Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('ULLB302','ULLB302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Libertad Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('ULLB301','ULLB301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Libertad Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('ULLB301','ULLB301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Libertad Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV001','USSV001',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV304','USSV304',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV309','USSV309',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV308','USSV308',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV306','USSV306',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV307','USSV307',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV305','USSV305',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV311','USSV311',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV310','USSV310',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Salvador Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV301','USSV301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Cuscatlán Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV301','USSV301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Cuscatlán Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV303','USSV303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Paz Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV303','USSV303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Paz Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV303','USSV303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Paz Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA201','USNA201',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Cabañas Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USNA201','USNA201',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Cabañas Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV302','USSV302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Vicente Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USSV302','USSV302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Vicente Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG302','USMG302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Usulután Este'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG302','USMG302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Usulután Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG302','USMG302',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Usulután Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG301','USMG301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Miguel Centro'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG301','USMG301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Miguel Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG301','USMG301',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'San Miguel Oeste'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG303','USMG303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Morazán Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG303','USMG303',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'Morazán Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG101','USMG101',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Unión Norte'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')
	INSERT INTO [dbo].[CatRoute] ([CodeRoute],[Description],[IdTownship],[IdTypeRoute],[Zone],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated],[CountryId]) VALUES ('USMG101','USMG101',(SELECT IdTownship FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) WHERE TownshipName = 'La Unión Sur'),4,NULL,1,'SYS-WOROZCO',GETDATE(),NULL,NULL,'SV')

	COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;

    -- Manejo de errores con PRINT
    DECLARE @ErrorMessage NVARCHAR(4000);
    SELECT @ErrorMessage = ERROR_MESSAGE();
    
    PRINT 'Error: ' + @ErrorMessage;
END CATCH;
