--SELECT * FROM DeliveryBackOffice.dbo.Container

--Ubicar el ultimo número segun tipo de contenedor
--SELECT TOP 1 ContainerNumber FROM DeliveryBackOffice.dbo.Container
--WHERE CatTypeContainerId = (SELECT IdCatTypeContainer FROM DeliveryBackOffice.dbo.CatTypeContainer
--WHERE TypeContainerSerie = 'PLT')
--ORDER BY DateCreated DESC


BEGIN TRY
    BEGIN TRANSACTION;

	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00626','BOX00626',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00627','BOX00627',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00628','BOX00628',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00629','BOX00629',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00630','BOX00630',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00631','BOX00631',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00632','BOX00632',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00633','BOX00633',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00634','BOX00634',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00635','BOX00635',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00636','BOX00636',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00637','BOX00637',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00638','BOX00638',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00639','BOX00639',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00640','BOX00640',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00641','BOX00641',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00642','BOX00642',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00643','BOX00643',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00644','BOX00644',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(1,'00645','BOX00645',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01077','LH01077',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01078','LH01078',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01079','LH01079',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01080','LH01080',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01081','LH01081',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01082','LH01082',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01083','LH01083',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01084','LH01084',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01085','LH01085',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(2,'01086','LH01086',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'00998','MTB00998',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'00999','MTB00999',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01000','MTB01000',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01001','MTB01001',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01002','MTB01002',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01003','MTB01003',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01004','MTB01004',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01005','MTB01005',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01006','MTB01006',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01007','MTB01007',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01008','MTB01008',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01009','MTB01009',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01010','MTB01010',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01011','MTB01011',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01012','MTB01012',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01013','MTB01013',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01014','MTB01014',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01015','MTB01015',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01016','MTB01016',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(5,'01017','MTB01017',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00002','VBX00002',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00003','VBX00003',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00004','VBX00004',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00005','VBX00005',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00006','VBX00006',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00007','VBX00007',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00008','VBX00008',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00009','VBX00009',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00010','VBX00010',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00011','VBX00011',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00012','VBX00012',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00013','VBX00013',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00014','VBX00014',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00015','VBX00015',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(6,'00016','VBX00016',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00301','PLT00301',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00302','PLT00302',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00303','PLT00303',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00304','PLT00304',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00305','PLT00305',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00306','PLT00306',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00307','PLT00307',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00308','PLT00308',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00309','PLT00309',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00310','PLT00310',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00311','PLT00311',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00312','PLT00312',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00313','PLT00313',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00314','PLT00314',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00315','PLT00315',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00316','PLT00316',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00317','PLT00317',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00318','PLT00318',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00319','PLT00319',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00320','PLT00320',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00321','PLT00321',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00322','PLT00322',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00323','PLT00323',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00324','PLT00324',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00325','PLT00325',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00326','PLT00326',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00327','PLT00327',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00328','PLT00328',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00329','PLT00329',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
	INSERT INTO [dbo].[Container] ([CatTypeContainerId],[ContainerNumber],[ContainerDescription],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
		VALUES(7,'00330','PLT00330',1,'SYS-WOROZCO',GETDATE(),NULL,NULL)
    
    COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;

    -- Manejo de errores con PRINT
    DECLARE @ErrorMessage NVARCHAR(4000);
    SELECT @ErrorMessage = ERROR_MESSAGE();
    
    PRINT 'Error: ' + @ErrorMessage;
END CATCH;
