BEGIN TRY
BEGIN TRANSACTION

 DECLARE @IdSegmentMetro      INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'MEG'),
         @IdSegmentLocal      INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'LOC'),
         @IdSegmentCapital    INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'CAG'),
         @IdSegmentDepart     INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FOR'),
         @IdSegmentRegional   INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'REG'),
         @IdSegmentForPeten   INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FPG'),
         @IdSegmentEspecial   INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'ESP'),
         @IdSegmentNacional   INT = (SELECT CrsId FROM CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'NAG');

DECLARE @IdRate          INT = (SELECT RheId FROM RateHeader WITH(NOLOCK) WHERE RheName ='Tarifario destinos express center' AND CountryId = 'GT'),
        @TypeServiceSTD  INT = (SELECT CtsId FROM CatTypeService WITH(NOLOCK) WHERE CtsShortName = 'STD'), --5
        @TypeServiceCOD  INT = (SELECT CtsId FROM CatTypeService WITH(NOLOCK) WHERE CtsShortName = 'COD'); --6

DECLARE @IdPeq   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Pequeño' and IdCountry = 'GT') AND Code = 'EXP076'),
        @IdMed   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Mediano' and IdCountry = 'GT') AND Code ='EXP077'),
        @IdGrand INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Grande' and IdCountry = 'GT') AND Code ='EXP078'),
        @IdExt   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Extra Grande' and IdCountry = 'GT') AND Code ='EXP079'),
        @IdSob   INT = (SELECT AbcId FROM ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Sobredimensionado' and IdCountry = 'GT') AND Code ='EXP080');


 --*********************  ESTANDAR  *********************

--INHABILITAR TARIFAS ANTIGUAS (ESTANDAR)
UPDATE RateData
SET RowStatus = 0,
    TokenUpdated = 'SYS-BPEDROZA',
    DateUpdated = GETDATE()
WHERE RateId = @IdRate AND RowStatus = 1 AND TypeServiceId IS NOT NULL AND TypeServiceId = @TypeServiceSTD;

--COBERTURA METRO
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdPeq,23.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdMed,33.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdGrand,53.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdExt,63.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdSob,73.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA LOCAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdPeq,28.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdMed,38.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdGrand,58.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdExt,68.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdSob,78.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA DEPARTAMENTAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdPeq,33.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdMed,43.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdGrand,63.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdExt,73.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdSob,83.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA REGIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdPeq,38.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdMed,48.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdGrand,68.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdExt,78.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdSob,88.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA NACIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdPeq,43.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdMed,53.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdGrand,73.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdExt,83.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdSob,93.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA PETEN
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForPeten,NULL,NULL,@IdPeq,48.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForPeten,NULL,NULL,@IdMed,58.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForPeten,NULL,NULL,@IdGrand,78.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForPeten,NULL,NULL,@IdExt,88.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForPeten,NULL,NULL,@IdSob,98.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA ESPECIAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdPeq,63.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdMed,73.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdGrand,93.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdExt,103.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdSob,113.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA CAPITAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentCapital,NULL,NULL,@IdPeq,33.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentCapital,NULL,NULL,@IdMed,43.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentCapital,NULL,NULL,@IdGrand,63.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentCapital,NULL,NULL,@IdExt,73.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentCapital,NULL,NULL,@IdSob,83.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


 --*********************  COD  *********************

--INHABILITAR TARIFAS ANTIGUAS (COD)
UPDATE RateData
SET RowStatus = 0,
    TokenUpdated = 'SYS-BPEDROZA',
    DateUpdated = GETDATE()
WHERE RateId = @IdRate AND RowStatus = 1 AND TypeServiceId IS NOT NULL AND TypeServiceId = @TypeServiceCOD;

--COBERTURA METRO
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdPeq,22.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdMed,32.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdGrand,52.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdExt,62.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdSob,72.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA LOCAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdPeq,26.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdMed,36.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdGrand,56.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdExt,66.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdSob,76.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA DEPARTAMENTAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdPeq,32.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdMed,42.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdGrand,62.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdExt,72.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdSob,82.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA REGIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdPeq,34.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdMed,44.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdGrand,64.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdExt,74.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdSob,84.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA NACIONAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdPeq,36.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdMed,46.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdGrand,66.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdExt,76.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdSob,86.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA FORANEA PETEN
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForPeten,NULL,NULL,@IdPeq,38.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForPeten,NULL,NULL,@IdMed,48.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForPeten,NULL,NULL,@IdGrand,68.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForPeten,NULL,NULL,@IdExt,78.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForPeten,NULL,NULL,@IdSob,88.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA ESPECIAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdPeq,46.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdMed,56.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdGrand,76.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdExt,86.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdSob,96.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

--COBERTURA CAPITAL
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentCapital,NULL,NULL,@IdPeq,32.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentCapital,NULL,NULL,@IdMed,42.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentCapital,NULL,NULL,@IdGrand,62.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentCapital,NULL,NULL,@IdExt,72.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentCapital,NULL,NULL,@IdSob,82.5,1,'SYS-BPEDROZA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


COMMIT TRANSACTION
    PRINT 'Actualización realizada correctamente.'
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION

    PRINT 'Ocurrió un error al ejecutar la actualización.'
    PRINT ERROR_MESSAGE()
END CATCH
