/*
	SCRIPT PARA PODER AGREGAR EL ROL DE EXPRESS CENTER
*/


INSERT INTO CatRol VALUES(1,'ENCARGADO EXPRESS CENTER FD HERMES', 'ENCARGADO EXPRESS CENTER FD HERMES',0,0,1,'SYS-MJIMENEZ',GETDATE(), NULL, NULL)