-- SCRIP PARA LIMPIAR CONFIGURACION DE CLIENTES PARA SOCIOS DE NEGOCIO
BEGIN TRY
    BEGIN TRANSACTION;
		UPDATE DeliveryBackOffice.dbo.visitpointconfiguration
		SET CODAccountBankTypeID = NULL,
		CODAccountCurrencyID = NULL
		WHERE CODAccountBankID IS NULL
		AND CODAccountBankTypeID IS NOT NULL;
	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
END CATCH
