SELECT * FROM DeliveryBackOffice.dbo.Township WITH(NOLOCK) --Municipios

BEGIN TRY
    BEGIN TRANSACTION;

INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Ahuachapán Centro','Ahuachapán Centro',NULL,NULL,NULL,1,41,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0101')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Ahuachapán Norte','Ahuachapán Norte',NULL,NULL,NULL,1,41,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0102')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Ahuachapán Sur','Ahuachapán Sur',NULL,NULL,NULL,1,41,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0103')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Santa Ana Centro','Santa Ana Centro',NULL,NULL,NULL,1,52,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0201')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Santa Ana Este','Santa Ana Este',NULL,NULL,NULL,1,52,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0202')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Santa Ana Norte','Santa Ana Norte',NULL,NULL,NULL,1,52,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0203')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Santa Ana Oeste','Santa Ana Oeste',NULL,NULL,NULL,1,52,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0204')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Sonsonate Centro','Sonsonate Centro',NULL,NULL,NULL,1,53,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0301')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Sonsonate Este','Sonsonate Este',NULL,NULL,NULL,1,53,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0302')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Sonsonate Norte','Sonsonate Norte',NULL,NULL,NULL,1,53,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0303')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Sonsonate Oeste','Sonsonate Oeste',NULL,NULL,NULL,1,53,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0304')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Chalatenango Centro','Chalatenango Centro',NULL,NULL,NULL,1,43,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0401')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Chalatenango Norte','Chalatenango Norte',NULL,NULL,NULL,1,43,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0402')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Chalatenango Sur','Chalatenango Sur',NULL,NULL,NULL,1,43,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0403')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Libertad Centro','La Libertad Centro',NULL,NULL,NULL,1,45,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0501')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Libertad Costa','La Libertad Costa',NULL,NULL,NULL,1,45,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0502')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Libertad Este','La Libertad Este',NULL,NULL,NULL,1,45,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0503')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Libertad Norte','La Libertad Norte',NULL,NULL,NULL,1,45,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0504')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Libertad Oeste','La Libertad Oeste',NULL,NULL,NULL,1,45,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0505')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Libertad Sur','La Libertad Sur',NULL,NULL,NULL,1,45,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0506')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Salvador Centro','San Salvador Centro',NULL,NULL,NULL,1,50,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0601')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Salvador Este','San Salvador Este',NULL,NULL,NULL,1,50,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0602')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Salvador Norte','San Salvador Norte',NULL,NULL,NULL,1,50,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0603')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Salvador Oeste','San Salvador Oeste',NULL,NULL,NULL,1,50,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0604')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Salvador Sur','San Salvador Sur',NULL,NULL,NULL,1,50,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0605')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Cuscatlán Norte','Cuscatlán Norte',NULL,NULL,NULL,1,44,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0701')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Cuscatlán Sur','Cuscatlán Sur',NULL,NULL,NULL,1,44,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0702')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Paz Centro','La Paz Centro',NULL,NULL,NULL,1,46,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0801')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Paz Este','La Paz Este',NULL,NULL,NULL,1,46,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0802')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Paz Oeste','La Paz Oeste',NULL,NULL,NULL,1,46,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0803')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Cabañas Este','Cabañas Este',NULL,NULL,NULL,1,42,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0901')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Cabañas Oeste','Cabañas Oeste',NULL,NULL,NULL,1,42,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S0902')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Vicente Norte','San Vicente Norte',NULL,NULL,NULL,1,51,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1001')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Vicente Sur','San Vicente Sur',NULL,NULL,NULL,1,51,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1002')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Usulután Este','Usulután Este',NULL,NULL,NULL,1,54,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1101')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Usulután Norte','Usulután Norte',NULL,NULL,NULL,1,54,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1102')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Usulután Oeste','Usulután Oeste',NULL,NULL,NULL,1,54,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1103')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Miguel Centro','San Miguel Centro',NULL,NULL,NULL,1,49,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1201')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Miguel Norte','San Miguel Norte',NULL,NULL,NULL,1,49,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1202')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('San Miguel Oeste','San Miguel Oeste',NULL,NULL,NULL,1,49,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1203')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Morazán Norte','Morazán Norte',NULL,NULL,NULL,1,48,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1301')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('Morazán Sur','Morazán Sur',NULL,NULL,NULL,1,48,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1302')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Unión Norte','La Unión Norte',NULL,NULL,NULL,1,47,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1401')
INSERT INTO [dbo].[Township]([TownshipName],[TownshipDescription],[TownshipLatitud],[TownshipLongitud],[PostalCode],[TownshipStatus],[IdProvince],[TokenCreated],[DateCreated],[TokenUpdated],[DatedUpdated],[HeaderCode])VALUES('La Unión Sur','La Unión Sur',NULL,NULL,NULL,1,47,'SYS-WOROZCO',GETDATE(),NULL,NULL,'S1402')

 COMMIT TRANSACTION;
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;

    -- Manejo de errores con PRINT
    DECLARE @ErrorMessage NVARCHAR(4000);
    SELECT @ErrorMessage = ERROR_MESSAGE();
    
    PRINT 'Error: ' + @ErrorMessage;
END CATCH;
