USE [DeliveryBackOffice]
GO

INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('SOCIEDAD LIMITADA','Sociedad Limitada','GT','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('SOCIEDAD ANONIMA','Sociedad Anonima','GT','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('SOCIEDAD COMANDITA','Sociedad Comandita','GT','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('SOCIEDAD MIXTA','Sociedad Mixta','GT','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('SIN ANIMO DE LUCRO','Sin animo de lucro','GT','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('INDIVIDUAL','Individual','GT','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('GUBERNAMENTAL','Gubernamental','GT','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('SOLE PROPRIETORSHIP','The simplest type of business. Sole proprietorships are owned and operated by a single person and are very easy to set up.','US','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('PARTNERSHIP','A business owned by two or more people who share responsibilities and profits.','US','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('LIMITED PARTNERSHIP','A business partnership, often between business operators and investors.','US','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('CORPORATION','A type of fully-independent business with shareholders. One of the most complex business types.','US','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('LIMITED LIABILITY COMPANY (LLC)','A mixture of a partnership and a corporation, designed to make it easier to start small businesses. One of the most popular business types for startups.','US','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('NONPROFIT ORGANIZATION','A type of business that uses its profits for charitable purposes. Tax-exempt, but must follow special rules.','US','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
INSERT INTO [dbo].[CatTypeOfBusiness] ([TypeOfBusinessName],[TypeOfBusinessDescription],[CountryID],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])VALUES('COOPERATIVOE (CO-OP)','A business owned and operated for the benefit of the members of the organization that use its services.','US','TRUE','SYS-ERAMIREZ',GETDATE(),NULL,NULL)
GO
