UPDATE Province set LocalCode = '01' where ProvinceName = 'Guatemala'
UPDATE Province set LocalCode = '02' where ProvinceName = 'El Progreso'
UPDATE Province set LocalCode = '03' where ProvinceName = 'Sacatepéquez'
UPDATE Province set LocalCode = '04' where ProvinceName = 'Chimaltenango'
UPDATE Province set LocalCode = '05' where ProvinceName = 'Escuintla'
UPDATE Province set LocalCode = '06' where ProvinceName = 'Santa Rosa'
UPDATE Province set LocalCode = '07' where ProvinceName = 'Solola'
UPDATE Province set LocalCode = '08' where ProvinceName = 'Totonicapán'
UPDATE Province set LocalCode = '09' where ProvinceName = 'Quetzaltenango'
UPDATE Province set LocalCode = '10' where ProvinceName = 'Suchitepéquez'
UPDATE Province set LocalCode = '11' where ProvinceName = 'Retalhuleu'
UPDATE Province set LocalCode = '12' where ProvinceName = 'San Marcos'
UPDATE Province set LocalCode = '13' where ProvinceName = 'Huehuetenango'
UPDATE Province set LocalCode = '14' where ProvinceName = 'Quiché'
UPDATE Province set LocalCode = '15' where ProvinceName = 'Baja Verapaz'
UPDATE Province set LocalCode = '16' where ProvinceName = 'Alta Verapaz'
UPDATE Province set LocalCode = '17' where ProvinceName = 'Petén'
UPDATE Province set LocalCode = '18' where ProvinceName = 'Izabal'
UPDATE Province set LocalCode = '19' where ProvinceName = 'Zacapa'
UPDATE Province set LocalCode = '20' where ProvinceName = 'Chiquimula'
UPDATE Province set LocalCode = '21' where ProvinceName = 'Jalapa'
UPDATE Province set LocalCode = '22' where ProvinceName = 'Jutiapa'
