
USE DeliveryBackOffice


UPDATE Township set HeaderCode = '0101' where TownshipName = 'Guatemala'
UPDATE Township set HeaderCode = '0102' where TownshipName = 'Santa Catarina Pinula'
UPDATE Township set HeaderCode = '0103' where TownshipName = 'San Jose Pinula'
UPDATE Township set HeaderCode = '0104' where TownshipName = 'San Jose Del Golfo'
UPDATE Township set HeaderCode = '0105' where TownshipName = 'Palencia'
UPDATE Township set HeaderCode = '0106' where TownshipName = 'Chinautla'
UPDATE Township set HeaderCode = '0107' where TownshipName = 'San Pedro Ayampuc'
UPDATE Township set HeaderCode = '0108' where TownshipName = 'Mixco'
UPDATE Township set HeaderCode = '0109' where TownshipName = 'San Pedro Sacatepequez'
UPDATE Township set HeaderCode = '0110' where TownshipName = 'San Juan Sacatepequez'
UPDATE Township set HeaderCode = '0111' where TownshipName = 'San Raymundo'
UPDATE Township set HeaderCode = '0112' where TownshipName = 'Chuarrancho'
UPDATE Township set HeaderCode = '0113' where TownshipName = 'Fraijanes'
UPDATE Township set HeaderCode = '0114' where TownshipName = 'Amatitlan'
UPDATE Township set HeaderCode = '0115' where TownshipName = 'Villa Nueva'
UPDATE Township set HeaderCode = '0116' where TownshipName = 'Villa Canales'
UPDATE Township set HeaderCode = '0117' where TownshipName = 'San Miguel Petapa'
UPDATE Township set HeaderCode = '0201' where TownshipName = 'Guastatoya'
UPDATE Township set HeaderCode = '0202' where TownshipName = 'Morazan'
UPDATE Township set HeaderCode = '0203' where TownshipName = 'San Agustin Acasaguastlan'
UPDATE Township set HeaderCode = '0204' where TownshipName = 'San Cristobal Acasaguastlan'
UPDATE Township set HeaderCode = '0205' where TownshipName = 'El Jicaro'
UPDATE Township set HeaderCode = '0206' where TownshipName = 'Sansare'
UPDATE Township set HeaderCode = '0207' where TownshipName = 'Sanarate'
UPDATE Township set HeaderCode = '0208' where TownshipName = 'San Antonio la Paz'
UPDATE Township set HeaderCode = '0301' where TownshipName = 'Antigua Guatemala'
UPDATE Township set HeaderCode = '0302' where TownshipName = 'Jocotenango'
UPDATE Township set HeaderCode = '0303' where TownshipName = 'Pastores'
UPDATE Township set HeaderCode = '0304' where TownshipName = 'Sumpango'
UPDATE Township set HeaderCode = '0305' where TownshipName = 'Santo Domingo Xenacoj'
UPDATE Township set HeaderCode = '0306' where TownshipName = 'Santiago Sacatepequez'
UPDATE Township set HeaderCode = '0307' where TownshipName = 'San Bartolome Milpas Altas'
UPDATE Township set HeaderCode = '0308' where TownshipName = 'San Lucas Sacatepequez'
UPDATE Township set HeaderCode = '0309' where TownshipName = 'Santa Lucia Milpas Altas'
UPDATE Township set HeaderCode = '0310' where TownshipName = 'Magdalena Milpas Altas'
UPDATE Township set HeaderCode = '0311' where TownshipName = 'Santa Maria de Jesus'
UPDATE Township set HeaderCode = '0312' where TownshipName = 'Ciudad Vieja'
UPDATE Township set HeaderCode = '0313' where TownshipName = 'San Miguel Dueñas'
UPDATE Township set HeaderCode = '0314' where TownshipName = 'San Juan Alotenango'
UPDATE Township set HeaderCode = '0315' where TownshipName = 'San Antonio Aguas Calientes'
UPDATE Township set HeaderCode = '0316' where TownshipName = 'Santa Catarina Barahona'
UPDATE Township set HeaderCode = '0401' where TownshipName = 'Chimaltenango'
UPDATE Township set HeaderCode = '0402' where TownshipName = 'San Jose Poaquil'
UPDATE Township set HeaderCode = '0403' where TownshipName = 'San Martin Jilotepeque'
UPDATE Township set HeaderCode = '0404' where TownshipName = 'San Juan Comalapa'
UPDATE Township set HeaderCode = '0405' where TownshipName = 'Santa Apolonia'
UPDATE Township set HeaderCode = '0406' where TownshipName = 'Tecpan Guatemala'
UPDATE Township set HeaderCode = '0407' where TownshipName = 'Patzun'
UPDATE Township set HeaderCode = '0408' where TownshipName = 'Pochuta'
UPDATE Township set HeaderCode = '0409' where TownshipName = 'Patzicia'
UPDATE Township set HeaderCode = '0410' where TownshipName = 'Santa Cruz Balanya'
UPDATE Township set HeaderCode = '0411' where TownshipName = 'Acatenango'
UPDATE Township set HeaderCode = '0412' where TownshipName = 'San Pedro Yepocapa'
UPDATE Township set HeaderCode = '0413' where TownshipName = 'San Andres Itzapa'
UPDATE Township set HeaderCode = '0414' where TownshipName = 'Parramos'
UPDATE Township set HeaderCode = '0415' where TownshipName = 'Zaragoza'
UPDATE Township set HeaderCode = '0416' where TownshipName = 'El Tejar'
UPDATE Township set HeaderCode = '0501' where TownshipName = 'Escuintla'
UPDATE Township set HeaderCode = '0502' where TownshipName = 'Santa Lucia Cotzumalguapa'
UPDATE Township set HeaderCode = '0503' where TownshipName = 'La Democracia'
UPDATE Township set HeaderCode = '0504' where TownshipName = 'Siquinala'
UPDATE Township set HeaderCode = '0505' where TownshipName = 'Masagua'
UPDATE Township set HeaderCode = '0506' where TownshipName = 'Tiquisate'
UPDATE Township set HeaderCode = '0507' where TownshipName = 'La Gomera'
UPDATE Township set HeaderCode = '0508' where TownshipName = 'Guanagazapa'
UPDATE Township set HeaderCode = '0509' where TownshipName = 'Puerto San Jose'
UPDATE Township set HeaderCode = '0510' where TownshipName = 'Iztapa'
UPDATE Township set HeaderCode = '0511' where TownshipName = 'Palin'
UPDATE Township set HeaderCode = '0512' where TownshipName = 'San Vicente Pacaya'
UPDATE Township set HeaderCode = '0513' where TownshipName = 'Nueva Concepcion'
UPDATE Township set HeaderCode = '0601' where TownshipName = 'Cuilapa'
UPDATE Township set HeaderCode = '0602' where TownshipName = 'Barberena'
UPDATE Township set HeaderCode = '0603' where TownshipName = 'Santa Rosa de Lima'
UPDATE Township set HeaderCode = '0604' where TownshipName = 'Casillas'
UPDATE Township set HeaderCode = '0605' where TownshipName = 'San Rafael las Flores'
UPDATE Township set HeaderCode = '0606' where TownshipName = 'Oratorio'
UPDATE Township set HeaderCode = '0607' where TownshipName = 'San Juan Tecuaco'
UPDATE Township set HeaderCode = '0608' where TownshipName = 'Chiquimulilla'
UPDATE Township set HeaderCode = '0609' where TownshipName = 'Taxisco'
UPDATE Township set HeaderCode = '0610' where TownshipName = 'Santa Maria Ixhuatan'
UPDATE Township set HeaderCode = '0611' where TownshipName = 'Guazacapan'
UPDATE Township set HeaderCode = '0612' where TownshipName = 'Santa Cruz Naranjo'
UPDATE Township set HeaderCode = '0613' where TownshipName = 'Pueblo Nuevo Viñas'
UPDATE Township set HeaderCode = '0614' where TownshipName = 'Nueva Santa Rosa'
UPDATE Township set HeaderCode = '0701' where TownshipName = 'Solola'
UPDATE Township set HeaderCode = '0702' where TownshipName = 'San Jose Chacaya'
UPDATE Township set HeaderCode = '0703' where TownshipName = 'Santa Maria Visitacion'
UPDATE Township set HeaderCode = '0704' where TownshipName = 'Santa Lucia Utatlan'
UPDATE Township set HeaderCode = '0705' where TownshipName = 'Nahuala'
UPDATE Township set HeaderCode = '0706' where TownshipName = 'Santa Catarina Ixtahuacan'
UPDATE Township set HeaderCode = '0707' where TownshipName = 'Santa Clara la Laguna'
UPDATE Township set HeaderCode = '0708' where TownshipName = 'Concepcion'
UPDATE Township set HeaderCode = '0709' where TownshipName = 'San Andres Semetabaj'
UPDATE Township set HeaderCode = '0710' where TownshipName = 'Panajachel'
UPDATE Township set HeaderCode = '0711' where TownshipName = 'Santa Catarina Palopo'
UPDATE Township set HeaderCode = '0712' where TownshipName = 'San Antonio Palopo'
UPDATE Township set HeaderCode = '0713' where TownshipName = 'San Lucas Toliman'
UPDATE Township set HeaderCode = '0714' where TownshipName = 'Santa Cruz la Laguna'
UPDATE Township set HeaderCode = '0715' where TownshipName = 'San Pablo la Laguna'
UPDATE Township set HeaderCode = '0716' where TownshipName = 'San Marcos la Laguna'
UPDATE Township set HeaderCode = '0717' where TownshipName = 'San Juan la Laguna'
UPDATE Township set HeaderCode = '0718' where TownshipName = 'San Pedro la Laguna'
UPDATE Township set HeaderCode = '0719' where TownshipName = 'Santiago Atitlan'
UPDATE Township set HeaderCode = '0801' where TownshipName = 'Totonicapan'
UPDATE Township set HeaderCode = '0802' where TownshipName = 'San Cristobal Totonicapan'
UPDATE Township set HeaderCode = '0803' where TownshipName = 'San Francisco el Alto'
UPDATE Township set HeaderCode = '0804' where TownshipName = 'San Andres Xecul'
UPDATE Township set HeaderCode = '0805' where TownshipName = 'Momostenango'
UPDATE Township set HeaderCode = '0806' where TownshipName = 'Santa Maria Chiquimula'
UPDATE Township set HeaderCode = '0807' where TownshipName = 'Santa Lucia la Reforma'
UPDATE Township set HeaderCode = '0808' where TownshipName = 'San Bartolo Aguas Calientes'
UPDATE Township set HeaderCode = '0901' where TownshipName = 'Quetzaltenango'
UPDATE Township set HeaderCode = '0902' where TownshipName = 'Salcaja'
UPDATE Township set HeaderCode = '0903' where TownshipName = 'Olintepeque'
UPDATE Township set HeaderCode = '0904' where TownshipName = 'San Carlos Sija'
UPDATE Township set HeaderCode = '0905' where TownshipName = 'Sibilia'
UPDATE Township set HeaderCode = '0906' where TownshipName = 'Cabrican'
UPDATE Township set HeaderCode = '0907' where TownshipName = 'Cajola'
UPDATE Township set HeaderCode = '0908' where TownshipName = 'San Miguel Siguila'
UPDATE Township set HeaderCode = '0909' where TownshipName = 'San Juan Ostuncalco'
UPDATE Township set HeaderCode = '0910' where TownshipName = 'San Mateo'
UPDATE Township set HeaderCode = '0911' where TownshipName = 'Concepcion Chiquirichapa'
UPDATE Township set HeaderCode = '0912' where TownshipName = 'San Martin Sacatepequez'
UPDATE Township set HeaderCode = '0913' where TownshipName = 'Almolonga'
UPDATE Township set HeaderCode = '0914' where TownshipName = 'Cantel'
UPDATE Township set HeaderCode = '0915' where TownshipName = 'Huitan'
UPDATE Township set HeaderCode = '0916' where TownshipName = 'Zunil'
UPDATE Township set HeaderCode = '0917' where TownshipName = 'Colomba'
UPDATE Township set HeaderCode = '0918' where TownshipName = 'San Francisco la Union'
UPDATE Township set HeaderCode = '0919' where TownshipName = 'El Palmar'
UPDATE Township set HeaderCode = '0920' where TownshipName = 'Coatepeque'
UPDATE Township set HeaderCode = '0921' where TownshipName = 'Genova'
UPDATE Township set HeaderCode = '0922' where TownshipName = 'Flores Costa Cuca'
UPDATE Township set HeaderCode = '0923' where TownshipName = 'La Esperanza'
UPDATE Township set HeaderCode = '0924' where TownshipName = 'Palestina de los Altos'
UPDATE Township set HeaderCode = '1001' where TownshipName = 'Mazatenango'
UPDATE Township set HeaderCode = '1002' where TownshipName = 'Cuyotenango'
UPDATE Township set HeaderCode = '1003' where TownshipName = 'San Francisco Zapotitlan'
UPDATE Township set HeaderCode = '1004' where TownshipName = 'San Bernardino'
UPDATE Township set HeaderCode = '1005' where TownshipName = 'San Jose el Idolo'
UPDATE Township set HeaderCode = '1006' where TownshipName = 'Santo Domingo'
UPDATE Township set HeaderCode = '1007' where TownshipName = 'San Lorenzo Suchitepequez'
UPDATE Township set HeaderCode = '1008' where TownshipName = 'Samayac'
UPDATE Township set HeaderCode = '1009' where TownshipName = 'San Pablo Jocopilas'
UPDATE Township set HeaderCode = '1010' where TownshipName = 'San Antonio Suchitepequez'
UPDATE Township set HeaderCode = '1011' where TownshipName = 'San Miguel Panan'
UPDATE Township set HeaderCode = '1012' where TownshipName = 'San Gabriel'
UPDATE Township set HeaderCode = '1013' where TownshipName = 'Chicacao'
UPDATE Township set HeaderCode = '1014' where TownshipName = 'Patulul'
UPDATE Township set HeaderCode = '1015' where TownshipName = 'Santa Barbara'
UPDATE Township set HeaderCode = '1016' where TownshipName = 'San Juan Bautista'
UPDATE Township set HeaderCode = '1017' where TownshipName = 'Santo Tomas la Union'
UPDATE Township set HeaderCode = '1018' where TownshipName = 'Zunilito'
UPDATE Township set HeaderCode = '1019' where TownshipName = 'Pueblo Nuevo'
UPDATE Township set HeaderCode = '1020' where TownshipName = 'Rio Bravo'
UPDATE Township set HeaderCode = '1021' where TownshipName = 'San Jose La Maquina'
UPDATE Township set HeaderCode = '1101' where TownshipName = 'Retalhuleu'
UPDATE Township set HeaderCode = '1102' where TownshipName = 'San Sebastian'
UPDATE Township set HeaderCode = '1103' where TownshipName = 'Santa Cruz Mulua'
UPDATE Township set HeaderCode = '1104' where TownshipName = 'San Martin Zapotitlan'
UPDATE Township set HeaderCode = '1105' where TownshipName = 'San Felipe'
UPDATE Township set HeaderCode = '1106' where TownshipName = 'San Andres Villa Seca'
UPDATE Township set HeaderCode = '1107' where TownshipName = 'Champerico'
UPDATE Township set HeaderCode = '1108' where TownshipName = 'Nuevo San Carlos'
UPDATE Township set HeaderCode = '1109' where TownshipName = 'El Asintal'
UPDATE Township set HeaderCode = '1201' where TownshipName = 'San Marcos'
UPDATE Township set HeaderCode = '1202' where TownshipName = 'San Pedro Sacatepequez'
UPDATE Township set HeaderCode = '1203' where TownshipName = 'San Antonio Sacatepequez'
UPDATE Township set HeaderCode = '1204' where TownshipName = 'Comitancillo'
UPDATE Township set HeaderCode = '1205' where TownshipName = 'San Miguel Ixtahuacan'
UPDATE Township set HeaderCode = '1206' where TownshipName = 'Concepcion Tutuapa'
UPDATE Township set HeaderCode = '1207' where TownshipName = 'Tacana'
UPDATE Township set HeaderCode = '1208' where TownshipName = 'Sibinal'
UPDATE Township set HeaderCode = '1209' where TownshipName = 'Tajumulco'
UPDATE Township set HeaderCode = '1210' where TownshipName = 'Tejutla'
UPDATE Township set HeaderCode = '1211' where TownshipName = 'San Rafael Pie de la Cuesta'
UPDATE Township set HeaderCode = '1212' where TownshipName = 'Nuevo Progreso'
UPDATE Township set HeaderCode = '1213' where TownshipName = 'El Tumbador'
UPDATE Township set HeaderCode = '1214' where TownshipName = 'El Rodeo'
UPDATE Township set HeaderCode = '1215' where TownshipName = 'Malacatan'
UPDATE Township set HeaderCode = '1216' where TownshipName = 'Catarina'
UPDATE Township set HeaderCode = '1217' where TownshipName = 'Ayutla'
UPDATE Township set HeaderCode = '1218' where TownshipName = 'Ocos'
UPDATE Township set HeaderCode = '1219' where TownshipName = 'San Pablo'
UPDATE Township set HeaderCode = '1220' where TownshipName = 'El Quetzal'
UPDATE Township set HeaderCode = '1221' where TownshipName = 'La Reforma'
UPDATE Township set HeaderCode = '1222' where TownshipName = 'Pajapita'
UPDATE Township set HeaderCode = '1223' where TownshipName = 'Ixchiguan'
UPDATE Township set HeaderCode = '1224' where TownshipName = 'San Jose Ojetenam'
UPDATE Township set HeaderCode = '1225' where TownshipName = 'San Cristobal Cucho'
UPDATE Township set HeaderCode = '1226' where TownshipName = 'Sipacapa'
UPDATE Township set HeaderCode = '1227' where TownshipName = 'Esquipulas Palo Gordo'
UPDATE Township set HeaderCode = '1228' where TownshipName = 'Rio Blanco'
UPDATE Township set HeaderCode = '1229' where TownshipName = 'San Lorenzo'
UPDATE Township set HeaderCode = '1230' where TownshipName = 'La Blanca'
UPDATE Township set HeaderCode = '1301' where TownshipName = 'Huehuetenango'
UPDATE Township set HeaderCode = '1302' where TownshipName = 'Chiantla'
UPDATE Township set HeaderCode = '1303' where TownshipName = 'Malacatancito'
UPDATE Township set HeaderCode = '1304' where TownshipName = 'Cuilco'
UPDATE Township set HeaderCode = '1305' where TownshipName = 'Nenton'
UPDATE Township set HeaderCode = '1306' where TownshipName = 'San Pedro Necta'
UPDATE Township set HeaderCode = '1307' where TownshipName = 'Jacaltenango'
UPDATE Township set HeaderCode = '1308' where TownshipName = 'San Pedro Soloma'
UPDATE Township set HeaderCode = '1309' where TownshipName = 'San Idelfonso Ixtaguacan'
UPDATE Township set HeaderCode = '1310' where TownshipName = 'Santa Barbara Huehuetenango'
UPDATE Township set HeaderCode = '1311' where TownshipName = 'La Libertad Huehuetenango'
UPDATE Township set HeaderCode = '1312' where TownshipName = 'La Democracia Huehuetenango'
UPDATE Township set HeaderCode = '1313' where TownshipName = 'San Miguel Acatan'
UPDATE Township set HeaderCode = '1314' where TownshipName = 'San Rafael la Independencia'
UPDATE Township set HeaderCode = '1315' where TownshipName = 'Todos Santos Cuchumatanes'
UPDATE Township set HeaderCode = '1316' where TownshipName = 'San Juan Atitan'
UPDATE Township set HeaderCode = '1317' where TownshipName = 'Santa Eulalia'
UPDATE Township set HeaderCode = '1318' where TownshipName = 'San Mateo Ixtatan'
UPDATE Township set HeaderCode = '1319' where TownshipName = 'Colotenango'
UPDATE Township set HeaderCode = '1320' where TownshipName = 'San Sebastian Huehuetenango'
UPDATE Township set HeaderCode = '1321' where TownshipName = 'Tectitan'
UPDATE Township set HeaderCode = '1322' where TownshipName = 'Concepcion Huista'
UPDATE Township set HeaderCode = '1323' where TownshipName = 'San Juan Ixcoy'
UPDATE Township set HeaderCode = '1324' where TownshipName = 'San Antonio Huista'
UPDATE Township set HeaderCode = '1325' where TownshipName = 'San Sebastian Coatan'
UPDATE Township set HeaderCode = '1326' where TownshipName = 'Santa Cruz Barillas'
UPDATE Township set HeaderCode = '1327' where TownshipName = 'Aguacatan'
UPDATE Township set HeaderCode = '1328' where TownshipName = 'San Rafael Petzal'
UPDATE Township set HeaderCode = '1329' where TownshipName = 'San Gaspar Ixchil'
UPDATE Township set HeaderCode = '1330' where TownshipName = 'Santiago Chimaltenango'
UPDATE Township set HeaderCode = '1331' where TownshipName = 'Santa Ana Huista'
UPDATE Township set HeaderCode = '1332' where TownshipName = 'Union Cantinil'
UPDATE Township set HeaderCode = '1401' where TownshipName = 'Santa Cruz del Quiche'
UPDATE Township set HeaderCode = '1402' where TownshipName = 'Chiche'
UPDATE Township set HeaderCode = '1403' where TownshipName = 'Chinique'
UPDATE Township set HeaderCode = '1404' where TownshipName = 'Zacualpa'
UPDATE Township set HeaderCode = '1405' where TownshipName = 'Chajul'
UPDATE Township set HeaderCode = '1406' where TownshipName = 'Chichicastenango'
UPDATE Township set HeaderCode = '1407' where TownshipName = 'Patzite'
UPDATE Township set HeaderCode = '1408' where TownshipName = 'San Antonio Ilotenango'
UPDATE Township set HeaderCode = '1409' where TownshipName = 'San Pedro Jocopilas'
UPDATE Township set HeaderCode = '1410' where TownshipName = 'Cunen'
UPDATE Township set HeaderCode = '1411' where TownshipName = 'San Juan Cotzal'
UPDATE Township set HeaderCode = '1412' where TownshipName = 'Joyabaj'
UPDATE Township set HeaderCode = '1413' where TownshipName = 'Nebaj'
UPDATE Township set HeaderCode = '1414' where TownshipName = 'San Andres Sajcabaja'
UPDATE Township set HeaderCode = '1415' where TownshipName = 'Uspantan'
UPDATE Township set HeaderCode = '1416' where TownshipName = 'Sacapulas'
UPDATE Township set HeaderCode = '1417' where TownshipName = 'San Bartolome Jocotenango'
UPDATE Township set HeaderCode = '1418' where TownshipName = 'Canilla'
UPDATE Township set HeaderCode = '1419' where TownshipName = 'Chicaman'
UPDATE Township set HeaderCode = '1420' where TownshipName = 'Ixcan'
UPDATE Township set HeaderCode = '1421' where TownshipName = 'Pachalum'
UPDATE Township set HeaderCode = '1501' where TownshipName = 'Salama'
UPDATE Township set HeaderCode = '1502' where TownshipName = 'San Miguel Chicaj'
UPDATE Township set HeaderCode = '1503' where TownshipName = 'Rabinal'
UPDATE Township set HeaderCode = '1504' where TownshipName = 'Cubulco'
UPDATE Township set HeaderCode = '1505' where TownshipName = 'Granados'
UPDATE Township set HeaderCode = '1506' where TownshipName = 'Santa Cruz El Chol'
UPDATE Township set HeaderCode = '1507' where TownshipName = 'San Jeronimo'
UPDATE Township set HeaderCode = '1508' where TownshipName = 'Purulha'
UPDATE Township set HeaderCode = '1601' where TownshipName = 'Coban'
UPDATE Township set HeaderCode = '1602' where TownshipName = 'Santa Cruz Verapaz'
UPDATE Township set HeaderCode = '1603' where TownshipName = 'San Cristobal Verapaz'
UPDATE Township set HeaderCode = '1604' where TownshipName = 'Tactic'
UPDATE Township set HeaderCode = '1605' where TownshipName = 'Tamahu'
UPDATE Township set HeaderCode = '1606' where TownshipName = 'Tucuru'
UPDATE Township set HeaderCode = '1607' where TownshipName = 'Panzos'
UPDATE Township set HeaderCode = '1608' where TownshipName = 'Senahu'
UPDATE Township set HeaderCode = '1609' where TownshipName = 'San Pedro Carcha'
UPDATE Township set HeaderCode = '1610' where TownshipName = 'San Juan Chamelco'
UPDATE Township set HeaderCode = '1611' where TownshipName = 'Lanquin'
UPDATE Township set HeaderCode = '1612' where TownshipName = 'Santa Maria Cahabon'
UPDATE Township set HeaderCode = '1613' where TownshipName = 'Chisec'
UPDATE Township set HeaderCode = '1614' where TownshipName = 'Chahal'
UPDATE Township set HeaderCode = '1615' where TownshipName = 'Fray Bartolome de las Casas'
UPDATE Township set HeaderCode = '1616' where TownshipName = 'Santa Catalina la Tinta'
UPDATE Township set HeaderCode = '1617' where TownshipName = 'Raxruha'
UPDATE Township set HeaderCode = '1701' where TownshipName = 'Flores'
UPDATE Township set HeaderCode = '1702' where TownshipName = 'San Jose'
UPDATE Township set HeaderCode = '1703' where TownshipName = 'San Benito'
UPDATE Township set HeaderCode = '1704' where TownshipName = 'San Andres'
UPDATE Township set HeaderCode = '1705' where TownshipName = 'La Libertad'
UPDATE Township set HeaderCode = '1706' where TownshipName = 'San Francisco'
UPDATE Township set HeaderCode = '1707' where TownshipName = 'Santa Ana'
UPDATE Township set HeaderCode = '1708' where TownshipName = 'Dolores'
UPDATE Township set HeaderCode = '1709' where TownshipName = 'San Luis'
UPDATE Township set HeaderCode = '1710' where TownshipName = 'Sayaxche'
UPDATE Township set HeaderCode = '1711' where TownshipName = 'Melchor de Mencos'
UPDATE Township set HeaderCode = '1712' where TownshipName = 'Poptun'
UPDATE Township set HeaderCode = '1713' where TownshipName = 'Las Cruces'
UPDATE Township set HeaderCode = '1714' where TownshipName = 'El Chal'
UPDATE Township set HeaderCode = '1801' where TownshipName = 'Puerto Barrios'
UPDATE Township set HeaderCode = '1802' where TownshipName = 'Livingston'
UPDATE Township set HeaderCode = '1803' where TownshipName = 'El Estor'
UPDATE Township set HeaderCode = '1804' where TownshipName = 'Morales'
UPDATE Township set HeaderCode = '1805' where TownshipName = 'Los Amates'
UPDATE Township set HeaderCode = '1901' where TownshipName = 'Zacapa'
UPDATE Township set HeaderCode = '1902' where TownshipName = 'Estanzuela'
UPDATE Township set HeaderCode = '1903' where TownshipName = 'Rio Hondo'
UPDATE Township set HeaderCode = '1904' where TownshipName = 'Gualan'
UPDATE Township set HeaderCode = '1905' where TownshipName = 'Teculutan'
UPDATE Township set HeaderCode = '1906' where TownshipName = 'Usumatlan'
UPDATE Township set HeaderCode = '1907' where TownshipName = 'Cabañas'
UPDATE Township set HeaderCode = '1908' where TownshipName = 'San Diego'
UPDATE Township set HeaderCode = '1909' where TownshipName = 'La Union'
UPDATE Township set HeaderCode = '1910' where TownshipName = 'Huite'
UPDATE Township set HeaderCode = '1911' where TownshipName = 'San Jorge'
UPDATE Township set HeaderCode = '2001' where TownshipName = 'Chiquimula'
UPDATE Township set HeaderCode = '2002' where TownshipName = 'San Jose La Arada'
UPDATE Township set HeaderCode = '2003' where TownshipName = 'San Juan Ermita'
UPDATE Township set HeaderCode = '2004' where TownshipName = 'Jocotan'
UPDATE Township set HeaderCode = '2005' where TownshipName = 'Camotan'
UPDATE Township set HeaderCode = '2006' where TownshipName = 'Olopa'
UPDATE Township set HeaderCode = '2007' where TownshipName = 'Esquipulas'
UPDATE Township set HeaderCode = '2008' where TownshipName = 'Concepcion Las Minas'
UPDATE Township set HeaderCode = '2009' where TownshipName = 'Quetzaltepeque'
UPDATE Township set HeaderCode = '2010' where TownshipName = 'San Jacinto'
UPDATE Township set HeaderCode = '2011' where TownshipName = 'Ipala'
UPDATE Township set HeaderCode = '2101' where TownshipName = 'Jalapa'
UPDATE Township set HeaderCode = '2102' where TownshipName = 'San Pedro Pinula'
UPDATE Township set HeaderCode = '2103' where TownshipName = 'San Luis Jilotepeque'
UPDATE Township set HeaderCode = '2104' where TownshipName = 'San Manuel Chaparron'
UPDATE Township set HeaderCode = '2105' where TownshipName = 'San Carlos Alzatate'
UPDATE Township set HeaderCode = '2106' where TownshipName = 'Monjas'
UPDATE Township set HeaderCode = '2107' where TownshipName = 'Mataquescuintla'
UPDATE Township set HeaderCode = '2201' where TownshipName = 'Jutiapa'
UPDATE Township set HeaderCode = '2202' where TownshipName = 'El Progreso'
UPDATE Township set HeaderCode = '2203' where TownshipName = 'Santa Catarina Mita'
UPDATE Township set HeaderCode = '2204' where TownshipName = 'Agua Blanca'
UPDATE Township set HeaderCode = '2205' where TownshipName = 'Asuncion Mita'
UPDATE Township set HeaderCode = '2206' where TownshipName = 'Yupiltepeque'
UPDATE Township set HeaderCode = '2207' where TownshipName = 'Atescatempa'
UPDATE Township set HeaderCode = '2208' where TownshipName = 'Jerez'
UPDATE Township set HeaderCode = '2209' where TownshipName = 'El Adelanto'
UPDATE Township set HeaderCode = '2210' where TownshipName = 'Zapotitlan'
UPDATE Township set HeaderCode = '2211' where TownshipName = 'Comapa'
UPDATE Township set HeaderCode = '2212' where TownshipName = 'Jalpatagua'
UPDATE Township set HeaderCode = '2213' where TownshipName = 'Conguaco'
UPDATE Township set HeaderCode = '2214' where TownshipName = 'Moyuta'
UPDATE Township set HeaderCode = '2215' where TownshipName = 'Pasaco'
UPDATE Township set HeaderCode = '2216' where TownshipName = 'San Jose Acatempa'
UPDATE Township set HeaderCode = '2217' where TownshipName = 'Quesada'

