UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3384
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3364
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3367
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3339
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3352
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3346
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3338
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3343
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3363
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3358
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3357
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3355
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3347
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3326
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3329
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3334
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3325
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3333
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3327
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3331
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3324
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3330
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3328
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3335
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3332
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3353
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3348
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3351
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3340
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3337
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3356
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3434
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3432
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3446
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3419
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3368
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3469
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3395
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3344
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3354
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3350
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3345
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3336
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3362
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3359
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3341
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3349
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3342
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3421
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3589
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3390
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3378
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3452
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3459
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3470
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3466
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3435
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3447
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3382
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3420
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3413
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3386
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3411
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3449
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3462
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3430
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3404
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3377
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3374
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3391
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3397
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3455
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3408
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3457
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3473
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3433
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3425
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3373
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3441
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3464
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3460
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3436
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3468
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3427
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3450
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3412
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3423
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3409
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3443
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3401
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3365
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3422
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3448
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3438
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3424
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3398
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3426
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3406
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3399
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3403
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3428
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3431
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3472
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3465
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3394
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3453
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3439
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3372
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3417
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3402
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3415
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3451
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3379
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3414
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3437
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3376
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3444
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3416
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3405
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3407
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3458
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3380
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3385
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3454
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3387
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3375
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3388
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3429
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3410
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3456
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3445
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3461
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3400
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3381
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3418
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3442
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3467
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3508
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3525
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3511
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3522
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3605
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3577
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3550
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3673
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3564
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3607
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3671
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3528
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3514
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3676
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3593
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3559
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3616
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3545
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3646
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3569
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3530
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3590
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3603
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3610
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3383
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3396
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3627
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3602
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3566
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3574
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3576
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3515
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3653
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3568
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3592
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3584
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3661
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3539
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3587
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3675
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3524
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3619
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3597
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3583
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3665
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3659
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3650
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3612
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3608
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3631
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3591
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3549
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3670
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3614
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3586
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3567
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3558
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3629
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3662
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3548
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3543
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3579
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3617
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3537
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3523
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3519
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3611
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3672
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3632
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3651
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3641
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3571
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3637
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3581
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3594
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3547
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3598
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3620
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3513
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3648
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3667
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3582
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3555
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3615
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3573
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3531
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3535
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3628
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3669
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3656
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3633
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3596
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3546
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3640
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3540
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3526
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3507
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3565
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3626
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3630
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3655
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3666
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3663
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3595
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3658
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3542
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3618
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3613
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3553
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3575
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3520
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3644
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3622
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3578
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3551
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3494
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3485
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3479
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3487
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3495
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3496
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3480
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3483
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3491
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3492
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3499
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3638
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3506
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3476
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3489
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3474
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3505
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3501
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3642
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3486
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3510
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3488
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3475
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3504
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3482
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3488
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3493
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3481
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3500
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3497
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3484
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3477
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3502
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3793
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3704
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3767
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3875
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3882
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3830
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3870
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3942
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3771
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3639
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3853
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3900
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3761
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3751
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3871
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3874
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3918
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3792
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3798
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3790
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3639
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3836
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3580
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3786
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3896
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3746
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3440
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3817
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3821
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3776
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3804
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3780
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3813
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3702
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3839
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3699
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3827
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3674
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3831
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3854
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3864
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3748
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3777
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3799
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3723
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3868
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3859
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3846
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3895
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3789
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3886
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3931
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3710
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3765
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3785
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3840
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3844
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3741
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3782
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3924
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3706
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3815
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3709
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3752
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3917
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3779
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3703
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3728
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3732
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3784
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3925
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3820
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3902
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3823
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3927
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3708
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3733
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3737
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3888
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3750
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3822
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3819
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3760
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3738
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3755
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3889
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3729
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3916
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3944
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3922
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3878
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3740
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3929
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3873
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3866
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3744
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3872
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3800
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3814
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3797
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3772
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3943
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3832
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3901
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3838
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3769
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3647
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3532
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3527
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3892
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3787
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3747
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3512
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3541
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3588
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3764
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3754
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3700
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3938
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3906
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3392
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3940
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3736
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3570
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3560
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3802
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3762
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3937
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3722
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3826
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3891
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3899
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3907
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3885
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3717
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3698
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3726
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3833
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3774
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3806
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3852
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3915
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3880
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3904
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3909
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3756
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3652
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3739
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3847
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3623
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3911
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3919
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3730
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3908
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3850
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3883
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3657
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3556
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3649
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3734
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3781
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3711
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3856
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3825
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3745
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3516
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3716
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3837
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3810
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3812
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3783
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3757
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3809
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3773
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3763
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3926
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3719
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3858
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3939
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3770
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3913
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3805
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3794
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3869
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3721
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3855
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3742
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3714
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3818
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3894
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3930
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3905
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3845
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3807
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3791
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3914
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3862
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3841
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3877
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3860
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3749
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3775
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3893
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3881
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3707
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3712
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3720
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3589
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3861
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3727
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3471
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3725
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3601
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3572
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3718
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3758
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3554
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3557
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3843
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3808
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3795
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3851
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3811
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3759
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3941
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3829
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3788
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3828
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3816
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3606
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3518
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3842
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3867
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3832
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3884
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3503
--UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4013
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4461
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4121
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4490
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4470
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3961
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3634
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3713
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3552
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3552
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3803
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3803
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3545
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3545
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3634
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3701
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3731
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3517
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3517
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3536
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3533
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3920
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3563
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3534
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3664
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3766
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3923
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3796
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3389
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3824
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3724
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3609
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3604
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3857
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3635
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4147
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4148
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4167
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3585
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3625
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3529
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3636
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3910
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3935
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3898
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3778
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3538
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3599
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3753
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3561
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3897
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3848
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3834
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3561
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3879
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3903
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3865
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3849
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3835
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3912
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3600
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3677
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4453
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4124
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4444
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4445
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3693
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3678
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3695
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3679
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3692
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3681
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3688
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3696
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4097
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3687
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3682
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3490
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3697
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3680
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4051
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4047
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4063
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4072
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4068
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4053
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4054
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4070
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4041
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4060
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4049
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4073
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4069
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4059
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4042
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4071
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4058
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3691
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4065
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4061
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3643
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4040
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4056
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4048
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4062
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4045
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4039
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4039
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4067
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4055
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4078
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4451
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4088
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4450
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4454
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4084
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4075
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4455
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4449
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4086
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4087
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4082
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4446
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4452
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4447
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4085
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4076
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4074
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4077
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4079
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3957
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3962
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4001
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3968
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3960
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3966
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3978
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4003
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4005
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3984
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3975
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3964
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3963
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3976
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3983
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3987
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3964
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3985
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 3982
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4486
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4462
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4012
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4028
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4009
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4027
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4022
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4038
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4052
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4221
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4030
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4025
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4456
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4023
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4457
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4019
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4029
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4016
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4011
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4017
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4036
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4020
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4026
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4032
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4007
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4034
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4015
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4035
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4031
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4010
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4459
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4037
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4018
UPDATE [DeliveryBackOffice].[dbo].[DeliveryOrder] SET StatusOrderId = 5 WHERE Guide_Serie = 'FD' AND Guide_Number = 4458