UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9901
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9839
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10390
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9874
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9951
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9878
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10366
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9213
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10397
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10396
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9919
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9903
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8798
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9844
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8787
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8500
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8964
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8931
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9849
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8939
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9249
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9029
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8894
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9049
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8874
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8975
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8346
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8317
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9058
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8788
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9017
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9215
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8980
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8983
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9018
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9263
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9240
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8973
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8871
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8401
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8933
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8363
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8510
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8924
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8335
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9066
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8956
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8863
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8784
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8991
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8991
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9246
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8914
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9274
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9077
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9180
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9103
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9095
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9095
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9956
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8867
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9875
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9871
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9908
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9891
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9133
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10388
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6090
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10376
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10381
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10395
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9934
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9930
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9879
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10387
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 10378
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9881
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9008
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8932
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9241
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9025
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8959
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8981
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9279
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8777
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9876
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9390
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9057
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8785
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8764
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8911
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9069
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8773
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9459
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9475
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9454
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9941
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8774
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8792
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8781
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8891
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9211
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9012
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8920
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9242
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9906
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8930
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9045
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8982
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9062
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9208
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7991
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9225
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9909
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8968
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8904
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8496
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8437
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8491
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8023
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7972
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8018
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8881
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9123
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8013
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8466
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8448
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8536
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9167
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8108
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8061
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9178
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8767
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9126
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9189
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9090
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 9099
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8372
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8361
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8343
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8329
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8342
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8307
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8242
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8635
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8643
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8304
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8302
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8699
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8294
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8696
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8646
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8698
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8688
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8370
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8650
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8700
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8410
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8648
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8695
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8259
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8671
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8345
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8367
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8390
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8258
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8256
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8397
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8731
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8835
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8838
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8831
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8839
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8829
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8810
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8845
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8812
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8851
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8809
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8848
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8818
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8534
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8856
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8518
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8760
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8498
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8545
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8490
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8540
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8516
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8497
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8507
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8512
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8524
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8544
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8493
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8519
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8487
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8492
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8462
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8451
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8506
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8549
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8532
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8418
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8459
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8414
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8251
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8311
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8297
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8303
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8274
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8322
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7172
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7252
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7224
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7170
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7175
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7078
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7221
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7279
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7290
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7220
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7289
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8156
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7263
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6958
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6165
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6239
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6250
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6905
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6929
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7828
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6834
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7206
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7223
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7205
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7287
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7207
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7256
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7193
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 1223
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 2523
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 2900
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 2101
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 1100
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 1923
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 3001
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 2001
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 2002
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 1524
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 3201
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 1424
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 2601
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8514
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8494
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8830
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8546
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8485
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8613
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8525
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8021
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8539
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8841
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8824
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7982
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6643
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6136
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6543
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7818
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7096
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7820
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6108
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7008
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7744
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6898
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7549
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7875
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5368
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 3992
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 4004
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 4442
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 4879
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5841
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6189
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6245
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6368
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6120
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6748
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6268
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6855
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6866
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6802
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 3686
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6794
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7772
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6710
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6986
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7943
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5604
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7505
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6828
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7743
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 4822
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7568
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5552
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5795
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5890
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5743
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 4614
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 3996
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6706
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6791
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6933
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7542
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 3934
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6380
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6342
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7960
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7117
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8020
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7533
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8002
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8024
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6869
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6539
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6132
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6446
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7041
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8027
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6267
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6163
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6549
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7124
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5884
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6315
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7753
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7976
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5254
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6511
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6987
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8010
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7495
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 5068
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6175
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6785
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6778
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7570
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6859
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 6413
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 8316
UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 1 WHERE Guide_Number = 7823

UPDATE DeliveryBackOffice.dbo.DeliveryOrder SET Package_Type = 2 WHERE Package_Type IS NULL

--select count(guide_number) from DeliveryBackOffice.dbo.DeliveryOrder
--select count(guide_number) from DeliveryBackOffice.dbo.DeliveryOrder where Package_Type = 2