INSERT INTO RolByModuleBySystem VALUES (4,1,1,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)
INSERT INTO RolByModuleBySystem VALUES (4,1,2,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)
INSERT INTO RolByModuleBySystem VALUES (4,1,4,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)
INSERT INTO RolByModuleBySystem VALUES (4,1,5,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)
INSERT INTO RolByModuleBySystem VALUES (4,1,6,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)
INSERT INTO RolByModuleBySystem VALUES (4,1,7,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)
INSERT INTO RolByModuleBySystem VALUES (4,1,8,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)
INSERT INTO RolByModuleBySystem VALUES (4,1,10,1,'SYS-MAJIMENEZ',GETDATE(),NULL,NULL)


