USE [DeliveryBackOffice]
GO

INSERT INTO [dbo].[ArticleByCustomer]
           ([AbcIdArticle]
           ,[AbcIdCustomer]
           ,[AbcRowStatus]
           ,[AbcTokenCreated]
           ,[AbcDateCreated]
           ,[AbcTokenUpdated]
           ,[AbcDateUpdated]
           ,[Code]
           ,[PriceDefault]
           ,[Height]
           ,[Width]
           ,[Length]
           ,[MassWeight]
           ,[VolumetricWeight]
           ,[ShowDefault])
     VALUES((SELECT ArtId FROM CatArticle WHERE ArtName = 'Alacena Doble Puertas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP001',185,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Amueblado Comedor 4 Personas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP002',414,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Amueblado De 4 Pax'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP003',306,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Amueblado De 6 Pax'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP004',373,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Amueblado De Sala'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP005',306,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Armario'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP006',87,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Bicicleta Grande'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP007',67,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Bicicleta Pequeña'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP008',29,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Butaca'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP009',98,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cabecera Con Mesa De Noche'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP010',74,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cabecera Plana Matrimonial'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP011',110,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Caja De Aire Acondicionado'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP012',167,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cajas De Vehiculos'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP013',145,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cama imperial/unipersonal'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP014',158,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cama King'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP015',297,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cama matrimonial'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP016',221,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cama Queen'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP017',245,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cama Semi-Matrimonial'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP018',193,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Camaras y Enfriadores y Freezer'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP019',278,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Camilla'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP020',268,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Capos'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP021',145,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Centro De Entretenimiento'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP022',167,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Chapeadora'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP023',98,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Compresores 50 Lts'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP024',103,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Congelador De 8 A 15 Pies'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP025',221,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Congelador Mediano'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP026',183,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Congelador Pequeño'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP027',154,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cuna Con Gavetas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP028',124,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Cunas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP029',124,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Escaleras Menos De 5Mts'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP030',71,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Escritorios Desarmados'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP031',154,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Escritorios Gerenciales'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP032',198,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Estufas Grandes'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP033',191,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Estufas Industriales'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP034',274,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Fotocopiadoras Grandes'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP035',167,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Fotocopiadoras Medianas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP036',132,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Gavetero'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP037',167,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Horno Microhonda'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP038',48,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Jacuzzi, Tinas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP039',332,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Lavadoras'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP040',114,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Lavadora-Secadora (Combo)'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP041',126,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Litera Imperial 2 Piezas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP042',354,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Llantas de camión'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP043',145,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Llantas De Tractor'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP044',263,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Loderas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP045',91,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Maquina De Coser'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP046',54,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Mesas De Futillo'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP047',212,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Mostradores (Vidrio,Madera)'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP048',221,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Motocicletas (4 Llantas)'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP049',354,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Motocicletas 2 Ruedas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP050',238,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Motores De Vehiculos Livianos'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP051',198,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Oasis'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP052',71,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Plantas Generadoras'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP053',165,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Puertas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP054',116,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Recamara 5 Pz'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP055',324,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Recamara 6 Piezas'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP056',292,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Recamara 8 Pz'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP057',221,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Refrigeradoras 14 - 17'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP058',225,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Refrigeradoras 21 En Adelante'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP059',252,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Refrigeradoras 9 - 12'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP060',198,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Roperos'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP061',221,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Rotulos'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP062',177,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Juego de sala'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP063',333,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Servicios Sanitarios'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP064',150,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Silla Ruedas (Caja)'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP065',60,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Silla Secretarial Basica C/ Negro 1576-B'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP066',51,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Sillon Extensible, Reclinable y Butaca M'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP067',110,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Trinchante'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP068',221,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'TV Led 24'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP069',52,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'TV Led 50'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP070',141,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'TVS Plasma 32'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP071',73,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'TVS Plasma 60'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP072',204,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Ventilador D/Pedestal Fs1810 Parker Metr'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP073',40,30,30,30,NULL,NULL,'FALSE'),
      ((SELECT ArtId FROM CatArticle WHERE ArtName = 'Wind Shield'),NULL,'TRUE','SYS-OMORALES',GETDATE(),NULL,NULL,'EXP074',98,30,30,30,NULL,NULL,'FALSE')
