USE [DeliveryBackOffice]
GO

INSERT INTO [dbo].[CatMoney] ([CurrencyId],[Type],[Value],[RowStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
     VALUES (1,'BILLETE',200.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'BILLETE',100.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'BILLETE',50.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'BILLETE',20.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'BILLETE',10.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'BILLETE',5.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'BILLETE',1.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'BILLETE',0.50,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'MONEDA',1.00,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'MONEDA',0.50,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'MONEDA',0.25,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'MONEDA',0.10,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'MONEDA',0.05,1,'OMORALES', GETDATE(), NULL, NULL),
			(1,'MONEDA',0.01,1,'OMORALES', GETDATE(), NULL, NULL)
GO