INSERT INTO CatSalesChannel  VALUES ('Express Center','SYS-BHERRERA',GETDATE(),NULL,NULL,1)
INSERT INTO CatSalesChannel  VALUES ('Autoventa','SYS-BHERRERA',GETDATE(),NULL,NULL,1)
INSERT INTO CatSalesChannel  VALUES ('Portal Web','SYS-BHERRERA',GETDATE(),NULL,NULL,1)
INSERT INTO CatSalesChannel  VALUES ('Telemarketing','SYS-BHERRERA',GETDATE(),NULL,NULL,1)
INSERT INTO CatSalesChannel  VALUES ('Corporativo','SYS-BHERRERA',GETDATE(),NULL,NULL,1)
INSERT INTO CatSalesChannel  VALUES ('Gobierno','SYS-BHERRERA',GETDATE(),NULL,NULL,1)
INSERT INTO CatSalesChannel  VALUES ('Concesionario','SYS-BHERRERA',GETDATE(),NULL,NULL,1)
SELECT * FROM DeliveryBackOffice.dbo.CatSalesChannel
