/*ACTUALIZAR CORREOS DE HUBs*/
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,veronica.ayala@forzadelivery.com,emilio.alegria@forzadelivery.com,nelson.recinos@forzadelivery.com,feliciano.solis@forzadelivery.com,eddy.solorzano@forzadelivery.com,omar.orellana@forzadelivery.com,alvaro.ruano@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'GTM')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,veronica.ayala@forzadelivery.com,emilio.alegria@forzadelivery.com,nelson.recinos@forzadelivery.com,feliciano.solis@forzadelivery.com,eddy.solorzano@forzadelivery.com,omar.orellana@forzadelivery.com,alvaro.ruano@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'GUA')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,hub.chimaltenango@forzadelivery.com,veronica.ayala@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'CHI')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,sede.escuintla@forzadelivery.com,victor.marinelli@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'ESC')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,sede.mazatenango@forzadelivery.com,victor.marinelli@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'MAZ')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,sede.quetzaltenango@forzadelivery.com,victor.marinelli@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'QUE')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,hub.sanmarcos@forzadelivery.com,victor.marinelli@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'SMA')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,eduardo.lopez@forzadelivery.com,victor.marinelli@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'HUE')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,hub.solola@forzadelivery.com,victor.marinelli@forzadelivery.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'SOL')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,hub.barberena@forzadelivery.com,agencia.teculutan@forzalatam.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'BAR')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,supervisortrafico.teculutan@forzadelivery.com,agencia.teculutan@forzalatam.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'TEC')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,supervisortrafico.coban@forzadelivery.com,agencia.teculutan@forzalatam.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'COB')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,daniel.cordova@forzadelivery.com,agencia.teculutan@forzalatam.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'MOR')
UPDATE  CatLinehaul SET Emails = 'bidcar.herrera@forzalatam.com,carlos.valdes@forzalatam.com,jose.zamudio@forzalatam.com,agencia.peten@forzalatam.com,jairo.lemus@forzadelivery.com,agencia.teculutan@forzalatam.com' WHERE IdHubDestination = (select IdHubLogistic from HubLogistics where HubAbbreviation = 'FRS')


