USE [DeliveryBackOffice]
GO

SELECT * FROM [dbo].[FlateRate]
--1 A 10 LBS
INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (1
           ,6
           ,'FALSE'
           ,23.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)
GO


INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (1
           ,7
           ,'FALSE'
           ,28.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (1
           ,8
           ,'FALSE'
           ,33.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (1
           ,9
           ,'FALSE'
           ,38.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


		   INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (1
           ,10
           ,'FALSE'
           ,42.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


--11 A 20 LBS

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (2
           ,6
           ,'FALSE'
           ,25.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)
GO


INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (2
           ,7
           ,'FALSE'
           ,30.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (2
           ,8
           ,'FALSE'
           ,35.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (2
           ,9
           ,'FALSE'
           ,40.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


		   INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (2
           ,10
           ,'FALSE'
           ,44.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

--21 A 30 LBS

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (3
           ,6
           ,'FALSE'
           ,27.50
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)
																																																																																																																																																																																																																																			A
INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (3
           ,7
           ,'FALSE'
           ,33.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (3
           ,8
           ,'FALSE'
           ,39.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (3
           ,9
           ,'FALSE'
           ,45.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


		   INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (3
           ,10
           ,'FALSE'
           ,50.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


--31 A 40 LBS

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (4
           ,6
           ,'FALSE'
           ,30.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)
GO


INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (4
           ,7
           ,'FALSE'
           ,37.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (4
           ,8
           ,'FALSE'
           ,44.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (4
           ,9
           ,'FALSE'
           ,51.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


		   INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (4
           ,10
           ,'FALSE'
           ,56.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

--DE 41 A 50
INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (5
           ,6
           ,'FALSE'
           ,33.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)
GO


INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (5
           ,7
           ,'FALSE'
           ,40.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (5
           ,8
           ,'FALSE'
           ,47.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (5
           ,9
           ,'FALSE'
           ,54.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


		   INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (5
           ,10
           ,'FALSE'
           ,60.00
           ,NULL
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

--51 EN ADELANTE
INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (6
           ,6
           ,'TRUE'
           ,33.00
           ,1.00
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)
GO


INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (6
           ,7
           ,'TRUE'
           ,40.00
           ,1.00
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (6
           ,8
           ,'TRUE'
           ,47.00
           ,1.00
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)

INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (6
           ,9
           ,'TRUE'
           ,54.00
           ,1.00
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)


		   INSERT INTO [dbo].[FlateRate]
           ([IdDimensional]
           ,[IdSegmentArea]
           ,[ExceededRate]
           ,[PriceRate]
           ,[AdicionalCostPerUnit]
           ,[IdCurrency]
           ,[IdCountry]
           ,[FlatRateStatus]
           ,[IdRateCategory]
           ,[DateFromValid]
           ,[DateExpired]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated])
     VALUES
           (6
           ,10
           ,'TRUE'
           ,60.00
           ,1.0
           ,1
           ,'GT'
           ,'TRUE'
           ,2
           ,'2020-10-15'
           ,'2025-10-15'
           ,'SYS-ERAMIREZ'
           ,GETDATE()
           ,NULL
           ,NULL)
