 

insert into [DeliveryBackOffice].[dbo].[RateByHub]
SELECT
      [RbhIdRate]
      ,[RbhIdHubSource]
      ,22
      ,[RbhIdTypeService]
      ,[RbhRate]
      ,[RbhFragileRate]
      ,[RbhInsuranceRate]
      ,[RbhCollectedRate]
      ,[RbhWeightAdditionalRate]
      ,[RbhWeightLimit]
      ,[RbhWeightMeasure]
      ,[RbhDeliveryAttempts]
      ,[RbhCurrency]
      ,[RbhRowStatus]
      ,[RbhTokenCreated]
      ,[RbhDateCreated]
      ,[RbhTokenUpdated]
      ,[RvDateUpdated]
  FROM [DeliveryBackOffice].[dbo].[RateByHub] where RbhIdHubDestiny = 1

  insert into [DeliveryBackOffice].[dbo].[RateByHub]
SELECT
      [RbhIdRate]
      ,[RbhIdHubSource]
      ,22
      ,[RbhIdTypeService]
      ,[RbhRate]
      ,[RbhFragileRate]
      ,[RbhInsuranceRate]
      ,[RbhCollectedRate]
      ,[RbhWeightAdditionalRate]
      ,[RbhWeightLimit]
      ,[RbhWeightMeasure]
      ,[RbhDeliveryAttempts]
      ,[RbhCurrency]
      ,[RbhRowStatus]
      ,[RbhTokenCreated]
      ,[RbhDateCreated]
      ,[RbhTokenUpdated]
      ,[RvDateUpdated]
  FROM [DeliveryBackOffice].[dbo].[RateByHub] where RbhIdHubSource = 1
 
 
 
 update RateByHub set RbhRate =28 where RbhIdHubSource = 2 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 16 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 8 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 4 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 5 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 1 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 22 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 17 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 6 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 18 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 19 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 13 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 20 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =2; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 21 and RbhIdHubDestiny =2; 
 update RateByHub set RbhRate =35 where RbhIdHubSource = 2 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 16 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 8 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 4 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 5 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 1 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 22 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 17 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 6 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 18 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 19 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 13 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 20 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =16; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 21 and RbhIdHubDestiny =16; 
 update RateByHub set RbhRate =35 where RbhIdHubSource = 2 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 16 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 8 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 4 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 5 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 1 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 22 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 17 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 6 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 18 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 19 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 13 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 20 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =8; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 21 and RbhIdHubDestiny =8; 
 update RateByHub set RbhRate =35 where RbhIdHubSource = 2 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 16 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 8 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 4 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 5 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 1 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 22 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 17 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 6 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 18 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 19 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 13 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 20 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =4; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 21 and RbhIdHubDestiny =4; 
 update RateByHub set RbhRate =48 where RbhIdHubSource = 2 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 16 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 8 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 4 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 5 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 1 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 22 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 17 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 18 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 7 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 19 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 13 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 20 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =5; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 21 and RbhIdHubDestiny =5; 
 update RateByHub set RbhRate =41 where RbhIdHubSource = 2 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 16 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 8 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 4 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 5 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 1 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 22 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 17 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 18 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 7 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 19 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 3 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 13 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 20 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 10 and RbhIdHubDestiny =1; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 21 and RbhIdHubDestiny =1; 
 update RateByHub set RbhRate =41 where RbhIdHubSource = 2 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 16 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 8 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 4 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 5 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 1 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 22 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 17 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 18 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 7 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 19 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 13 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 20 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =22; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 21 and RbhIdHubDestiny =22; 
 update RateByHub set RbhRate =48 where RbhIdHubSource = 2 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 16 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 8 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 4 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 5 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 1 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 22 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 17 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 18 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 7 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 19 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 13 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 20 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =17; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 21 and RbhIdHubDestiny =17; 
 update RateByHub set RbhRate =52 where RbhIdHubSource = 2 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 16 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 8 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 4 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 5 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 1 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 22 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 17 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 6 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 18 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 7 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 19 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 13 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 20 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 10 and RbhIdHubDestiny =6; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 21 and RbhIdHubDestiny =6; 
 update RateByHub set RbhRate =52 where RbhIdHubSource = 2 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 16 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 8 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 4 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 5 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 1 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 22 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 17 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 6 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 18 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 7 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 19 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 13 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 20 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 10 and RbhIdHubDestiny =18; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 21 and RbhIdHubDestiny =18; 
 update RateByHub set RbhRate =52 where RbhIdHubSource = 2 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 16 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 8 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 4 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 5 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 1 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 22 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 17 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 18 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 7 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 19 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 13 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 20 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =7; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 21 and RbhIdHubDestiny =7; 
 update RateByHub set RbhRate =52 where RbhIdHubSource = 2 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 16 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 8 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 4 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 5 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 1 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 22 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 17 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 18 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 7 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 19 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 3 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 13 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 20 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 10 and RbhIdHubDestiny =19; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 21 and RbhIdHubDestiny =19; 
 update RateByHub set RbhRate =52 where RbhIdHubSource = 2 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 16 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 8 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 4 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 5 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 1 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 22 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 17 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 6 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 18 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 19 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 3 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 13 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 20 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 10 and RbhIdHubDestiny =3; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 21 and RbhIdHubDestiny =3; 
 update RateByHub set RbhRate =41 where RbhIdHubSource = 2 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 16 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 8 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 4 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 5 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 1 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 22 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 17 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 18 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 7 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 19 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 13 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 20 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =13; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 21 and RbhIdHubDestiny =13; 
 update RateByHub set RbhRate =41 where RbhIdHubSource = 2 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 16 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 8 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 4 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 5 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 1 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 22 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 17 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 6 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 18 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 19 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 13 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 20 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =20; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 21 and RbhIdHubDestiny =20; 
 update RateByHub set RbhRate =52 where RbhIdHubSource = 2 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 16 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 8 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 4 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 5 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 1 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 22 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 17 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 6 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 18 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 19 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 3 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 13 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 20 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 10 and RbhIdHubDestiny =10; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 21 and RbhIdHubDestiny =10; 
 update RateByHub set RbhRate =35 where RbhIdHubSource = 2 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 16 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 8 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =35 where RbhIdHubSource = 4 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 5 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =41 where RbhIdHubSource = 1 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 22 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 17 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 6 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 18 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 7 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 19 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 3 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 13 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =48 where RbhIdHubSource = 20 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =52 where RbhIdHubSource = 10 and RbhIdHubDestiny =21; 	 update RateByHub set RbhRate =28 where RbhIdHubSource = 21 and RbhIdHubDestiny =21; 
