  insert into ctgTypeOfInOutOfMoney (tio_pk_id, tio_pk_name, tio_tokenCreated, tio_dateCreated)
  values (1, 'pago en efectivo', 'Icoti', GETDATE())
    insert into ctgTypeOfInOutOfMoney (tio_pk_id, tio_pk_name, tio_tokenCreated, tio_dateCreated)
  values (2, 'pago con tarjeta', 'Icoti', GETDATE())
    insert into ctgTypeOfInOutOfMoney (tio_pk_id, tio_pk_name, tio_tokenCreated, tio_dateCreated)
  values (3, 'pago con cupon', 'SYS-SYSTEM', GETDATE())
    insert into ctgTypeOfInOutOfMoney (tio_pk_id, tio_pk_name, tio_tokenCreated, tio_dateCreated)
  values (4, 'pago con wallet', 'SYS-SYSTEM', GETDATE())
    insert into ctgTypeOfInOutOfMoney (tio_pk_id, tio_pk_name, tio_tokenCreated, tio_dateCreated)
  values (5, 'credito', 'SYS-SYSTEM', GETDATE())
    insert into ctgTypeOfInOutOfMoney (tio_pk_id, tio_pk_name, tio_tokenCreated, tio_dateCreated)
  values (6, 'Datafono', 'SYS-CAQUINO', GETDATE())