USE [DeliveryBackOffice]
GO

INSERT INTO [dbo].[RateCategory]([TitleName],[RateCatDescription],[RateCatStatus],[TokenCreated],[DateCreated],[TokenUpdated],[DateUpdated])
SELECT 'STANDAR DELIVERY', 'TARIFA ESTANDAR', 'TRUE', 'SYS-ERAMIREZ', GETDATE(), NULL, NULL
UNION
SELECT 'EXPRESS DELIVERY', 'TARIFA EXPRESS', 'TRUE', 'SYS-ERAMIREZ', GETDATE(), NULL, NULL
UNION
SELECT 'NEXT DAY DELIVERY', 'TARIFA NEXT DAY', 'TRUE', 'SYS-ERAMIREZ', GETDATE(), NULL, NULL


--SELECT  * FROM [dbo].[RateCategory]
