--cambio para controlar caracteres que pueden romper la estructuras del json
--al reimprimir una guia
INSERT INTO tb_StringEncoding VALUES(CHAR(1),'','json');--SOH(inicio encabezado)
INSERT INTO tb_StringEncoding VALUES(CHAR(2),'','json');--STX(inicio texto)
INSERT INTO tb_StringEncoding VALUES(CHAR(3),'','json');--ETX(fin de texto)
INSERT INTO tb_StringEncoding VALUES(CHAR(4),'','json');--EOT(fin transmisión)
INSERT INTO tb_StringEncoding VALUES(CHAR(5),'','json');--ENQ(consulta)
INSERT INTO tb_StringEncoding VALUES(CHAR(6),'','json');--ACK(reconocimiento)
INSERT INTO tb_StringEncoding VALUES(CHAR(7),'','json');--BEL(timbre)
INSERT INTO tb_StringEncoding VALUES(CHAR(8),'','json');--BS(retroceso)
INSERT INTO tb_StringEncoding VALUES(CHAR(9),'','json');--HT(tab horizontal)
INSERT INTO tb_StringEncoding VALUES(CHAR(10),'','json');--LF(nueva línea)
INSERT INTO tb_StringEncoding VALUES(CHAR(11),'','json');--VT(tab vertical)
INSERT INTO tb_StringEncoding VALUES(CHAR(12),'','json');--FF(nueva página)
INSERT INTO tb_StringEncoding VALUES(CHAR(13),'','json');--CR(retorno de carro)
INSERT INTO tb_StringEncoding VALUES(CHAR(14),'','json');--SO(desplaza afuera)
INSERT INTO tb_StringEncoding VALUES(CHAR(15),'','json');--SI(desplaza adentro)
INSERT INTO tb_StringEncoding VALUES(CHAR(16),'','json');--DLE(esc.vínculo datos)
INSERT INTO tb_StringEncoding VALUES(CHAR(17),'','json');--DC1(control disp. 1)
INSERT INTO tb_StringEncoding VALUES(CHAR(18),'','json');--DC2(control disp. 2)
INSERT INTO tb_StringEncoding VALUES(CHAR(19),'','json');--DC3(control disp. 3)
INSERT INTO tb_StringEncoding VALUES(CHAR(20),'','json');--DC4(control disp. 4)
INSERT INTO tb_StringEncoding VALUES(CHAR(21),'','json');--NAK(conf. negativa)
INSERT INTO tb_StringEncoding VALUES(CHAR(22),'','json');--SYN(inactividad sínc)
INSERT INTO tb_StringEncoding VALUES(CHAR(23),'','json');--ETB(fin bloque trans)
INSERT INTO tb_StringEncoding VALUES(CHAR(24),'','json');--CAN(cancelar)
INSERT INTO tb_StringEncoding VALUES(CHAR(25),'','json');--EM(fin del medio)
INSERT INTO tb_StringEncoding VALUES(CHAR(26),'','json');--SUB(sustitución)
INSERT INTO tb_StringEncoding VALUES(CHAR(27),'','json');--ESC(escape)
INSERT INTO tb_StringEncoding VALUES(CHAR(28),'','json');--FS(sep. archivos)
INSERT INTO tb_StringEncoding VALUES(CHAR(29),'','json');--GS(sep. grupos)
INSERT INTO tb_StringEncoding VALUES(CHAR(30),'','json');--RS(sep. registros)
INSERT INTO tb_StringEncoding VALUES(CHAR(31),'','json');--US(sep. unidades)
INSERT INTO tb_StringEncoding VALUES(CHAR(127),'','json');--DEL(suprimir)
