USE [DeliveryBackOffice]
GO

BEGIN TRAN

/****** Object:  Table [dbo].[BatchCOD]    Script Date: 25/06/2021 14:51:30 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[BatchCOD](
	[IdBatchCOD] [int] IDENTITY(1,1) NOT NULL,
	[BankId] [int] NOT NULL,
	[BatchNumber] [int] NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Date] [datetime] NOT NULL,
	[TotalAmountIncluded] [decimal](18, 2) NULL,
 CONSTRAINT [PK_BatchCOD_IdBatchCOD] PRIMARY KEY CLUSTERED 
(
	[IdBatchCOD] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [UK_BatchCOD_BankId_BatchNumber] UNIQUE NONCLUSTERED 
(
	[BankId] ASC,
	[BatchNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[BatchCOD] ADD  CONSTRAINT [DF_BatchCOD_Date]  DEFAULT (getdate()) FOR [Date]
GO

ALTER TABLE [dbo].[BatchCOD]  WITH CHECK ADD  CONSTRAINT [FK_BatchCOD_DeliveryBank] FOREIGN KEY([BankId])
REFERENCES [dbo].[DeliveryBank] ([Id_bank])
GO

ALTER TABLE [dbo].[BatchCOD] CHECK CONSTRAINT [FK_BatchCOD_DeliveryBank]
GO

--COMMIT


