USE [DeliveryBackOffice]
GO

/****** Object:  Index [IDX_DCBA_ID_DCBA_ID_ESTADO]    Script Date: 25/08/2021 18:42:50 ******/
CREATE NONCLUSTERED INDEX [IDX_DCBA_ID_DCBA_ID_ESTADO] ON [dbo].[DeliveryCustomerBankAccount]
(
	[DCBA_Id] ASC,
	[DCBA_Id_estado] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)
GO


