--FDD-519 RESTRICCION A ACCESO A SOCIOS DE NEGOCIO Y PUNTOS DE VISITA, POR MEDIO DEL IDSALEADVISOR
ALTER TABLE [DBO].[InternalUser]
	ADD SaleAdvisorID int,
	CONSTRAINT FK_InternalUser_SaleAdvisorID FOREIGN KEY (SaleAdvisorID) REFERENCES DBO.CatSaleAdvisor(IdSaleAdvisor)

--INDEX PARA VALIDAR QUE LOS DATOS NO SE REPITAN, TAMBIEN AYUDARA A LA BUSQUEDA DE DATOS
CREATE UNIQUE NONCLUSTERED INDEX [UK_InternalUser_SaleAdvisroID] ON [DBO].[InternalUser]
( SaleAdvisorID ) WHERE SaleAdvisorID IS NOT NULL    