/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RateCategory SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.SegmentArea SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.DimensionalParameter SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.FlateRate ADD CONSTRAINT
	FK_FlateRate_Dimensional FOREIGN KEY
	(
	IdDimensional
	) REFERENCES dbo.DimensionalParameter
	(
	IdDimensional
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.FlateRate ADD CONSTRAINT
	FK_FlateRate_SegmentArea FOREIGN KEY
	(
	IdSegmentArea
	) REFERENCES dbo.SegmentArea
	(
	IdSegmentArea
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.FlateRate ADD CONSTRAINT
	FK_FlateRate_RateCategory FOREIGN KEY
	(
	IdRateCategory
	) REFERENCES dbo.RateCategory
	(
	IdRateCategory
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.FlateRate SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
