/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Unit
	(
	IdUnit int NOT NULL IDENTITY (1, 1),
	UnitName nvarchar(50) NULL,
	Prefix nvarchar(5) NULL,
	TypeUnit nvarchar(10) NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Unit ADD CONSTRAINT
	PK_Unit PRIMARY KEY CLUSTERED 
	(
	IdUnit
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Unit SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
