--pendiente

INSERT INTO MarketplaceTagsByProduct (MarketplaceProductTagsId,RowStatus,TokenCreated,DateCreated, CatSubscriptionId, CatMembershipId, Position)
VALUES(4,1,'SYS-BHERRERA',GETDATE(),13,NULL,3),	
	  (5,1,'SYS-BHERRERA',GETDATE(),14,NULL,6),
	  (5,1,'SYS-BHERRERA',GETDATE(),17,NULL,2),
	  (7,1,'SYS-BHERRERA',GETDATE(),NULL,3,3),
	  (7,1,'SYS-BHERRERA',GETDATE(),13,NULL,3),
	  (7,1,'SYS-BHERRERA',GETDATE(),14,NULL,6),
	  (7,1,'SYS-BHERRERA',GETDATE(),15,NULL,4),
	  (6,1,'SYS-BHERRERA',GETDATE(),18,NULL,5),
	  (7,1,'SYS-BHERRERA',GETDATE(),16,NULL,6),
      (7,1,'SYS-BHERRERA',GETDATE(),17,NULL,2),
	  (7,1,'SYS-BHERRERA',GETDATE(),18,NULL,5)