
INSERT INTO CatMembership (MembershipName,
						   MembershipDescription, 
						   MembershipCost, 
						   MembershipFixedValue,
						   MembershipMaxServiceFixedValue,
						   MembershipValidity,
						   RowStatus,
						   TokenCreated,
						   DateCreated,
						   Icon,
						   NextSalesPackageBanner,
						   CatProductCategoryId,
						   IdCountry,
						   IdCatCurrencyCOD)

	  VALUES('Club Forza',
			 'Es una membresía para emprendedores y mi Pymes que te da beneficios, acceso exclusivo a promociones y descuentos, recolecciones sin costo y con frecuencia programada de visita.',
			 63.87,
			 0,
			 0,
			 12,
			 1,
			 'SYS-ARUIZ',
			 GETDATE(),
			 'hwa-membershipIcon',
			 'bannerSubsPlan1.png',
			 8,
			 'HN',
			 4)