CREATE TABLE [dbo].[ConfirmedAddress] (
    [IdConfirmedAddress]     BIGINT         IDENTITY (1, 1) NOT NULL,
    [AccountId]              BIGINT         NOT NULL,
    [NirPhone]               NVARCHAR (4)   NOT NULL,
    [Phone]                  NVARCHAR (15)  NOT NULL,
    [NameAddress]            VARCHAR (100)  NOT NULL,
    [CodeOfReference]        INT            NULL,
    [DeliveryOptionId]       BIGINT         NULL,
    [ProvinceId]             INT            NOT NULL,
    [TownshipId]             INT            NOT NULL,
    [Zone]                   SMALLINT       NULL,
    [Neighborhood]           VARCHAR (50)   NULL,
    [CityPlaceId]            INT            NOT NULL,
    [Address]                NVARCHAR (600) NOT NULL,
    [AdditionalInstructions] VARCHAR (250)  NULL,
    [Latitude]               VARCHAR (20)   NULL,
    [Longitude]              VARCHAR (20)   NULL,
    [CatModuleId]            INT            NULL,
    [StatusAddressId]        INT            NOT NULL,
    [RowStatus]              BIT            NOT NULL,
    [DateCreated]            DATETIME       NOT NULL,
    [TokenCreated]           VARCHAR (50)   NOT NULL,
    [DateUpdate]             DATETIME       NULL,
    [TokenUpdate]            VARCHAR (50)   NULL,
    CONSTRAINT [PK_ConfirmedAddress] PRIMARY KEY CLUSTERED ([IdConfirmedAddress] ASC)
);

