/*********************************************

NOTA:
	ESTE SCRIPT NO DEBE EJECUTARSE, PUES YA HA SIDO 
	EJECUTADO EN AMBIENTE PRODUCTIVO. ESTA UNICAMENTE 
	COMO HISTORICO DE LOS CAMBIOS QUE SE HAN EJECUTADO
	EN PRODUCCION.

**********************************************/

INSERT INTO CatEconomicActivityBySV (CodeActivity, Description, RowStatus, TokenCreated, DateCreated, TokenUpdated, DateUpdated) VALUES
('01111', 'Cultivo de cereales excepto arroz y para forrajes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01112', 'Cultivo de legumbres ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01113', 'Cultivo de semillas oleaginosas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01114', 'Cultivo de plantas para la preparación de semillas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01119', 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01120', 'Cultivo de arroz ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01131', 'Cultivo de raíces y tubérculos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01132', 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01133', 'Cultivo hortícola de fruto ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01134', 'Cultivo de hortalizas de hoja y otras hortalizas ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01140', 'Cultivo de caña de azúcar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01150', 'Cultivo de tabaco ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01161', 'Cultivo de algodón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01162', 'Cultivo de fibras vegetales excepto algodón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01191', 'Cultivo de plantas no perennes para la producción de semillas y flores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01192', 'Cultivo de cereales y pastos para la alimentación animal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01199', 'Producción de cultivos no estacionales ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01220', 'Cultivo de frutas tropicales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01230', 'Cultivo de cítricos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01240', 'Cultivo de frutas de pepita y hueso ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01251', 'Cultivo de frutas ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01252', 'Cultivo de otros frutos y nueces de árboles y arbustos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01260', 'Cultivo de frutos oleaginosos', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01271', 'Cultivo de café ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01272', 'Cultivo de plantas para la elaboración de bebidas excepto café ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01281', 'Cultivo de especias y aromáticas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01282', 'Cultivo de plantas para la obtención de productos medicinales y farmacéuticos', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01291', 'Cultivo de árboles de hule (caucho) para la obtención de látex ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01292', 'Cultivo de plantas para la obtención de productos químicos y colorantes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01299', 'Producción de cultivos perennes ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01300', 'Propagación de plantas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01301', 'Cultivo de plantas y flores ornamentales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01410', 'Cría y engorde de ganado bovino ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01420', 'Cría de caballos y otros equinos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01440', 'Cría de ovejas y cabras ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01450', 'Cría de cerdos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01460', 'Cría de aves de corral y producción de huevos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01491', 'Cría de abejas apicultura para la obtención de miel y otros productos apícolas', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01492', 'Cría de conejos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01493', 'Cría de iguanas y garrobos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01494', 'Cría de mariposas y otros insectos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01499', 'Cría y obtención de productos animales n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01500', 'Cultivo de productos agrícolas en combinación con la cría de animales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01611', 'Servicios de maquinaria agrícola ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01612', 'Control de plagas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01613', 'Servicios de riego ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01614', 'Servicios de contratación de mano de obra para la agricultura ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01619', 'Servicios agrícolas ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01621', 'Actividades para mejorar la reproducción, el crecimiento y el rendimiento de los animales y sus productos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01622', 'Servicios de mano de obra pecuaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01629', 'Servicios pecuarios ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01631', 'Labores post cosecha de preparación de los productos agrícolas para su comercialización o para la industria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01632', 'Servicio de beneficio de café ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01633', 'Servicio de beneficiado de plantas textiles (incluye el beneficiado cuando este es realizado en la misma explotación agropecuaria) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01640', 'Tratamiento de semillas para la propagación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('01700', 'Caza ordinaria y mediante trampas, repoblación de animales de caza y servicios conexos', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('02100', 'Silvicultura y otras actividades forestales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('02200', 'Extracción de madera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('02300', 'Recolección de productos diferentes a la madera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('02400', 'Servicios de apoyo a la silvicultura ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('03110', 'Pesca marítima de altura y costera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('03120', 'Pesca de agua dulce ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('03210', 'Acuicultura marítima ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('03220', 'Acuicultura de agua dulce ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('03300', 'Servicios de apoyo a la pesca y acuicultura', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('05100', 'Extracción de hulla ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('05200', 'Extracción y aglomeración de lignito ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('06100', 'Extracción de petróleo crudo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('06200', 'Extracción de gas natural ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('07100', 'Extracción de minerales de hierro ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('07210', 'Extracción de minerales de uranio y torio ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('07290', 'Extracción de minerales metalíferos no ferrosos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('08100', 'Extracción de piedra, arena y arcilla ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('08910', 'Extracción de minerales para la fabricación de abonos y productos químicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('08920', 'Extracción y aglomeración de turba ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('08930', 'Extracción de sal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('08990', 'Explotación de otras minas y canteras ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('09100', 'Actividades de apoyo a la extracción de petróleo y gas natural ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('09900', 'Actividades de apoyo a la explotación de minas y canteras ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10101', 'Servicio de rastros y mataderos de bovinos y porcinos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10102', 'Matanza y procesamiento de bovinos y porcinos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10103', 'Matanza y procesamientos de aves de corral ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10104', 'Elaboración y conservación de embutidos y tripas naturales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10105', 'Servicios de conservación y empaque de carnes', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10106', 'Elaboración y conservación de grasas y aceites animales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10107', 'Servicios de molienda de carne ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10108', 'Elaboración de productos de carne ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10201', 'Procesamiento y conservación de pescado, crustáceos y moluscos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10209', 'Fabricación de productos de pescado ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10301', 'Elaboración de jugos de frutas y hortalizasv ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10302', 'Elaboración y envase de jaleas, mermeladas y frutas deshidratadas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10309', 'Elaboración de productos de frutas y hortalizas n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10401', 'Fabricación de aceites y grasas vegetales y animales comestibles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10402', 'Fabricación de aceites y grasas vegetales y animales no comestibles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10409', 'Servicio de maquilado de aceites ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10501', 'Fabricación de productos lácteos excepto sorbetes y quesos sustitutos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10502', 'Fabricación de sorbetes y helados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10503', 'Fabricación de quesos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10611', 'Molienda de cereales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10612', 'Elaboración de cereales para el desayuno y similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10613', 'Servicios de beneficiado de productos agrícolas ncp (excluye Beneficio de azúcar rama 1072 y beneficio de café rama 0163) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10621', 'Fabricación de almidón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10628', 'Servicio de molienda de maíz húmedo molino para nixtamal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10711', 'Elaboración de tortillas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10712', 'Fabricación de pan, galletas y barquillos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10713', 'Fabricación de repostería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10721', 'Ingenios azucareros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10722', 'Molienda de caña de azúcar para la elaboración de dulces ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10723', 'Elaboración de jarabes de azúcar y otros similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10724', 'Maquilado de azúcar de caña ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10730', 'Fabricación de cacao, chocolates y productos de confitería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10740', 'Elaboración de macarrones, fideos, y productos farináceos similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10750', 'Elaboración de comidas y platos preparados para la reventa en locales y/o para exportación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10791', 'Elaboración de productos de café ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10792', 'Elaboración de especies, sazonadores y condimentos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10793', 'Elaboración de sopas, cremas y consomé ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10794', 'Fabricación de bocadillos tostados y/o fritos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10799', 'Elaboración de productos alimenticios ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10800', 'Elaboración de alimentos preparados para animales', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11012', 'Fabricación de aguardiente y licores', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11020', 'Elaboración de vinos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11030', 'Fabricación de cerveza ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11041', 'Fabricación de aguas gaseosas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11042', 'Fabricación y envasado de agua ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11043', 'Elaboración de refrescos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11048', 'Maquilado de aguas gaseosas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('11049', 'Elaboración de bebidas no alcohólicas', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('12000', 'Elaboración de productos de tabaco', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13111', 'Preparación de fibras textiles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13112', 'Fabricación de hilados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13120', 'Fabricación de telas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13130', 'Acabado de productos textiles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13910', 'Fabricación de tejidos de punto y ganchillo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13921', 'Fabricación de productos textiles para el hogar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13922', 'Sacos, bolsas y otros artículos textiles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13929', 'Fabricación de artículos confeccionados con materiales textiles, excepto prendas de vestir ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13930', 'Fabricación de tapices y alfombras ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13941', 'Fabricación de cuerdas de henequén y otras fibras naturales (lazos, pitas) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13942', 'Fabricación de redes de diversos materiales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13948', 'Maquilado de productos trenzables de cualquier material (petates, sillas, etc.) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13991', 'Fabricación de adornos, etiquetas y otros artículos para prendas de vestir ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13992', 'Servicio de bordados en artículos y prendas de tela ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('13999', 'Fabricación de productos textiles ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14101', 'Fabricación de ropa interior, para dormir y similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14102', 'Fabricación de ropa para niños ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14103', 'Fabricación de prendas de vestir para ambos sexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14104', 'Confección de prendas a medida ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14105', 'Fabricación de prendas de vestir para deportes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14106', 'Elaboración de artesanías de uso personal confeccionadas especialmente de materiales textiles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14108', 'Maquilado de prendas de vestir, accesorios y otros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14109', 'Fabricación de prendas y accesorios de vestir n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14200', 'Fabricación de artículos de piel ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14301', 'Fabricación de calcetines, calcetas, medias (panty house) y otros similares', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14302', 'Fabricación de ropa interior de tejido de punto ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('14309', 'Fabricación de prendas de vestir de tejido de punto ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15110', 'Curtido y adobo de cueros; adobo y teñido de pieles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15121', 'Fabricación de maletas, bolsos de mano y otros artículos de marroquinería', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15122', 'Fabricación de monturas, accesorios y vainas talabartería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15123', 'Fabricación de artesanías principalmente de cuero natural y sintético ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15128', 'Maquilado de artículos de cuero natural, sintético y de otros materiales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15201', 'Fabricación de calzado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15202', 'Fabricación de partes y accesorios de calzado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('15208', 'Maquilado de partes y accesorios de calzado', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('16100', 'Aserradero y acepilladura de madera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('16210', 'Fabricación de madera laminada, terciada, enchapada y contrachapada, paneles para la construcción ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('16220', 'Fabricación de partes y piezas de carpintería para edificios y construcciones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('16230', 'Fabricación de envases y recipientes de madera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('16292', 'Fabricación de artesanías de madera, semillas, materiales trenzables ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('16299', 'Fabricación de productos de madera, corcho, paja y materiales trenzables ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('17010', 'Fabricación de pasta de madera, papel y cartón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('17020', 'Fabricación de papel y cartón ondulado y envases de papel y cartón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('17091', 'Fabricación de artículos de papel y cartón de uso personal y doméstico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('17092', 'Fabricación de productos de papel ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('18110', 'Impresión ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('18120', 'Servicios relacionados con la impresión ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('18200', 'Reproducción de grabaciones', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('19100', 'Fabricación de productos de hornos de coque ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('19201', 'Fabricación de combustible ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('19202', 'Fabricación de aceites y lubricantes', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20111', 'Fabricación de materias primas para la fabricación de colorantes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20112', 'Fabricación de materiales curtientes', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20113', 'Fabricación de gases industriales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20114', 'Fabricación de alcohol etílico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20119', 'Fabricación de sustancias químicas básicas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20120', 'Fabricación de abonos y fertilizantes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20130', 'Fabricación de plástico y caucho en formas primarias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20210', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20220', 'Fabricación de pinturas, barnices y productos de revestimiento similares; tintas de imprenta y masillas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20231', 'Fabricación de jabones, detergentes y similares para limpieza ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20232', 'Fabricación de perfumes, cosméticos y productos de higiene y cuidado personal, incluyendo tintes, champú, etc. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20291', 'Fabricación de tintas y colores para escribir y pintar; fabricación de cintas para impresoras ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20292', 'Fabricación de productos pirotécnicos, explosivos y municiones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20299', 'Fabricación de productos químicos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('20300', 'Fabricación de fibras artificiales', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('21001', 'Manufactura de productos farmacéuticos, sustancias químicas y productos botánicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('21008', 'Maquilado de medicamentos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('22110', 'Fabricación de cubiertas y cámaras; renovación y recauchutado de cubiertas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('22190', 'Fabricación de otros productos de caucho ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('22201', 'Fabricación de envases plásticos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('22202', 'Fabricación de productos plásticos para uso personal o doméstico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('22208', 'Maquila de plásticos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('22209', 'Fabricación de productos plásticos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23101', 'Fabricación de vidrio ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23102', 'Fabricación de recipientes y envases de vidrio ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23108', 'Servicio de maquilado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23109', 'Fabricación de productos de vidrio ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23910', 'Fabricación de productos refractarios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23920', 'Fabricación de productos de arcilla para la construcción ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23931', 'Fabricación de productos de cerámica y porcelana no refractaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23932', 'Fabricación de productos de cerámica y porcelana ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23940', 'Fabricación de cemento, cal y yeso', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23950', 'Fabricación de artículos de hormigón, cemento y yeso ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23960', 'Corte, tallado y acabado de la piedra ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('23990', 'Fabricación de productos minerales no metálicos ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('24100', 'Industrias básicas de hierro y acero ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('24200', 'Fabricación de productos primarios de metales preciosos y metales no ferrosos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('24310', 'Fundición de hierro y acero ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('24320', 'Fundición de metales no ferrosos', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25111', 'Fabricación de productos metálicos para uso estructural ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25118', 'Servicio de maquila para la fabricación de estructuras metálicas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25120', 'Fabricación de tanques, depósitos y recipientes de metal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25130', 'Fabricación de generadores de vapor, excepto calderas de agua caliente para calefacción central ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25200', 'Fabricación de armas y municiones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25910', 'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25920', 'Tratamiento y revestimiento de metales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25930', 'Fabricación de artículos de cuchillería, herramientas de mano y artículos de ferretería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25991', 'Fabricación de envases y artículos conexos de metal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25992', 'Fabricación de artículos metálicos de uso personal y/o doméstico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('25999', 'Fabricación de productos elaborados de metal ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26100', 'Fabricación de componentes electrónicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26200', 'Fabricación de computadoras y equipo conexo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26300', 'Fabricación de equipo de comunicaciones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26400', 'Fabricación de aparatos electrónicos de consumo para audio, video radio y televisión ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26510', 'Fabricación de instrumentos y aparatos para medir, verificar, ensayar, navegar y de control de procesos industriales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26520', 'Fabricación de relojes y piezas de relojes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26600', 'Fabricación de equipo médico de irradiación y equipo electrónico de uso médico y terapéutico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26700', 'Fabricación de instrumentos de óptica y equipo fotográfico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('26800', 'Fabricación de medios magnéticos y ópticos', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27100', 'Fabricación de motores, generadores, transformadores eléctricos, aparatos de distribución y control de electricidad', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27200', 'Fabricación de pilas, baterías y acumuladores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27310', 'Fabricación de cables de fibra óptica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27320', 'Fabricación de otros hilos y cables eléctricos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27330', 'Fabricación de dispositivos de cableados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27400', 'Fabricación de equipo eléctrico de iluminación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27500', 'Fabricación de aparatos de uso doméstico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('27900', 'Fabricación de otros tipos de equipo eléctrico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28110', 'Fabricación de motores y turbinas, excepto motores para aeronaves, vehículos automotores y motocicletas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28120', 'Fabricación de equipo hidráulico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28130', 'Fabricación de otras bombas, compresores, grifos y válvulas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28140', 'Fabricación de cojinetes, engranajes, trenes de engranajes y piezas de transmisión ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28150', 'Fabricación de hornos y quemadores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28160', 'Fabricación de equipo de elevación y manipulación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28170', 'Fabricación de maquinaria y equipo de oficina ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28180', 'Fabricación de herramientas manuales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28190', 'Fabricación de otros tipos de maquinaria de uso general ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28210', 'Fabricación de maquinaria agropecuaria y forestal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28220', 'Fabricación de máquinas para conformar metales y maquinaria herramienta ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28230', 'Fabricación de maquinaria metalúrgica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28240', 'Fabricación de maquinaria para la explotación de minas y canteras y para obras de construcción ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28250', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28260', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28291', 'Fabricación de máquinas para imprenta ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('28299', 'Fabricación de maquinaria de uso especial ncp', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('29100', 'Fabricación vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('29200', 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semiremolques ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('29300', 'Fabricación de partes, piezas y accesorios para vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30110', 'Fabricación de buques ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30120', 'Construcción y reparación de embarcaciones de recreo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30200', 'Fabricación de locomotoras y de material rodante', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30300', 'Fabricación de aeronaves y naves espaciales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30400', 'Fabricación de vehículos militares de combate ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30910', 'Fabricación de motocicletas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30920', 'Fabricación de bicicletas y sillones de ruedas para inválidos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('30990', 'Fabricación de equipo de transporte ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('31001', 'Fabricación de colchones y somier ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('31002', 'Fabricación de muebles y otros productos de madera a medida ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('31008', 'Servicios de maquilado de muebles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('31009', 'Fabricación de muebles ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32110', 'Fabricación de joyas platerías y joyerías ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32120', 'Fabricación de joyas de imitación (fantasía) y artículos conexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32200', 'Fabricación de instrumentos musicales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32301', 'Fabricación de artículos de deporte ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32308', 'Servicio de maquila de productos deportivos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32401', 'Fabricación de juegos de mesa y de salón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32402', 'Servicio de maquilado de juguetes y juegos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32409', 'Fabricación de juegos y juguetes n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32500', 'Fabricación de instrumentos y materiales médicos y odontológicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32901', 'Fabricación de lápices, bolígrafos, sellos y artículos de librería en general ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32902', 'Fabricación de escobas, cepillos, pinceles y similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32903', 'Fabricación de artesanías de materiales diversos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32904', 'Fabricación de artículos de uso personal y domésticos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32905', 'Fabricación de accesorios para las confecciones y la marroquinería n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32908', 'Servicios de maquila ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('32909', 'Fabricación de productos manufacturados n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('33110', 'Reparación y mantenimiento de productos elaborados de metal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('33120', 'Reparación y mantenimiento de maquinaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('33130', 'Reparación y mantenimiento de equipo electrónico y óptico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('33140', 'Reparación y mantenimiento de equipo eléctrico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('33150', 'Reparación y mantenimiento de equipo de transporte, excepto vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('33190', 'Reparación y mantenimiento de equipos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('33200', 'Instalación de maquinaria y equipo industrial ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('35101', 'Generación de energía eléctrica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('35102', 'Transmisión de energía eléctrica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('35103', 'Distribución de energía eléctrica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('35200', 'Fabricación de gas, distribución de combustibles gaseosos por tuberías ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('35300', 'Suministro de vapor y agua caliente ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('36000', 'Captación, tratamiento y suministro de agua ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('37000', 'Evacuación de aguas residuales (alcantarillado) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38110', 'Recolección y transporte de desechos sólidos proveniente de hogares y sector urbano ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38120', 'Recolección de desechos peligrosos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38210', 'Tratamiento y eliminación de desechos inicuos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38220', 'Tratamiento y eliminación de desechos peligrosos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38301', 'Reciclaje de desperdicios y desechos textiles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38302', 'Reciclaje de desperdicios y desechos de plástico y caucho ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38303', 'Reciclaje de desperdicios y desechos de vidrio ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38304', 'Reciclaje de desperdicios y desechos de papel y cartón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38305', 'Reciclaje de desperdicios y desechos metálicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('38309', 'Reciclaje de desperdicios y desechos no metálicos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('39000', 'Actividades de Saneamiento y otros Servicios de Gestión de Desechos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('41001', 'Construcción de edificios residenciales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('41002', 'Construcción de edificios no residenciales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('42100', 'Construcción de carreteras, calles y caminos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('42200', 'Construcción de proyectos de servicio público ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('42900', 'Construcción de obras de ingeniería civil n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43110', 'Demolición ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43120', 'Preparación de terreno ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43210', 'Instalaciones eléctricas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43220', 'Instalación de fontanería, calefacción y aire acondicionado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43290', 'Otras instalaciones para obras de construcción', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43300', 'Terminación y acabado de edificios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43900', 'Otras actividades especializadas de construcción ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('43901', 'Fabricación de techos y materiales diversos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45100', 'Venta de vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45201', 'Reparación mecánica de vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45202', 'Reparaciones eléctricas del automotor y recarga de baterías ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45203', 'Enderezado y pintura de vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45204', 'Reparaciones de radiadores, escapes y silenciadores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45205', 'Reparación y reconstrucción de vías, stop y otros artículos de fibra de vidrio ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45206', 'Reparación de llantas de vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45207', 'Polarizado de vehículos (mediante la adhesión de papel especial a los vidrios) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45208', 'Lavado y pasteado de vehículos (carwash) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45209', 'Reparaciones de vehículos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45211', 'Remolque de vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45301', 'Venta de partes, piezas y accesorios nuevos para vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45302', 'Venta de partes, piezas y accesorios usados para vehículos automotores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45401', 'Venta de motocicletas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45402', 'Venta de repuestos, piezas y accesorios de motocicletas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('45403', 'Mantenimiento y reparación de motocicletas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46100', 'Venta al por mayor a cambio de retribución o por contrata ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46201', 'Venta al por mayor de materias primas agrícolas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46202', 'Venta al por mayor de productos de la silvicultura ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46203', 'Venta al por mayor de productos pecuarios y de granja ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46211', 'Venta de productos para uso agropecuario ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46291', 'Venta al por mayor de granos básicos (cereales, leguminosas) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46292', 'Venta al por mayor de semillas mejoradas para cultivo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46293', 'Venta al por mayor de café oro y uva ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46294', 'Venta al por mayor de caña de azúcar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46295', 'Venta al por mayor de flores, plantas y otros productos naturales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46296', 'Venta al por mayor de productos agrícolas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46297', 'Venta al por mayor de ganado bovino (vivo) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46298', 'Venta al por mayor de animales porcinos, ovinos, caprino, canículas, apícolas, avícolas vivos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46299', 'Venta de otras especies vivas del reino animal', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46301', 'Venta al por mayor de alimentos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46302', 'Venta al por mayor de bebidas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46303', 'Venta al por mayor de tabaco ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46371', 'Venta al por mayor de frutas, hortalizas (verduras), legumbres y tubérculos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46372', 'Venta al por mayor de pollos, gallinas destazadas, pavos y otras aves ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46373', 'Venta al por mayor de carne bovina y porcina, productos de carne y embutidos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46374', 'Venta al por mayor de huevos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46375', 'Venta al por mayor de productos lácteos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46376', 'Venta al por mayor de productos farináceos de panadería (pan dulce, cakes, repostería, etc.) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46377', 'Venta al por mayor de pastas alimenticias, aceites y grasas comestibles vegetal y animal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46378', 'Venta al por mayor de sal comestible ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46379', 'Venta al por mayor de azúcar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46391', 'Venta al por mayor de abarrotes (vinos, licores, productos alimenticios envasados, etc.) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46392', 'Venta al por mayor de aguas gaseosas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46393', 'Venta al por mayor de agua purificada ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46394', 'Venta al por mayor de refrescos y otras bebidas, líquidas o en polvo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46395', 'Venta al por mayor de cerveza y licores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46396', 'Venta al por mayor de hielo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46411', 'Venta al por mayor de hilados, tejidos y productos textiles de mercería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46412', 'Venta al por mayor de artículos textiles excepto confecciones para el hogar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46413', 'Venta al por mayor de confecciones textiles para el hogar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46414', 'Venta al por mayor de prendas de vestir y accesorios de vestir ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46415', 'Venta al por mayor de ropa usada ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46416', 'Venta al por mayor de calzado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46417', 'Venta al por mayor de artículos de marroquinería y talabartería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46418', 'Venta al por mayor de artículos de peletería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46419', 'Venta al por mayor de otros artículos textiles n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46471', 'Venta al por mayor de instrumentos musicales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46472', 'Venta al por mayor de colchones, almohadas, cojines, etc. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46473', 'Venta al por mayor de artículos de aluminio para el hogar y para otros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46474', 'Venta al por mayor de depósitos y otros artículos plásticos para el hogar y otros usos, incluyendo los desechables de durapax y no desechables ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46475', 'Venta al por mayor de cámaras fotográficas, accesorios y materiales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46482', 'Venta al por mayor de medicamentos, artículos y otros productos de uso veterinario', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46483', 'Venta al por mayor de productos y artículos de belleza y de uso personal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46484', 'Venta de productos farmacéuticos y medicinales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46491', 'Venta al por mayor de productos medicinales, cosméticos, perfumería y productos de limpieza ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46492', 'Venta al por mayor de relojes y artículos de joyería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46493', 'Venta al por mayor de electrodomésticos y artículos del hogar excepto bazar; artículos de iluminación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46494', 'Venta al por mayor de artículos de bazar y similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46495', 'Venta al por mayor de artículos de óptica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46496', 'Venta al por mayor de revistas, periódicos, libros, artículos de librería y artículos de papel y cartón en general ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46497', 'Venta de artículos deportivos, juguetes y rodados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46498', 'Venta al por mayor de productos usados para el hogar o el uso personal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46499', 'Venta al por mayor de enseres domésticos y de uso personal n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46500', 'Venta al por mayor de bicicletas, partes, accesorios y otros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46510', 'Venta al por mayor de computadoras, equipo periférico y programas informáticos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46520', 'Venta al por mayor de equipos de comunicación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46530', 'Venta al por mayor de maquinaria y equipo agropecuario, accesorios, partes y suministros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46590', 'Venta de equipos e instrumentos de uso profesional y científico y aparatos de medida y control ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46591', 'Venta al por mayor de maquinaria equipo, accesorios y materiales para la industria de la madera y sus productos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46592', 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria gráfica y del papel, cartón y productos de papel y cartón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46593', 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria de productos químicos, plástico y caucho ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46594', 'Venta al por mayor de maquinaria, equipo, accesorios y materiales para la industria metálica y de sus productos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46595', 'Venta al por mayor de equipamiento para uso médico, odontológico, veterinario y servicios conexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46596', 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria de la alimentación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46597', 'Venta al por mayor de maquinaria, equipo, accesorios y partes para la industria textil, confecciones y cuero ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46598', 'Venta al por mayor de maquinaria, equipo y accesorios para la construcción y explotación de minas y canteras ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46599', 'Venta al por mayor de otro tipo de maquinaria y equipo con sus accesorios y partes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46610', 'Venta al por mayor de otros combustibles sólidos, líquidos, gaseosos y de productos conexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46612', 'Venta al por mayor de combustibles para automotores, aviones, barcos, maquinaria y otros', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46613', 'Venta al por mayor de lubricantes, grasas y otros aceites para automotores, maquinaria industrial, etc. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46614', 'Venta al por mayor de gas propano ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46615', 'Venta al por mayor de leña y carbón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46620', 'Venta al por mayor de metales y minerales metalíferos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46631', 'Venta al por mayor de puertas, ventanas, vitrinas y similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46632', 'Venta al por mayor de artículos de ferretería y pinturerías ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46633', 'Vidrierías ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46634', 'Venta al por mayor de maderas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46639', 'Venta al por mayor de materiales para la construcción n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46691', 'Venta al por mayor de sal industrial sin yodar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46692', 'Venta al por mayor de productos intermedios y desechos de origen textil ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46693', 'Venta al por mayor de productos intermedios y desechos de origen metálico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46694', 'Venta al por mayor de productos intermedios y desechos de papel y cartón ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46695', 'Venta al por mayor fertilizantes, abonos, agroquímicos y productos similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46696', 'Venta al por mayor de productos intermedios y desechos de origen plástico', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46697', 'Venta al por mayor de tintas para imprenta, productos curtientes y materias y productos colorantes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46698', 'Venta de productos intermedios y desechos de origen químico y de caucho ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46699', 'Venta al por mayor de productos intermedios y desechos ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46701', 'Venta de algodón en oro ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46900', 'Venta al por mayor de otros productos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46901', 'Venta al por mayor de cohetes y otros productos pirotécnicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46902', 'Venta al por mayor de artículos diversos para consumo humano ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46903', 'Venta al por mayor de armas de fuego, municiones y accesorios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46904', 'Venta al por mayor de toldos y tiendas de campaña de cualquier material ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46905', 'Venta al por mayor de exhibidores publicitarios y rótulos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('46906', 'Venta al por mayor de artículos promocionales diversos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47111', 'Venta en supermercados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47112', 'Venta en tiendas de artículos de primera necesidad', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47119', 'Almacenes (venta de diversos artículos) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47190', 'Venta al por menor de otros productos en comercios no especializados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47199', 'Venta de establecimientos no especializados con surtido compuesto principalmente de alimentos, bebidas y tabaco ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47211', 'Venta al por menor de frutas y hortalizas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47212', 'Venta al por menor de carnes, embutidos y productos de granja ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47213', 'Venta al por menor de pescado y mariscos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47214', 'Venta al por menor de productos lácteos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47215', 'Venta al por menor de productos de panadería, repostería y galletas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47216', 'Venta al por menor de huevos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47217', 'Venta al por menor de carnes y productos cárnicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47218', 'Venta al por menor de granos básicos y otros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47219', 'Venta al por menor de alimentos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47221', 'Venta al por menor de hielo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47223', 'Venta de bebidas no alcohólicas, para su consumo fuera del establecimiento ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47224', 'Venta de bebidas alcohólicas, para su consumo fuera del establecimiento ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47225', 'Venta de bebidas alcohólicas para su consumo dentro del establecimiento ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47230', 'Venta al por menor de tabaco ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47300', 'Venta de combustibles, lubricantes y otros (gasolineras) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47411', 'Venta al por menor de computadoras y equipo periférico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47412', 'Venta de equipo y accesorios de telecomunicación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47420', 'Venta al por menor de equipo de audio y video ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47510', 'Venta al por menor de hilados, tejidos y productos textiles de mercería; confecciones para el hogar y textiles n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47521', 'Venta al por menor de productos de madera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47522', 'Venta al por menor de artículos de ferretería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47523', 'Venta al por menor de productos de pinturerías ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47524', 'Venta al por menor en vidrierías ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47529', 'Venta al por menor de materiales de construcción y artículos conexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47530', 'Venta al por menor de tapices, alfombras y revestimientos de paredes y pisos en comercios especializados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47591', 'Venta al por menor de muebles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47592', 'Venta al por menor de artículos de bazar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47593', 'Venta al por menor de aparatos electrodomésticos, repuestos y accesorios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47594', 'Venta al por menor de artículos eléctricos y de iluminación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47598', 'Venta al por menor de instrumentos musicales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47610', 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47620', 'Venta al por menor de discos láser, cassettes, cintas de video y otros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47630', 'Venta al por menor de productos y equipos de deporte ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47631', 'Venta al por menor de bicicletas, accesorios y repuestos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47640', 'Venta al por menor de juegos y juguetes en comercios especializados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47711', 'Venta al por menor de prendas de vestir y accesorios de vestir ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47712', 'Venta al por menor de calzado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47713', 'Venta al por menor de artículos de peletería, marroquinería y talabartería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47721', 'Venta al por menor de medicamentos farmacéuticos y otros materiales y artículos de uso médico, odontológico y veterinario ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47722', 'Venta al por menor de productos cosméticos y de tocador ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47731', 'Venta al por menor de productos de joyería, bisutería, óptica, relojería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47732', 'Venta al por menor de plantas, semillas, animales y artículos conexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47733', 'Venta al por menor de combustibles de uso doméstico (gas propano y gas licuado)', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47734', 'Venta al por menor de artesanías, artículos cerámicos y recuerdos en general ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47735', 'Venta al por menor de ataúdes, lápidas y cruces, trofeos, artículos religiosos en general ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47736', 'Venta al por menor de armas de fuego, municiones y accesorios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47737', 'Venta al por menor de artículos de cohetería y pirotécnicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47738', 'Venta al por menor de artículos desechables de uso personal y doméstico (servilletas, papel higiénico, pañales, toallas sanitarias, etc.) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47739', 'Venta al por menor de otros productos n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47741', 'Venta al por menor de artículos usados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47742', 'Venta al por menor de textiles y confecciones usados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47743', 'Venta al por menor de libros, revistas, papel y cartón usados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47749', 'Venta al por menor de productos usados n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47811', 'Venta al por menor de frutas, verduras y hortalizas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47814', 'Venta al por menor de productos lácteos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47815', 'Venta al por menor de productos de panadería, galletas y similares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47816', 'Venta al por menor de bebidas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47818', 'Venta al por menor en tiendas de mercado y puestos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47821', 'Venta al por menor de hilados, tejidos y productos textiles de mercería en puestos de mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47822', 'Venta al por menor de artículos textiles excepto confecciones para el hogar en puestos de mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47823', 'Venta al por menor de confecciones textiles para el hogar en puestos de mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47824', 'Venta al por menor de prendas de vestir, accesorios de vestir y similares en puestos de mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47825', 'Venta al por menor de ropa usada', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47826', 'Venta al por menor de calzado, artículos de marroquinería y talabartería en puestos de mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47827', 'Venta al por menor de artículos de marroquinería y talabartería en puestos de mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47829', 'Venta al por menor de artículos textiles ncp en puestos de mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47891', 'Venta al por menor de animales, flores y productos conexos en puestos de feria y mercados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47892', 'Venta al por menor de productos medicinales, cosméticos, de tocador y de limpieza en puestos de ferias y mercados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47893', 'Venta al por menor de artículos de bazar en puestos de ferias y mercados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47894', 'Venta al por menor de artículos de papel, envases, libros, revistas y conexos en puestos de feria y mercados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47895', 'Venta al por menor de materiales de construcción, electrodomésticos, accesorios para autos y similares en puestos de feria y mercados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47896', 'Venta al por menor de equipos accesorios para las comunicaciones en puestos de feria y mercados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47899', 'Venta al por menor en puestos de ferias y mercados n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47910', 'Venta al por menor por correo o Internet ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('47990', 'Otros tipos de venta al por menor no realizada, en almacenes, puestos de venta o mercado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49110', 'Transporte interurbano de pasajeros por ferrocarril ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49120', 'Transporte de carga por ferrocarril ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49211', 'Transporte de pasajeros urbanos e interurbano mediante buses ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49212', 'Transporte de pasajeros interdepartamental mediante microbuses ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49213', 'Transporte de pasajeros urbanos e interurbano mediante microbuses ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49214', 'Transporte de pasajeros interdepartamental mediante buses ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49221', 'Transporte internacional de pasajeros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49222', 'Transporte de pasajeros mediante taxis y autos con chofer ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49223', 'Transporte escolar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49225', 'Transporte de pasajeros para excursiones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49226', 'Servicios de transporte de personal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49229', 'Transporte de pasajeros por vía terrestre ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49231', 'Transporte de carga urbano ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49232', 'Transporte nacional de carga ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49233', 'Transporte de carga internacional ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49234', 'Servicios de mudanza ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49235', 'Alquiler de vehículos de carga con conductor ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('49300', 'Transporte por oleoducto o gasoducto', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('50110', 'Transporte de pasajeros marítimo y de cabotaje ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('50120', 'Transporte de carga marítimo y de cabotaje ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('50211', 'Transporte de pasajeros por vías de navegación interiores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('50212', 'Alquiler de equipo de transporte de pasajeros por vías de navegación interior con conductor ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('50220', 'Transporte de carga por vías de navegación interiores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('51100', 'Transporte aéreo de pasajeros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('51201', 'Transporte de carga por vía aérea ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('51202', 'Alquiler de equipo de aerotransporte con operadores para el propósito de transportar carga ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52101', 'Alquiler de instalaciones de almacenamiento en zonas francas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52102', 'Alquiler de silos para conservación y almacenamiento de granos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52103', 'Alquiler de instalaciones con refrigeración para almacenamiento y conservación de alimentos y otros productos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52109', 'Alquiler de bodegas para almacenamiento y depósito n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52211', 'Servicio de garaje y estacionamiento ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52212', 'Servicios de terminales para el transporte por vía terrestre ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52219', 'Servicios para el transporte por vía terrestre n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52220', 'Servicios para el transporte acuático ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52230', 'Servicios para el transporte aéreo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52240', 'Manipulación de carga ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52290', 'Servicios para el transporte ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('52291', 'Agencias de tramitaciones aduanales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('53100', 'Servicios de correo nacional ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('53200', 'Actividades de correo distintas a las actividades postales nacionales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('53201', 'Agencia privada de correo y encomiendas', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('55101', 'Actividades de alojamiento para estancias cortas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('55102', 'Hoteles ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('55200', 'Actividades de campamentos, parques de vehículos de recreo y parques de caravanas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('55900', 'Alojamiento n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56101', 'Restaurantes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56106', 'Pupusería', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56107', 'Actividades varias de restaurantes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56108', 'Comedores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56109', 'Merenderos ambulantes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56210', 'Preparación de comida para eventos especiales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56291', 'Servicios de provisión de comidas por contrato ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56292', 'Servicios de concesión de cafetines y chalet en empresas e instituciones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56299', 'Servicios de preparación de comidas ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56301', 'Servicio de expendio de bebidas en salones y bares ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('56302', 'Servicio de expendio de bebidas en puestos callejeros, mercados y ferias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('58110', 'Edición de libros, folletos, partituras y otras ediciones distintas a estas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('58120', 'Edición de directorios y listas de correos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('58130', 'Edición de periódicos, revistas y otras publicaciones periódicas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('58190', 'Otras actividades de edición ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('58200', 'Edición de programas informáticos (software) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('59110', 'Actividades de producción cinematográfica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('59120', 'Actividades de post producción de películas, videos y programas de televisión ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('59130', 'Actividades de distribución de películas cinematográficas, videos y programas de televisión ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('59140', 'Actividades de exhibición de películas cinematográficas y cintas de vídeo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('59200', 'Actividades de edición y grabación de música ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('60100', 'Servicios de difusiones de radio ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('60201', 'Actividades de programación y difusión de televisión abierta ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('60202', 'Actividades de suscripción y difusión de televisión por cable y/o suscripción ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('60299', 'Servicios de televisión, incluye televisión por cable ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('60900', 'Programación y transmisión de radio y televisión ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61101', 'Servicio de telefonía ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61102', 'Servicio de Internet ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61103', 'Servicio de telefonía fija ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61109', 'Servicio de Internet n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61201', 'Servicios de telefonía celular ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61202', 'Servicios de Internet inalámbrico', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61209', 'Servicios de telecomunicaciones inalámbrico n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61301', 'Telecomunicaciones satelitales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61309', 'Comunicación vía satélite n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('61900', 'Actividades de telecomunicación n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('62010', 'Programación informática ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('62020', 'Consultorías y gestión de servicios informáticos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('62090', 'Otras actividades de tecnología de información y servicios de computadora ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('63110', 'Procesamiento de datos y actividades relacionadas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('63120', 'Portales WEB ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('63910', 'Servicios de Agencias de Noticias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('63990', 'Otros servicios de información n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64110', 'Servicios provistos por el Banco Central de El salvador ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64190', 'Bancos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64192', 'Entidades dedicadas al envío de remesas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64199', 'Otras entidades financieras ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64200', 'Actividades de sociedades de cartera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64300', 'Fideicomisos, fondos y otras fuentes de financiamiento ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64910', 'Arrendamientos financieros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64920', 'Asociaciones cooperativas de ahorro y crédito dedicadas a la intermediación financiera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64921', 'Instituciones emisoras de tarjetas de crédito y otros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64922', 'Tipos de crédito ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64928', 'Prestamistas y casas de empeño ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('64990', 'Actividades de servicios financieros, excepto la financiación de planes de seguros y de pensiones n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('65110', 'Planes de seguros de vida ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('65120', 'Planes de seguro excepto de vida ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('65199', 'Seguros generales de todo tipo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('65200', 'Planes se seguro ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('65300', 'Planes de pensiones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('66110', 'Administración de mercados financieros (Bolsa de Valores) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('66120', 'Actividades bursátiles (Corredores de Bolsa) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('66190', 'Actividades auxiliares de la intermediación financiera ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('66210', 'Evaluación de riesgos y daños ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('66220', 'Actividades de agentes y corredores de seguros ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('66290', 'Otras actividades auxiliares de seguros y fondos de pensiones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('66300', 'Actividades de administración de fondos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('68101', 'Servicio de alquiler y venta de lotes en cementerios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('68109', 'Actividades inmobiliarias realizadas con bienes propios o arrendados n.c.p.', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('68200', 'Actividades Inmobiliarias Realizadas a Cambio de una Retribución o por Contrata ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('69100', 'Actividades jurídicas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('69200', 'Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento en materia de impuestos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('70100', 'Actividades de oficinas centrales de sociedades de cartera ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('70200', 'Actividades de consultoría en gestión empresarial ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('71101', 'Servicios de arquitectura y planificación urbana y servicios conexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('71102', 'Servicios de ingeniería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('71103', 'Servicios de agrimensura, topografía, cartografía, prospección y geofísica y servicios conexos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('71200', 'Ensayos y análisis técnicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('72100', 'Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('72199', 'Investigaciones científicas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('72200', 'Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades científica y desarrollo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('73100', 'Publicidad ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('73200', 'Investigación de mercados y realización de encuestas de opinión pública ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('74100', 'Actividades de diseño especializado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('74200', 'Actividades de fotografía', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('74900', 'Servicios profesionales y científicos ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('75000', 'Actividades veterinarias ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77101', 'Alquiler de equipo de transporte terrestre ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77102', 'Alquiler de equipo de transporte acuático ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77103', 'Alquiler de equipo de transporte por vía aérea ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77210', 'Alquiler y arrendamiento de equipo de recreo y deportivo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77220', 'Alquiler de cintas de video y discos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77290', 'Alquiler de otros efectos personales y enseres domésticos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77300', 'Alquiler de maquinaria y equipo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('77400', 'Arrendamiento de productos de propiedad intelectual ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('78100', 'Obtención y dotación de personal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('78200', 'Actividades de las agencias de trabajo temporal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('78300', 'Dotación de recursos humanos y gestión; gestión de las funciones de recursos humanos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('79110', 'Actividades de agencias de viajes y organizadores de viajes; actividades de asistencia a turistas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('79120', 'Actividades de los operadores turísticos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('79900', 'Otros servicios de reservas y actividades relacionadas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('80100', 'Servicios de seguridad privados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('80201', 'Actividades de servicios de sistemas de seguridad ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('80202', 'Actividades para la prestación de sistemas de seguridad ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('80300', 'Actividades de investigación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('81100', 'Actividades combinadas de mantenimiento de edificios e instalaciones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('81210', 'Limpieza general de edificios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('81290', 'Otras actividades combinadas de mantenimiento de edificios e instalaciones ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('81300', 'Servicio de jardinería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82110', 'Servicios administrativos de oficinas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82190', 'Servicio de fotocopiado y similares, excepto en imprentas', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82200', 'Actividades de las centrales de llamadas (call center) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82300', 'Organización de convenciones y ferias de negocios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82910', 'Actividades de agencias de cobro y oficinas de crédito ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82921', 'Servicios de envase y empaque de productos alimenticios ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82922', 'Servicios de envase y empaque de productos medicinales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82929', 'Servicio de envase y empaque ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('82990', 'Actividades de apoyo empresariales ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84110', 'Actividades de la Administración Pública en general ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84111', 'Alcaldías municipales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84120', 'Regulación de las actividades de prestación de servicios sanitarios, educativos, culturales y otros servicios sociales, excepto seguridad social ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84130', 'Regulación y facilitación de la actividad económica ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84210', 'Actividades de administración y funcionamiento del Ministerio de Relaciones Exteriores ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84220', 'Actividades de defensa ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84230', 'Actividades de mantenimiento del orden público y de seguridad ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('84300', 'Actividades de planes de seguridad social de afiliación obligatoria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85101', 'Guardería educativa ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85102', 'Enseñanza preescolar o parvularia ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85103', 'Enseñanza primaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85104', 'Servicio de educación preescolar y primaria integrada ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85211', 'Enseñanza secundaria tercer ciclo (7°, 8° y 9°) ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85212', 'Enseñanza secundaria de formación general bachillerato ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85221', 'Enseñanza secundaria de formación técnica y profesional ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85222', 'Enseñanza secundaria de formación técnica y profesional integrada con enseñanza primaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85301', 'Enseñanza superior universitaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85302', 'Enseñanza superior no universitaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85303', 'Enseñanza superior integrada a educación secundaria y/o primaria ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85410', 'Educación deportiva y recreativa ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85420', 'Educación cultural ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85490', 'Otros tipos de enseñanza n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85499', 'Enseñanza formal ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('85500', 'Servicios de apoyo a la enseñanza', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('86100', 'Actividades de hospitales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('86201', 'Clínicas médicas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('86202', 'Servicios de Odontología ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('86203', 'Servicios médicos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('86901', 'Servicios de análisis y estudios de diagnóstico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('86902', 'Actividades de atención de la salud humana ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('86909', 'Otros Servicio relacionados con la salud ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('87100', 'Residencias de ancianos con atención de enfermería ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('87200', 'Instituciones dedicadas al tratamiento del retraso mental, problemas de salud mental y el uso indebido de sustancias nocivas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('87300', 'Instituciones dedicadas al cuidado de ancianos y discapacitados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('87900', 'Actividades de asistencia a niños y jóvenes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('87901', 'Otras actividades de atención en instituciones ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('88100', 'Actividades de asistencia sociales sin alojamiento para ancianos y discapacitados ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('88900', 'Servicios sociales sin alojamiento ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('90000', 'Actividades creativas artísticas y de esparcimiento ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('91010', 'Actividades de bibliotecas y archivos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('91020', 'Actividades de museos y preservación de lugares y edificios históricos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('91030', 'Actividades de jardines botánicos, zoológicos y de reservas naturales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('92000', 'Actividades de juegos y apuestas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('93110', 'Gestión de instalaciones deportivas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('93120', 'Actividades de clubes deportivos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('93190', 'Otras actividades deportivas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('93210', 'Actividades de parques de atracciones y parques temáticos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('93291', 'Discotecas y salas de baile ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('93298', 'Centros vacacionales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('93299', 'Actividades de esparcimiento ncp ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('94110', 'Actividades de organizaciones empresariales y de empleadores', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('94120', 'Actividades de organizaciones profesionales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('94200', 'Actividades de sindicatos ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('94910', 'Actividades de organizaciones religiosas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('94920', 'Actividades de organizaciones políticas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('94990', 'Actividades de asociaciones n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95110', 'Reparación de computadoras y equipo periférico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95120', 'Reparación de equipo de comunicación ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95210', 'Reparación de aparatos electrónicos de consumo ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95220', 'Reparación de aparatos doméstico y equipo de hogar y jardín ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95230', 'Reparación de calzado y artículos de cuero ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95240', 'Reparación de muebles y accesorios para el hogar ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95291', 'Reparación de Instrumentos musicales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95292', 'Servicios de cerrajería y copiado de llaves ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95293', 'Reparación de joyas y relojes ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95294', 'Reparación de bicicletas, sillas de ruedas y rodados n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('95299', 'Reparaciones de enseres personales n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('96010', 'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('96020', 'Peluquería y otros tratamientos de belleza ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('96030', 'Pompas fúnebres y actividades conexas ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('96091', 'Servicios de sauna y otros servicios para la estética corporal n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('96092', 'Servicios n.c.p. ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('97000', 'Actividad de los hogares en calidad de empleadores de personal doméstico ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('98100', 'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('98200', 'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio  ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('99000', 'Actividades de organizaciones y órganos extraterritoriales ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10001', 'Empleados', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10002', 'Pensionado', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10003', 'Estudiante ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10004', 'Desempleado ', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10005', 'Otros', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL),
('10006', 'Comerciante', 1, 'SYS-BPEDROZA', GETDATE(), NULL, NULL);