-- SCRIP PARA INSERTAR NUEVO REGISTRO DE BANCO BANPAIS HN
BEGIN TRY
    BEGIN TRANSACTION;
		--ACTUALIZAR BANCO CUSCATLAN
		UPDATE dbo.DeliveryBank
		SET ACHCode = 6,
		PayingBank = 109,
		WHERE Id_bank = 124

		--ACTUALIZAR BANCO CREDIQ
		UPDATE dbo.DeliveryBank
		SET ACHCode = 52,
		PayingBank = 109
		WHERE Id_bank = 136

		--ACTUALIZAR BANCO CENTRAL DE HONDURAS
		UPDATE dbo.DeliveryBank
		SET ACHCode = 1,
		PayingBank = 109
		WHERE Id_bank = 114

		--ACTUALIZAR BANCO DE OCCIDENTE S.A.
		UPDATE dbo.DeliveryBank
		SET ACHCode = 7,
		PayingBank = 109
		WHERE Id_bank = 52

		--ACTUALIZAR BANCO DE HONDURAS
		UPDATE dbo.DeliveryBank
		SET ACHCode = 13,
		PayingBank = 109
		WHERE Id_bank = 111

		--ACTUALIZAR BANCO HONDUREÑO DEL CAFE
		UPDATE dbo.DeliveryBank
		SET ACHCode = 14,
		PayingBank = 109
		WHERE Id_bank = 112

		--ACTUALIZAR BANCO LAFISE
		UPDATE dbo.DeliveryBank
		SET ACHCode = 17,
		PayingBank = 109
		WHERE Id_bank = 116

		--ACTUALIZAR BANCO FINANCIERA CENTROAMERICANA S.A.
		UPDATE dbo.DeliveryBank
		SET ACHCode = 18,
		PayingBank = 109
		WHERE Id_bank = 117

		--ACTUALIZAR BANCO DE AMERICA CENTRAL
		UPDATE dbo.DeliveryBank
		SET ACHCode = 24,
		PayingBank = 109
		WHERE Id_bank = 109

		--ACTUALIZAR BANCO FICOHSA
		UPDATE dbo.DeliveryBank
		SET ACHCode = 28,
		PayingBank = 109
		WHERE Id_bank = 108

		--ACTUALIZAR BANCO DE DESARROLLO RURAL
		UPDATE dbo.DeliveryBank
		SET ACHCode = 31,
		PayingBank = 109
		WHERE Id_bank = 110

		--ACTUALIZAR BANCO AZTECA
		UPDATE dbo.DeliveryBank
		SET ACHCode = 32,
		PayingBank = 109
		WHERE Id_bank = 17

		--ACTUALIZAR BANCO NACIONAL DE DESARROLLO AGRICOLA
		UPDATE dbo.DeliveryBank
		SET ACHCode = 51,
		PayingBank = 109
		WHERE Id_bank = 119
	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
END CATCH