---Correge el nombre del banco FICOHSA en Honduras.
	UPDATE DeliveryBank
	set Name = 'BANCO FICOHSA',	Description = 'FICOHSA'
	where Id_bank = 108
		

--- Se insertan las reglas para los bancos de honduras
	-- 17 -  BANCO AZTECA	
	INSERT INTO AccountBankFormatRule VALUES(17, 3 ,14,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	-- 48 - BAC		
	INSERT INTO AccountBankFormatRule VALUES(48, 3 ,9,9,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(48, 4 ,9,9,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	--50 - BANCO AMERICA CENTRAL 		
	INSERT INTO AccountBankFormatRule VALUES(50, 3 ,9,9,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(50, 4 ,9,9,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

			
	--109 - BANCO DE AMERICA CENTRAL 		
	INSERT INTO AccountBankFormatRule VALUES(109, 3 ,9,9,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(109, 4 ,9,9,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	-- 19 - BANCO ATLANTIDA		
	INSERT INTO AccountBankFormatRule VALUES(19, 3 ,10,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(19, 4 ,10,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	
	--53 - BANCO ATLANTIDA S.A. DE C.V.'			
	INSERT INTO AccountBankFormatRule VALUES(53, 3 ,10,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(53, 4 ,10,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	--108 - BANCO FICOHSA'		
	INSERT INTO AccountBankFormatRule VALUES(108, 3 ,14,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(108, 4 ,14,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	--27 - BANCO DAVIVIENDA HONDURAS S.A.'			
	INSERT INTO AccountBankFormatRule VALUES(27, 3 ,1,10,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(27, 4 ,1,10,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	--21 - DAVIVIENDA'
	INSERT INTO AccountBankFormatRule VALUES(21, 3 ,1,10,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(21, 4 ,1,10,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	--110 - BANCO DE DESARROLLO RURAL'			
	INSERT INTO AccountBankFormatRule VALUES(110, 3 ,13,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(110, 4 ,13,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

					   
	--16 - BANCO DE OCCIDENTE			
	INSERT INTO AccountBankFormatRule VALUES(16, 3 ,10,12,2,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(16, 4 ,10,12,1,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	--52 - BANCO DE OCCIDENTE S.A DE C.V.'			
	INSERT INTO AccountBankFormatRule VALUES(52, 3 ,10,12,2,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(52, 4 ,10,12,1,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	--51 - BANCO FINANCIERA COMERCIAL HONDUREÑA S.A
	INSERT INTO AccountBankFormatRule VALUES(51, 3 ,14,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(51, 4 ,14,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	
	--NUEVOS BANCOS HONDURAS

	INSERT INTO DeliveryBank VALUES(111,'BANCO DE HONDURAS','BAH','BANCO DE HONDURAS',GETDATE(),1,'HN','/banks/hn/banhn.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(111, 3 ,10,10,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(111, 4 ,7,10,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(112,'BANCO HONDUREÑO DEL CAFE','BANHCAFE','BANCO HONDUREÑO DEL CAFE',GETDATE(),1,'HN','/banks/hn/banhcafe.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(112, 3 ,10,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(112, 4 ,10,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(113,'BANCO DEL PAIS','BAP HONRUDAS','BANCO DEL PAIS HONDURAS',GETDATE(),1,'HN','/banks/hn/banph.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(113, 3 ,7,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(113, 4 ,7,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(114,'BANCO CENTRAL DE HONDURAS','','BANCO CENTRAL DE HONDURAS',GETDATE(),1,'HN','/banks/hn/banchn.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(114, 3 ,14,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(114, 4 ,14,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(115,'BANCO DE TRABAJADORES','BANTRABH','BANCO DE TRABAJADORES HONDURAS',GETDATE(),1,'HN','/banks/hn/bantrabh.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(115, 3 ,12,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(115, 4 ,12,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(116,'BANCO LAFISE','LAFISE','BANCO LAFISE HONDURAS',GETDATE(),1,'HN','/banks/hn/banlafise.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(116, 3 ,12,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(116, 4 ,12,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(117,'BANCO FINANCIERA CENTROAMERICANA S.A.','FICENSA','BANCO FINANCIERA CENTROAMERICANA S.A.',GETDATE(),1,'HN','/banks/hn/banficensa.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(117, 3 ,11,11,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(117, 4 ,11,11,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(118,'BANCO PROMERICA','PROMERICA','BANCO PROMERICA HONDURAS',GETDATE(),1,'HN','/banks/hn/banpromericah.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(118, 3 ,1,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(118, 4 ,1,14,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);


	INSERT INTO DeliveryBank VALUES(119,'BANCO NACIONAL DE DESARROLLO AGRICOLA','BANADESA','BANCO NACIONAL DE DESARROLLO AGRICOLA',GETDATE(),1,'HN','/banks/hn/banadesa.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(119, 3 ,5,13,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(119, 4 ,5,13,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);

	INSERT INTO DeliveryBank VALUES(120,'BANCO POPULAR','','BANCO POPULAR HONDURAS',GETDATE(),1,'HN','/banks/hn/banpopular.png',NULL, NULL,NULL);
	INSERT INTO AccountBankFormatRule VALUES(120, 3 ,12,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);
	INSERT INTO AccountBankFormatRule VALUES(120, 4 ,12,12,NULL,0,1,'SYS-BPEDROZA', GETDATE(),NULL, NULL);