BEGIN TRY

--GT
DECLARE @TokenUpdate NVARCHAR(50) = 'SYS-BPEDROZA';
UPDATE CS SET CS.RackPositionDefault = '10#EXC016PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC HUEHUE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC043PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC QUICHE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC049PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CHIANTLA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC006PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC XELA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC024PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC TOTONICAPAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC025PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC XELA CENTRO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC040PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC INTERPLAZA XELA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC046PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SOLOLA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC054PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC 4 CAMINOS' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC011PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MAZATE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC031PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SAN MARCOS' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC033PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MALACATAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC035PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC COATEPEQUE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC048PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC RETALHULEU' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC053PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SALCAJA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC020PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC COBAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC022PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ZACAPA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC023PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SALAMA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC034PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PETEN Sta. ELENA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC036PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC TECULUTAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC050PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PUERTO BARRIOS' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC059PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MORALES' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC065PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC METROPLAZA POPTUN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC021PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CHIQUIMULA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC027PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC JALAPA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC028PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC BARBERENA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC030PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC JUTIAPA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC037PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SANARATE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC051PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ESQUIPULAS' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC007PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CHIMALTENANGO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC009PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ANTIGUA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC032PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SANTA LUCIA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC042PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ESCUINTLA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC052PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PALIN ESCUINTLA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC069PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SAN LUCAS SACATEPÉQUEZ' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC072PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC INTERPLAZA CHIMALTENANGO' AND StationType = 2 AND RowStatus=1
UPDATE CS SET CS.RackPositionDefault = '10#EXC001PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC 20 CALLE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC002PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC Calz. SAN JUAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC003PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PLAZA LEON Z1' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC004PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC METRONORTE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC005PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MONTUFAR' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC008PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ROOSEVELT' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC010PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SAN CRISTOBAL' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC012PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ZONA 6' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC013PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PETAPA ZONA 12' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC014PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PRADERA VILLA NUEVA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC015PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC AMATITLAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC017PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PLAZA PARQUE MINERVA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC019PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC REFORMADOR Z4' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC026PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC HINCAPIE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC029PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PINULA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC038PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC VILLA HERMOSA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC039PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PUMA SAN FRANCISCO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC041PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PERIFERICO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC044PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PUMA SAN JUAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC045PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SANTA AMELIA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC047PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC EL ZAPOTE, Z. 2' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC055PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MADERO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC057PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SAN JUAN SACATEPEQUEZ' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC058PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PLAZA ATLANTIC ZONA 18' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC060PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC VILLA NUEVA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC061PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MIXCO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC063PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC Monte Maria' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC066PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ZONA 15 V.H.' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC067PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC VILLA CANALES' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC070PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC ASUNCION ZONA 5' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC071PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC BARCENAS VILLA NUEVA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC073PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CONDADO FRAIJANES' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC074PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SANTA RITA ROOSEVELT' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC075PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC BOCA DEL MONTE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC076PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC 20 CALLE ZONA 10' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC077PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC Los Olivos Zona 18' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC078PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CARCHA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC079PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC Xela Zona 8' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC080PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PATZICIA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC082PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC LA TERMINAL' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC083PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC Tinajon' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC087PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PLAZA ARREBOL Z10' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC084PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC OLMECA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC085PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC VILLA NUEVA CALLE REAL' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC086PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SAN CRISTOBAL BLVR' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC089PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SAN RAFAEL Z.18' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC090PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC AVENIDA ELENA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC091PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC HACIENDA REAL' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC092PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CIUDAD QUETZAL' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC093PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC LA FLORIDA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC094PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PERONIA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC095PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC LA TERMINAL 2' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC096PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC DIAGONAL  ZONA 10' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC097PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC LINDA VISTA VILLA NUEVA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC098PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC EL CUENTRO SAN JOSE PINULA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC099PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MUXBAL' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC100PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC BETHANIA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC101PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'EXC BOSQUES DE SAN NICOLAS' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC102PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CENTRICO ZONA 5' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC103PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = ' FD EXC EL MILAGRO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC104PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MATEO FLORES' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC105PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = ' FD EXC PLAZA ONCE ZONA 11 HUEHUETENANGO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC106PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SAN JUAN OSTUNCALCO' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC107PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = ' FD EXC PLAZA GERONA CAES' AND StationType = 2 AND RowStatus= 1



--HN
UPDATE CS SET CS.RackPositionDefault = '10#EXC501PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC BLV JUAN PABLO II' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC513PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC LAS ACACIAS' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC502PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC BLV MORAZAN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC503PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CIRCUNVALACION' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC504PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC COMAYAGUA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC505PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC KENNEDY' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC506PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC LA CEIBA 1' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC507PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC MAMA CHEPA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC508PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PLAZA PREMIER' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC509PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC PLAZA SAN ANTONIO DE PADUA' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC510PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC SIGUATEPEQUE' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC511PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC TOCONTIN' AND StationType = 2 AND RowStatus= 1
UPDATE CS SET CS.RackPositionDefault = '10#EXC512PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC CHOLUTECA 1' AND StationType = 2 AND RowStatus= 1




--SV

UPDATE CS SET CS.RackPositionDefault ='10#EXC801PAL001' , TokenUpdated = @TokenUpdate, DateUpdated= GETDATE() FROM DeliveryBackOffice.dbo.CatStation CS WITH(NOLOCK) WHERE StationName = 'FD EXC DISTRITO OLIMPICA' AND StationType = 2 AND RowStatus= 1

END TRY
BEGIN CATCH

    PRINT 'Error: ' + ERROR_MESSAGE();
    THROW;

END CATCH;