BEGIN TRY
	BEGIN TRANSACTION
	
	UPDATE DefaultValuesPerCountry SET CultureInfo = 'es-SV' WHERE IdCountry = 'SV'
	
	COMMIT TRANSACTION;
	SELECT 'DATOS ACTUALIZADOS CORRECTAMENTE' AS MESSAGE
END TRY
BEGIN CATCH
	ROLLBACK TRANSACTION
	SELECT @@ERROR,
		   ERROR_MESSAGE(),
		   ERROR_LINE()
END CATCH