-- SCRIP PARA ACTUALIZAR NUEVO CAMPO EN TABLA DE EJECUCIONES COD PARA DIFERENCIAR COD INMEDIATO DE COD ANTICIPADO
BEGIN TRY
    BEGIN TRANSACTION;
		
		ALTER TABLE DeliveryBackOffice.dbo.[CatCoDDailySchedule]
		ADD IsCodAnticipated INT;

		UPDATE DeliveryBackOffice.dbo.CatCodDailySchedule
		SET IsCodAnticipated = 0
	
	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
END CATCH
