BEGIN TRY
BEGIN TRANSACTION

    DECLARE @IdSegmentMetro         INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'MEH'), --14
            @IdSegmentLocal          INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'LOH'), --15
            @IdSegmentDepart         INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'DEH'), --16
            @IdSegmentRegional       INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'REH'), --17
            @IdSegmentForOlancho     INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FOH'), --18
            @IdSegmentEspecial       INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'ESH'), --19
            @IdSegmentNacional       INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'NAH'), --21
            @IdSegmentForIslas       INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FIH'), --20
            @IdSegmentForGracias     INT = (SELECT CrsId FROM DeliveryBackOffice.dbo.CatRateSegment WITH(NOLOCK) WHERE CrsShortName = 'FGH'); --33

    DECLARE @IdRate          INT = (SELECT RheId FROM DeliveryBackOffice.dbo.RateHeader WITH(NOLOCK) WHERE RheName ='Tarifario destinos express center' AND CountryId = 'HN'),
        @TypeServiceSTD  INT = (SELECT CtsId FROM DeliveryBackOffice.dbo.CatTypeService WITH(NOLOCK) WHERE CtsShortName = 'STD'), --5
        @TypeServiceCOD  INT = (SELECT CtsId FROM DeliveryBackOffice.dbo.CatTypeService WITH(NOLOCK) WHERE CtsShortName = 'COD'); --6

    DECLARE @IdPeq   INT = (SELECT AbcId FROM DeliveryBackOffice.dbo.ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Pequeño' and IdCountry = 'HN') AND Code = 'EXPHN076'),
        @IdMed   INT = (SELECT AbcId FROM DeliveryBackOffice.dbo.ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Mediano' and IdCountry = 'HN') AND Code ='EXPHN077'),
        @IdGrand INT = (SELECT AbcId FROM DeliveryBackOffice.dbo.ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Grande' and IdCountry = 'HN') AND Code ='EXPHN078'),
        @IdExt   INT = (SELECT AbcId FROM DeliveryBackOffice.dbo.ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Extra Grande' and IdCountry = 'HN') AND Code ='EXPHN079'),
        @IdSob   INT = (SELECT AbcId FROM DeliveryBackOffice.dbo.ArticleByCustomer WITH(NOLOCK) WHERE AbcIdArticle =(SELECT ArtId FROM CatArticle WITH(NOLOCK) WHERE ArtName = 'Paquete Sobredimensionado' and IdCountry = 'HN') AND Code ='EXPHN080');


    --*********************  ESTANDAR  *********************

    --INHABILITAR TARIFAS ANTIGUAS (ESTANDAR)
    UPDATE DeliveryBackOffice.dbo.RateData
    SET RowStatus = 0,
    TokenUpdated = 'SYS-TGARCIA',
    DateUpdated = GETDATE()
    WHERE RateId = @IdRate AND RowStatus = 1 AND TypeServiceId IS NOT NULL AND TypeServiceId = @TypeServiceSTD;

    --COBERTURA METRO
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdExt,98,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentMetro,NULL,NULL,@IdSob,107,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA LOCAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdExt,110,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentLocal,NULL,NULL,@IdSob,118,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA DEPARTAMENTAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdExt,121,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentDepart,NULL,NULL,@IdSob,129,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA REGIONAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdExt,132,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentRegional,NULL,NULL,@IdSob,140,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA NACIONAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdExt,151,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentNacional,NULL,NULL,@IdSob,159,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA FORANEA OLANCHO
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdExt,192,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForOlancho,NULL,NULL,@IdSob,200,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA ESPECIAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdExt,252,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentEspecial,NULL,NULL,@IdSob,260,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA FORANEA ISLAS
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdExt,327,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForIslas,NULL,NULL,@IdSob,335,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA FORANEA GRACIAS A DIOS
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdPeq,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdMed,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdGrand,85,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdExt,395,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceSTD,@IdSegmentForGracias,NULL,NULL,@IdSob,403,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


    --*********************  COD  *********************

    --INHABILITAR TARIFAS ANTIGUAS (COD)
    UPDATE DeliveryBackOffice.dbo.RateData
    SET RowStatus = 0,
    TokenUpdated = 'SYS-TGARCIA',
    DateUpdated = GETDATE()
    WHERE RateId = @IdRate AND RowStatus = 1 AND TypeServiceId IS NOT NULL AND TypeServiceId = @TypeServiceCOD;

    --COBERTURA METRO
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdPeq,49,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdMed,57,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdGrand,83,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdExt,91,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentMetro,NULL,NULL,@IdSob,99,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA LOCAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdPeq,60,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdMed,68,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdGrand,94,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdExt,102,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentLocal,NULL,NULL,@IdSob,110,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA DEPARTAMENTAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdPeq,71,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdMed,80,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdGrand,105,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdExt,113,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentDepart,NULL,NULL,@IdSob,122,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA REGIONAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdPeq,83,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdMed,91,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdGrand,116,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdExt,125,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentRegional,NULL,NULL,@IdSob,133,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA NACIONAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdPeq,101,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdMed,110,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdGrand,135,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdExt,143,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentNacional,NULL,NULL,@IdSob,152,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA FORANEA OLANCHO
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdPeq,143,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdMed,151,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdGrand,176,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdExt,185,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForOlancho,NULL,NULL,@IdSob,193,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA ESPECIAL
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdPeq,203,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdMed,211,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdGrand,236,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdExt,245,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentEspecial,NULL,NULL,@IdSob,253,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA FORANEA ISLAS
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdPeq,278,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdMed,286,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdGrand,311,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdExt,320,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForIslas,NULL,NULL,@IdSob,328,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

    --COBERTURA FORANEA GRACIAS A DIOS
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdPeq,353,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdMed,360,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdGrand,375,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdExt,383,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
    INSERT INTO DeliveryBackOffice.dbo.RateData (RateId,TypeServiceId,TypeSegmentId,HubSourceId,HubDestinyId,ArticleId,RateValue,RowStatus,TokenCreated,DateCreated,TokenUpdated,DateUpdated,LimitHourDelivery,LimitHourPickup,WeightFrom,WeightTo,PackagesFrom,PackagesTo) VALUES ( @IdRate,@TypeServiceCOD,@IdSegmentForGracias,NULL,NULL,@IdSob,390,1,'SYS-TGARCIA',GETDATE(),NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


    COMMIT TRANSACTION
    PRINT 'Actualización realizada correctamente.'
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION

    PRINT 'Ocurrió un error al ejecutar la actualización.'
    PRINT ERROR_MESSAGE()
END CATCH
