CREATE TYPE dbo.TblDeposit AS TABLE
	(
		[TransactionNumber]       BIGINT          PRIMARY KEY,
		[TransactionDate]         DATETIME        NOT NULL,
		[TransactionCode]         INT             NOT NULL,
		[Reference]               NVARCHAR(15)    NOT NULL,
		[Amount]                  DECIMAL(19,4)   NOT NULL,
		[Balance]                 DECIMAL(19,4)   NOT NULL,
		[UserIdDeposit]           NVARCHAR(50)    NOT NULL,
		[UserNameDeposit]         NVARCHAR(50)    NOT NULL,
		[UserNickNameDeposit]     NVARCHAR(50)    NOT NULL,
		[UserDocumentNumber]      NVARCHAR(20)    NOT NULL,
		[CurrencyISO]             NVARCHAR(10)    NOT NULL,
		[CurrencyIdExternal]      INT             NOT NULL,
		[ClientIdExternal]        BIGINT          NOT NULL,
		[ClientCardCode]          NVARCHAR(15)    NOT NULL,
		[ClientNameExternal]      NVARCHAR(500)   NOT NULL,
		[VisitPointIdExternal]    BIGINT          NOT NULL,
		[VisitPointName]          NVARCHAR(100)   NOT NULL,
		[BankIdExternal]          INT             NOT NULL,
		[BankCardCode]            NVARCHAR(50)    NOT NULL,
		[BankNameExternal]        NVARCHAR(50)    NOT NULL,
		[BankAccountNumber]       NVARCHAR(50)    NOT NULL,
		[BankAccountIsMak]        BIT             NOT NULL,
		[BankAccountIsIBAN]		  BIT             NOT NULL,
		[BankAccountIsSWIFT]      BIT             NOT NULL,
		[TerminalId]              INT             NOT NULL,
		[TerminalSerie]           NVARCHAR(50)    NOT NULL
	);