CREATE TYPE [dbo].[TblDeliveryOrdersFD2] AS TABLE (
    [RowNumber]                            INT             NOT NULL,
    [Ticket_Number]                        NVARCHAR (150)  NULL,
    [Order_Number]                         INT             NULL,
    [Preparation_Date]                     DATETIME        NULL,
    [Shipping_Date]                        DATETIME        NULL,
    [Pieces_Dry]                           INT             NULL,
    [Pieces_Cold]                          INT             NULL,
    [Consolidated_Number]                  INT             NULL,
    [Recipe_Number]                        NVARCHAR (1000) NULL,
    [Sender_ID]                            INT             NULL,
    [Sender_FirstName]                     NVARCHAR (100)  NULL,
    [Sender_LastName]                      NVARCHAR (100)  NULL,
    [Sender_Address]                       NVARCHAR (200)  NULL,
    [Sender_Zone]                          NVARCHAR (100)  NULL,
    [Sender_Town]                          NVARCHAR (100)  NULL,
    [Sender_Department]                    NVARCHAR (100)  NULL,
    [Sender_Phone]                         NVARCHAR (50)   NULL,
    [Sender_Lat]                           VARCHAR (50)    NULL,
    [Sender_Lng]                           VARCHAR (50)    NULL,
    [Receiver_ID]                          INT             NULL,
    [Receiver_FirstName]                   NVARCHAR (100)  NULL,
    [Receiver_LastName]                    NVARCHAR (100)  NULL,
    [Receiver_Address]                     NVARCHAR (600)  NULL,
    [Receiver_Zone]                        NVARCHAR (100)  NULL,
    [Receiver_Town]                        NVARCHAR (100)  NULL,
    [Receiver_Department]                  NVARCHAR (100)  NULL,
    [Receiver_Phone]                       NVARCHAR (100)  NULL,
    [Receiver_Email]                       NVARCHAR (200)  NULL,
    [Receiver_SocialSecurity_ID]           NVARCHAR (200)  NULL,
    [Receiver_Alternant_ID]                INT             NULL,
    [Receiver_Alternant_FullName]          NVARCHAR (200)  NULL,
    [Receiver_Alternant_Address]           NVARCHAR (200)  NULL,
    [Receiver_Alternant_Zone]              NVARCHAR (100)  NULL,
    [Receiver_Alternant_Town]              NVARCHAR (100)  NULL,
    [Receiver_Alternant_Department]        NVARCHAR (100)  NULL,
    [Receiver_Alternant_Phone]             NVARCHAR (100)  NULL,
    [Receiver_Alternant_Email]             NVARCHAR (200)  NULL,
    [Receiver_Alternant_SocialSecurity_ID] NVARCHAR (200)  NULL,
    [Delivery_Max_Date]                    DATETIME        NULL,
    [printedStatus]                        TINYINT         NULL,
    [StatusOrderId]                        TINYINT         NOT NULL,
    [Receiver_CUI]                         NVARCHAR (25)   NULL,
    [Package_Description]                  NVARCHAR (200)  NULL,
    [Sender_Internal_Code]                 NVARCHAR (50)   NULL,
    [Receiver_Alternant_CUI]               NVARCHAR (25)   NULL,
    [Collect_OnDelivery]                   DECIMAL (14, 2) NULL,
    [IsCollect]                            BIT             NULL,
    [PriceShippment]                       DECIMAL (14, 2) NULL,
    [SenderIdTownship]                     INT             NULL,
    [ReceiverIdTownship]                   INT             NULL);

