CREATE TYPE [dbo].[TblPackagesRange] AS TABLE (
    [IdPackatesRange]      INT             NULL,
    [Range]                NVARCHAR (50)   NULL,
    [Discount]             DECIMAL (18, 2) NULL,
    [Order]                INT             NULL,
    [Local]                DECIMAL (18, 2) NULL,
    [Metro]                DECIMAL (18, 2) NULL,
    [Foraneo]              DECIMAL (18, 2) NULL,
    [Especial]             DECIMAL (18, 2) NULL,
    [LocalCOD]             DECIMAL (18, 2) NULL,
    [MetroCOD]             DECIMAL (18, 2) NULL,
    [ForaneoCOD]           DECIMAL (18, 2) NULL,
    [EspecialCOD]          DECIMAL (18, 2) NULL,
    [IsPercent]            BIT             NULL,
    [Status]               INT             NULL,
    [WeightLimit]          DECIMAL (12, 2) NULL,
    [AdditionalWeightRate] DECIMAL (12, 2) NULL,
    [InsuranceRate]        DECIMAL (12, 2) NULL,
    [InsuranceExempt]      DECIMAL (12, 2) NULL,
    [CreditCardRate]       DECIMAL (12, 2) NULL,
    [ReturnRate]           DECIMAL (12, 2) NULL,
    [FragilRate]           DECIMAL (12, 2) NULL,
    [CollectRate]          DECIMAL (12, 2) NULL,
    [Attempt]              DECIMAL (12, 2) NULL,
    [PiecesIncluded]       DECIMAL (12, 2) NULL,
    [numCODLoc]            DECIMAL (12, 2) NULL,
    [numCODMet]            DECIMAL (12, 2) NULL,
    [numCODFor]            DECIMAL (12, 2) NULL,
    [numCODEsp]            DECIMAL (12, 2) NULL,
    [numCODExcentLoc]      DECIMAL (12, 2) NULL,
    [numCODExcentMet]      DECIMAL (12, 2) NULL,
    [numCODExcentFor]      DECIMAL (12, 2) NULL,
    [numCODExcentEsp]      DECIMAL (12, 2) NULL,
    [IdCountry]            NVARCHAR(2)     NULL,
    [IdCurrency]           INT             NULL,
	[Description]          NVARCHAR(100)   NULL);

