CREATE TYPE [dbo].[TblServiceRoutes] AS TABLE (
    [IdTblServiceRoutes]     INT             NOT NULL,
    [Ticket_Number]          NVARCHAR (150)  NULL,
    [OriginCode]             INT             NULL,
    [HeaderCodeTownship]     VARCHAR (10)    NULL,
    [name]                   NVARCHAR (100)  NULL,
    [phone]                  NVARCHAR (100)  NULL,
    [contact]                NVARCHAR (100)  NULL,
    [email]                  NVARCHAR (200)  NULL,
    [address1]               NVARCHAR (600)  NULL,
    [Latitude]               VARCHAR (50)    NULL,
    [Longitude]              VARCHAR (50)    NULL,
    [Accuracy]               VARCHAR (50)    NULL,
    [CountPieces]            INT             NULL,
    [TotalWeight]            DECIMAL (18, 2) NULL,
    [TotalValue]             DECIMAL (18, 2) NULL,
    [Currency]               VARCHAR (20)    NULL,
    [IsInsuarance]           BIT             NULL,
    [ProductInsuranceAmount] DECIMAL (18, 2) NULL,
    [InsuranceCurrency]      NVARCHAR (10)   NULL,
    [TypeService]            VARCHAR (4)     NULL,
    [Username]               NVARCHAR (100)  NULL,
    [CashOnDelivery]         BIT             NULL,
    [AmmountCashOnDelivery]  DECIMAL (18, 2) NULL,
    [CashOnDeliveryCurrency] VARCHAR (20)    NULL,
    PRIMARY KEY CLUSTERED ([IdTblServiceRoutes] ASC));

