/***
-- INSERCION DE VALORES DEL_PARAMETROSFACTURA
-- PARA FACTURACIÓN EN EL SALVADOR
***/

BEGIN TRANSACTION;
BEGIN TRY

UPDATE del_parametrosFactura SET dpf_VpCodeOfReference = 1378846 WHERE dpf_VpCodeOfReference =  1160901

    COMMIT TRANSACTION;

END TRY
BEGIN CATCH

    ROLLBACK TRANSACTION;

    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();

    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);

END CATCH