-- Iniciar transacción
BEGIN TRANSACTION

BEGIN TRY

INSERT INTO CatEconomicActivityBySV VALUES
('01111', 'Cultivo de cereales excepto arroz y para forrajes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01112', 'Cultivo de legumbres ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01113', 'Cultivo de semillas oleaginosas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01114', 'Cultivo de plantas para la preparación de semillas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01119', 'Cultivo de otros cereales excepto arroz y forrajeros n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01120', 'Cultivo de arroz ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01131', 'Cultivo de raíces y tubérculos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01132', 'Cultivo de brotes, bulbos, vegetales tubérculos y cultivos similares ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01133', 'Cultivo hortícola de fruto ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01134', 'Cultivo de hortalizas de hoja y otras hortalizas ncp ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01140', 'Cultivo de caña de azúcar ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01150', 'Cultivo de tabaco ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01160', 'Cultivo de plantas textiles ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01191', 'Cultivo de flores y capullos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01192', 'Cultivo de plantas para la preparación de especias ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01193', 'Cultivo de plantas aromáticas y medicinales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01199', 'Cultivo de otros productos agrícolas n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01210', 'Cultivo de uva ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01220', 'Cultivo de frutas tropicales y subtropicales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01230', 'Cultivo de frutas cítricas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01240', 'Cultivo de frutas con hueso/carozo y pepita ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01250', 'Cultivo de otras frutas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01260', 'Cultivo de palma de aceite ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01270', 'Cultivo de plantas utilizadas principalmente en perfumería, farmacia o para usos insecticidas, fungicidas o similares ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01280', 'Cultivo de especias, plantas aromáticas y medicinales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01290', 'Cultivo de frutos de cáscara ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01300', 'Cultivo de plantas de vivero excepto para usos forestales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01410', 'Cría de ganado bovino y bufalino ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01420', 'Cría de ganado ovino y caprino ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01430', 'Cría de ganado porcino ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01440', 'Cría de aves de corral ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01450', 'Cría de camélidos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01460', 'Cría de caballos, asnos, mulos y burdéganos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01490', 'Cría de otros animales n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01500', 'Producción agrícola combinada con la producción ganadera ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01610', 'Actividades de apoyo a la agricultura ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01620', 'Actividades de apoyo a la ganadería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01630', 'Actividades de preparación de productos agrícolas para el mercado primario ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01640', 'Procesamiento posterior de productos agrícolas para el mercado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('01700', 'Caza y servicios conexos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('02100', 'Silvicultura y otras actividades forestales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('02200', 'Extracción de madera ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('02300', 'Recolección de productos forestales no madereros ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('02400', 'Servicios de apoyo a la silvicultura ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('03110', 'Pesca marítima ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('03120', 'Pesca de agua dulce ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('03210', 'Acuicultura marina ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('03220', 'Acuicultura de agua dulce ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('05100', 'Extracción de hulla (carbón de piedra)',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('05200', 'Extracción de lignito ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('06100', 'Extracción de petróleo crudo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('06200', 'Extracción de gas natural ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('07100', 'Extracción de minerales de hierro ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('07210', 'Extracción de minerales de uranio y torio ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('07290', 'Extracción de otros minerales metalíferos no ferrosos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08101', 'Extracción de piedra caliza y yeso ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08102', 'Extracción de arena, arcilla y caolín ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08103', 'Extracción de pizarra ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08104', 'Extracción de grava ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08109', 'Extracción de otros minerales no metálicos y de cantera n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08910', 'Extracción de minerales para la fabricación de abonos y productos químicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08920', 'Extracción de turba ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08930', 'Extracción de sal ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('08990', 'Extracción de otros minerales no metálicos n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('09100', 'Actividades de apoyo para la extracción de petróleo y gas natural ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('09900', 'Actividades de apoyo para otras explotaciones de minas y canteras ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10100', 'Procesamiento y conservación de carne ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10200', 'Procesamiento y conservación de pescado, crustáceos y moluscos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10300', 'Procesamiento y conservación de frutas y hortalizas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10400', 'Fabricación de aceites y grasas de origen vegetal y animal ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10500', 'Elaboración de productos lácteos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10610', 'Fabricación de productos de molinería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10620', 'Fabricación de almidones y productos derivados del almidón ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10710', 'Fabricación de productos de panadería, galletas y pastas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10720', 'Fabricación de azúcar ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10730', 'Fabricación de cacao, chocolate y productos de confitería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10740', 'Fabricación de fideos, macarrones, y productos de pasta similares ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10750', 'Fabricación de comidas preparadas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10790', 'Fabricación de otros productos alimenticios n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10810', 'Fabricación de alimentos para animales de granja ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10890', 'Fabricación de otros alimentos preparados para animales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('11010', 'Destilación, rectificación y mezcla de bebidas alcohólicas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('11020', 'Fabricación de vinos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('11030', 'Fabricación de sidra y otras bebidas fermentadas no destiladas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('11040', 'Fabricación de cerveza ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('11050', 'Fabricación de maltas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('11060', 'Elaboración de bebidas no alcohólicas; producción de aguas minerales y otras aguas embotelladas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('12000', 'Fabricación de productos de tabaco ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13110', 'Preparación e hilado de fibras textiles ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13120', 'Fabricación de tejidos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13130', 'Acabado de productos textiles ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13910', 'Fabricación de tejidos de punto y ganchillo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13920', 'Fabricación de artículos confeccionados de materiales textiles, excepto prendas de vestir ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13930', 'Fabricación de tapices y alfombras ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13940', 'Fabricación de cuerdas, cordeles, bramantes y redes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('13990', 'Fabricación de otros productos textiles n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('14100', 'Fabricación de prendas de vestir, excepto prendas de piel ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('14200', 'Fabricación de artículos de piel ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('14300', 'Fabricación de prendas de vestir de punto y ganchillo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('15110', 'Curtido y adobo de cueros; preparación y teñido de pieles ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('15120', 'Fabricación de artículos de viaje, bolsos de mano y artículos similares, y artículos de talabartería y guarnicionería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('15200', 'Fabricación de calzado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('16100', 'Aserrado y cepillado de madera ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('16210', 'Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('16220', 'Fabricación de partes y piezas de carpintería para edificios y construcciones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('16230', 'Fabricación de recipientes de madera ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('16290', 'Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('17000', 'Fabricación de papel y productos de papel ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('18110', 'Impresión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('18120', 'Servicios relacionados con la impresión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('18200', 'Reproducción de grabaciones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('19100', 'Fabricación de productos de hornos de coque ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('19200', 'Fabricación de productos de la refinación del petróleo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20110', 'Fabricación de gases industriales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20120', 'Fabricación de colorantes y pigmentos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20130', 'Fabricación de otros productos químicos básicos orgánicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20140', 'Fabricación de abonos y compuestos de nitrógeno ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20210', 'Fabricación de plaguicidas y otros productos químicos de uso agropecuario ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20220', 'Fabricación de pinturas, barnices y revestimientos similares; tintas de imprenta y masillas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20230', 'Fabricación de jabones, detergentes y otros artículos de tocador y limpieza ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20290', 'Fabricación de otros productos químicos n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('20300', 'Fabricación de fibras artificiales y sintéticas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('21000', 'Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('22110', 'Fabricación de neumáticos y cámaras de caucho; recauchutado y reconstrucción de neumáticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('22190', 'Fabricación de otros productos de caucho ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('22200', 'Fabricación de productos de plástico ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23100', 'Fabricación de vidrio y productos de vidrio ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23910', 'Fabricación de productos de cerámica no refractaria para uso no estructural ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23920', 'Fabricación de productos de cerámica refractaria ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23930', 'Fabricación de productos de arcilla y cerámica para la construcción ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23940', 'Fabricación de cemento, cal y yeso ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23950', 'Fabricación de artículos de hormigón, cemento y yeso ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23960', 'Corte, tallado y acabado de la piedra ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('23990', 'Fabricación de otros productos minerales no metálicos n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('24100', 'Fabricación de productos de hierro y acero ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('24200', 'Fabricación de productos de metales preciosos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('24310', 'Fundición de hierro y acero ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('24320', 'Fundición de metales no ferrosos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25110', 'Fabricación de estructuras metálicas y sus partes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25120', 'Fabricación de tanques, depósitos y recipientes de metal ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25130', 'Fabricación de generadores de vapor, excepto calderas para calefacción central ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25200', 'Fabricación de armas y municiones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25910', 'Forjado, prensado, estampado y laminado de metales; pulvimetalurgia ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25920', 'Tratamiento y revestimiento de metales; maquinado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25930', 'Fabricación de artículos de cuchillería, herramientas y ferretería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('25990', 'Fabricación de otros productos elaborados de metal n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26100', 'Fabricación de componentes electrónicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26200', 'Fabricación de computadoras y equipo periférico ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26300', 'Fabricación de equipos de comunicaciones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26400', 'Fabricación de aparatos electrónicos de consumo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26510', 'Fabricación de equipos de medición, prueba y navegación ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26520', 'Fabricación de relojes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26600', 'Fabricación de equipos de irradiación y electromédicos y equipos electroterapéuticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26700', 'Fabricación de equipo óptico y equipo fotográfico ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('26800', 'Fabricación de soportes magnéticos y ópticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27100', 'Fabricación de motores, generadores y transformadores eléctricos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27200', 'Fabricación de pilas y baterías ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27310', 'Fabricación de cables de fibra óptica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27320', 'Fabricación de otros hilos y cables electrónicos y eléctricos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27330', 'Fabricación de dispositivos de cableado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27400', 'Fabricación de equipos de iluminación eléctrica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27500', 'Fabricación de aparatos de uso doméstico ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('27900', 'Fabricación de otros equipos eléctricos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28110', 'Fabricación de motores y turbinas, excepto para aeronaves, vehículos automotores y motocicletas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28120', 'Fabricación de bombas, compresores, grifos y válvulas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28130', 'Fabricación de cojinetes, engranajes, trenes de engranajes y elementos de accionamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28140', 'Fabricación de hornos, quemadores y estufas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28150', 'Fabricación de equipo de elevación y manipulación ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28160', 'Fabricación de maquinaria de oficina ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28170', 'Fabricación de aparatos de aire acondicionado, refrigeración no doméstica y ventilación ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28180', 'Fabricación de maquinaria para la preparación de alimentos y bebidas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28190', 'Fabricación de otra maquinaria de uso general n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28210', 'Fabricación de maquinaria agrícola y forestal ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28220', 'Fabricación de máquinas herramienta ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28230', 'Fabricación de maquinaria metalúrgica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28240', 'Fabricación de maquinaria para la explotación de minas y canteras y para la construcción ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28250', 'Fabricación de maquinaria para la elaboración de alimentos, bebidas y tabaco ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28260', 'Fabricación de maquinaria para la elaboración de productos textiles, prendas de vestir y cueros ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('28290', 'Fabricación de otra maquinaria de uso especial n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('29100', 'Fabricación de vehículos automotores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('29200', 'Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('29300', 'Fabricación de partes, piezas y accesorios para vehículos automotores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30110', 'Construcción de buques y estructuras flotantes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30120', 'Construcción de embarcaciones de recreo y deporte ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30200', 'Fabricación de locomotoras y material rodante ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30300', 'Fabricación de aeronaves y naves espaciales y de maquinaria conexa ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30400', 'Fabricación de vehículos militares de combate ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30910', 'Fabricación de motocicletas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30920', 'Fabricación de bicicletas y de sillones de ruedas para inválidos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('30990', 'Fabricación de otro equipo de transporte n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('31000', 'Fabricación de muebles ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('32100', 'Fabricación de joyas, bisutería y artículos conexos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('32200', 'Fabricación de instrumentos musicales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('32300', 'Fabricación de artículos de deporte ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('32400', 'Fabricación de juegos y juguetes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('32500', 'Fabricación de instrumentos y aparatos médicos y odontológicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('32900', 'Otras industrias manufactureras n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('33110', 'Reparación de productos elaborados de metal ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('33120', 'Reparación de maquinaria ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('33130', 'Reparación de equipos electrónicos y ópticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('33140', 'Reparación de equipos eléctricos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('33150', 'Reparación y mantenimiento de buques y estructuras flotantes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('33190', 'Reparación de otros equipos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('33200', 'Instalación de maquinaria y equipo industrial ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('35100', 'Generación, transmisión, distribución y comercialización de energía eléctrica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('35200', 'Producción de gas; distribución de combustibles gaseosos por tuberías ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('35300', 'Suministro de vapor y aire acondicionado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('36000', 'Captación, tratamiento y distribución de agua ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('37000', 'Evacuación de aguas residuales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('38110', 'Recolección de residuos no peligrosos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('38120', 'Recolección de residuos peligrosos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('38210', 'Tratamiento y eliminación de residuos no peligrosos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('38220', 'Tratamiento y eliminación de residuos peligrosos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('38300', 'Recuperación de materiales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('39000', 'Actividades de saneamiento ambiental y otros servicios de gestión de residuos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('41000', 'Construcción de edificios ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('42100', 'Construcción de carreteras y vías de ferrocarril ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('42200', 'Construcción de proyectos de servicio público ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('42900', 'Construcción de otras obras de ingeniería civil n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('43110', 'Demolición ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('43120', 'Preparación de terrenos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('43210', 'Instalaciones eléctricas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('43220', 'Instalaciones de fontanería, calefacción y aire acondicionado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('43290', 'Otras instalaciones para obras de construcción ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('43300', 'Terminación y acabado de edificios ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('43900', 'Otras actividades especializadas de construcción n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('45100', 'Venta de vehículos automotores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('45200', 'Mantenimiento y reparación de vehículos automotores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('45300', 'Venta de partes, piezas y accesorios para vehículos automotores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('45400', 'Venta de motocicletas y de sus partes, piezas y accesorios ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46100', 'Venta al por mayor en comisión o por contrata ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46200', 'Venta al por mayor de materias primas agropecuarias y de animales vivos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46300', 'Venta al por mayor de alimentos, bebidas y tabaco ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46410', 'Venta al por mayor de productos textiles, prendas de vestir y calzado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46490', 'Venta al por mayor de otros artículos de uso doméstico ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46510', 'Venta al por mayor de computadoras, equipos periféricos y programas informáticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46520', 'Venta al por mayor de equipo electrónico y de telecomunicaciones y sus partes y piezas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46530', 'Venta al por mayor de maquinaria, equipo y materiales agrícolas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46590', 'Venta al por mayor de otra maquinaria y equipo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46610', 'Venta al por mayor de combustibles sólidos, líquidos y gaseosos y productos conexos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46620', 'Venta al por mayor de metales y menas metálicas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46630', 'Venta al por mayor de materiales de construcción, artículos de ferretería y equipo y materiales de fontanería y calefacción ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46690', 'Venta al por mayor de otros productos n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('46900', 'Venta al por mayor no especializada ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47110', 'Venta al por menor en comercios no especializados con predominio de productos alimenticios, bebidas y tabaco ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47190', 'Venta al por menor en comercios no especializados, con predominio de productos no alimenticios ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47210', 'Venta al por menor de frutas y verduras en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47220', 'Venta al por menor de carne y productos cárnicos en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47230', 'Venta al por menor de pescado, crustáceos y moluscos en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47240', 'Venta al por menor de pan y productos de panadería, confitería y pastelería en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47250', 'Venta al por menor de bebidas en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47260', 'Venta al por menor de productos de tabaco en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47290', 'Venta al por menor de otros productos alimenticios en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47300', 'Venta al por menor de combustibles para vehículos automotores en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47410', 'Venta al por menor de computadoras, equipos periféricos, programas informáticos y equipos de telecomunicaciones en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47420', 'Venta al por menor de equipos de audio y vídeo en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47510', 'Venta al por menor de productos textiles en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47520', 'Venta al por menor de artículos de ferretería, pinturas y vidrio en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47530', 'Venta al por menor de alfombras, moquetas, revestimientos para paredes y pisos en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47540', 'Venta al por menor de aparatos electrodomésticos en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47590', 'Venta al por menor de muebles, aparatos de iluminación y otros artículos para el hogar en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47610', 'Venta al por menor de libros, periódicos y artículos de papelería en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47620', 'Venta al por menor de música y grabaciones de vídeo en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47630', 'Venta al por menor de equipo deportivo en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47640', 'Venta al por menor de juegos y juguetes en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47710', 'Venta al por menor de prendas de vestir en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47720', 'Venta al por menor de calzado y artículos de cuero en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47730', 'Venta al por menor de productos farmacéuticos y medicinales, artículos de tocador y cosméticos en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47740', 'Venta al por menor de otros productos nuevos en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47750', 'Venta al por menor de artículos usados en comercios ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47760', 'Venta al por menor de plantas y flores, alimentos para animales de compañía y animales de compañía en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47770', 'Venta al por menor de relojes y joyas en comercios especializados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47810', 'Venta al por menor de alimentos, bebidas y tabaco en puestos de venta y en mercados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47820', 'Venta al por menor de productos textiles, prendas de vestir y calzado en puestos de venta y en mercados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47890', 'Venta al por menor de otros productos en puestos de venta y en mercados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47910', 'Venta al por menor a través de empresas de venta por correo o a través de Internet ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('47990', 'Otras ventas al por menor no realizadas en comercios, puestos de venta ni en mercados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('49110', 'Transporte de pasajeros por vía férrea ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('49120', 'Transporte de carga por vía férrea ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('49210', 'Transporte de pasajeros por carretera ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('49220', 'Transporte de carga por carretera ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('49300', 'Transporte por tuberías ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('50110', 'Transporte de pasajeros marítimo y de cabotaje ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('50120', 'Transporte de carga marítimo y de cabotaje ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('50210', 'Transporte de pasajeros por vías de navegación interiores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('50220', 'Transporte de carga por vías de navegación interiores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('51100', 'Transporte de pasajeros por vía aérea ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('51200', 'Transporte de carga por vía aérea ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('52100', 'Almacenamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('52210', 'Actividades de servicios relacionadas con el transporte terrestre ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('52220', 'Actividades de servicios relacionadas con el transporte acuático ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('52230', 'Actividades de servicios relacionadas con el transporte aéreo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('52240', 'Actividades de manipulación de la carga ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('52290', 'Otras actividades de apoyo al transporte ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('53100', 'Actividades postales nacionales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('53200', 'Actividades de mensajería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('55100', 'Servicios de alojamiento, excepto los de apartamentos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('55200', 'Campamentos y parques de vehículos recreacionales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('55900', 'Otros tipos de alojamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('56100', 'Actividades de restaurantes y de servicio móvil de comidas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('56210', 'Suministro de comidas por encargo (catering)',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('56290', 'Otras actividades de servicio de comidas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('56300', 'Actividades de bares y cantinas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('58110', 'Edición de libros ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('58120', 'Edición de periódicos, revistas y publicaciones periódicas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('58130', 'Edición de software ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('58190', 'Otras actividades de edición ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('58200', 'Actividades de edición de programas informáticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('59110', 'Producción de películas cinematográficas, vídeos y programas de televisión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('59120', 'Actividades de postproducción de películas cinematográficas, vídeos y programas de televisión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('59130', 'Distribución de películas cinematográficas, vídeos y programas de televisión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('59140', 'Actividades de exhibición de películas cinematográficas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('59200', 'Actividades de grabación de sonido y edición de música ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('60100', 'Actividades de radiodifusión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('60200', 'Actividades de programación y transmisión de televisión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('61100', 'Actividades de telecomunicaciones por cable ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('61200', 'Actividades de telecomunicaciones inalámbricas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('61300', 'Actividades de telecomunicaciones satelitales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('61900', 'Otras actividades de telecomunicaciones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('62010', 'Actividades de programación informática ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('62020', 'Actividades de consultoría de informática y de gestión de instalaciones informáticas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('62090', 'Otras actividades de tecnología de la información y servicios de computadoras ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('63110', 'Procesamiento de datos, alojamiento y actividades relacionadas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('63120', 'Portales web ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('63910', 'Actividades de agencias de noticias ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('63990', 'Otras actividades de servicios de información n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('64110', 'Banca central ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('64190', 'Intermediación monetaria de otros bancos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('64200', 'Actividades de sociedades de cartera (holdings)',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('64300', 'Fondos y sociedades de inversión y entidades financieras similares ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('64910', 'Arrendamiento financiero ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('64920', 'Otras actividades de crédito ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('64990', 'Otros tipos de intermediación financiera n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('65110', 'Seguros de vida ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('65120', 'Seguros generales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('65200', 'Reaseguros ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('65300', 'Fondos de pensiones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('66110', 'Administración de mercados financieros ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('66120', 'Actividades de las bolsas de valores y de productos básicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('66190', 'Otras actividades de servicios financieros, excepto seguros y fondos de pensiones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('66210', 'Actividades de evaluación de riesgos y daños ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('66220', 'Actividades de agentes y corredores de seguros ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('66290', 'Otras actividades de servicios auxiliares de los seguros y los fondos de pensiones ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('66300', 'Actividades de gestión de fondos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('68100', 'Actividades inmobiliarias realizadas con bienes propios o arrendados ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('68200', 'Actividades inmobiliarias realizadas a cambio de una retribución o por contrata ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('69100', 'Actividades jurídicas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('69200', 'Actividades de contabilidad, teneduría de libros y auditoría; asesoramiento fiscal ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('70100', 'Actividades de las oficinas principales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('70200', 'Actividades de consultoría de gestión ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('71100', 'Servicios de arquitectura e ingeniería y actividades conexas de consultoría técnica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('71200', 'Ensayos y análisis técnicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('72100', 'Investigaciones y desarrollo experimental en ciencias naturales y de la ingeniería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('72200', 'Investigaciones y desarrollo experimental en ciencias sociales y humanidades ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('73100', 'Publicidad ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('73200', 'Estudios de mercado y realización de encuestas de opinión pública ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('74100', 'Actividades de diseño especializado ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('74200', 'Actividades de fotografía ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('74900', 'Otras actividades profesionales, científicas y técnicas n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('75000', 'Actividades veterinarias ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('77100', 'Alquiler y arrendamiento de vehículos automotores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('77210', 'Alquiler de artículos deportivos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('77220', 'Alquiler de videocasetes y discos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('77290', 'Alquiler de otros efectos personales y enseres domésticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('77300', 'Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('77400', 'Arrendamiento de propiedad intelectual y productos similares, excepto obras con derechos de autor ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('78100', 'Actividades de agencias de empleo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('78200', 'Actividades de las empresas de trabajo temporal ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('78300', 'Otras actividades de suministro de recursos humanos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('79110', 'Actividades de agencias de viajes ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('79120', 'Actividades de operadores turísticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('79900', 'Otros servicios de reservas y actividades relacionadas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('80100', 'Actividades de seguridad privada ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('80200', 'Actividades de servicios de sistemas de seguridad ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('80300', 'Actividades de investigación ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('81100', 'Servicios combinados de apoyo a edificios ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('81210', 'Limpieza general de edificios ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('81290', 'Otras actividades de limpieza de edificios e instalaciones industriales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('81300', 'Actividades de paisajismo y mantenimiento de jardines ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('82110', 'Actividades de servicios administrativos combinados de oficina ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('82190', 'Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo de oficina ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('82200', 'Actividades de centros de llamadas (call centers)',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('82300', 'Organización de convenciones y exposiciones comerciales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('82910', 'Actividades de agencias de cobro y oficinas de crédito ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('82920', 'Actividades de empaque y embalaje ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('82990', 'Otras actividades de apoyo a las empresas n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84111', 'Actividades de la administración pública en general ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84112', 'Actividades de la administración pública de servicios económicos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84113', 'Actividades de la administración pública de servicios sociales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84114', 'Actividades de la administración pública de servicios culturales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84120', 'Regulación de las actividades de organismos que prestan servicios de salud, educación, cultura y otros servicios sociales, excepto seguridad social ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84130', 'Regulación y facilitación de la actividad económica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84210', 'Asuntos exteriores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84220', 'Actividades de defensa ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84230', 'Actividades de orden público y seguridad ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('84300', 'Seguridad social obligatoria ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85100', 'Educación preprimaria ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85210', 'Educación primaria ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85220', 'Educación secundaria básica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85230', 'Educación secundaria diversificada ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85300', 'Educación superior ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85410', 'Educación técnica y profesional ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85420', 'Educación para adultos y otros tipos de educación n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('85500', 'Apoyo a la educación ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('86100', 'Actividades de hospitales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('86200', 'Actividades de práctica médica y odontológica ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('86900', 'Otras actividades de atención de la salud humana ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('87100', 'Actividades de atención en hogares de ancianos con alojamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('87200', 'Actividades de atención de la salud mental y por consumo de estupefacientes y bebidas alcohólicas con alojamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('87300', 'Actividades de atención a personas con discapacidad intelectual, trastornos del desarrollo y enfermedades mentales con alojamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('87900', 'Otras actividades de atención de la salud con alojamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('88100', 'Actividades de asistencia social sin alojamiento para personas mayores y con discapacidad ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('88900', 'Otras actividades de asistencia social sin alojamiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('90000', 'Actividades creativas, artísticas y de entretenimiento ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('91010', 'Actividades de bibliotecas y archivos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('91020', 'Actividades de museos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('91030', 'Actividades de jardines botánicos y zoológicos y reservas naturales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('91040', 'Actividades de lugares históricos y edificios similares y de sitios de interés ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('92000', 'Actividades de juegos de azar y apuestas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('93110', 'Gestión de instalaciones deportivas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('93120', 'Actividades de clubes deportivos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('93190', 'Otras actividades deportivas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('93210', 'Actividades de parques de atracciones y parques temáticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('93290', 'Otras actividades recreativas y de esparcimiento n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('94110', 'Actividades de asociaciones empresariales y de empleadores ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('94120', 'Actividades de asociaciones profesionales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('94200', 'Actividades de sindicatos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('94910', 'Actividades de asociaciones religiosas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('94920', 'Actividades de asociaciones políticas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('94990', 'Actividades de otras asociaciones n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('95110', 'Reparación de computadoras y equipos periféricos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('95120', 'Reparación de equipos de comunicación ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('95210', 'Reparación de aparatos electrónicos de consumo ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('95220', 'Reparación de aparatos de uso doméstico y equipo doméstico y de jardinería ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('95230', 'Reparación de calzado y artículos de cuero ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('95240', 'Reparación de muebles y equipos del hogar ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('95290', 'Reparación de otros efectos personales y enseres domésticos ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('96010', 'Lavado y limpieza de prendas de tela y de piel, incluso la limpieza en seco ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('96020', 'Peluquería y otros tratamientos de belleza ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('96030', 'Pompas fúnebres y actividades conexas ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('96091', 'Servicios de sauna y otros servicios para la estética corporal n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('96092', 'Servicios n.c.p. ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('97000', 'Actividad de los hogares en calidad de empleadores de personal doméstico ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('98100', 'Actividades indiferenciadas de producción de bienes de los hogares privados para uso propio ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('98200', 'Actividades indiferenciadas de producción de servicios de los hogares privados para uso propio  ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('99000', 'Actividades de organizaciones y órganos extraterritoriales ',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10001', 'Empleados',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL),
('10002', 'Pensionado',1,'SYS-BPEDROZA',GETDATE(),NULL,NULL);


	COMMIT TRANSACTION
	print 'Inserción exitosa'

END TRY
BEGIN CATCH
	-- Revertir transacción en caso de error
	IF @@TRANCOUNT > 0
		ROLLBACK TRANSACTION
    
	-- Capturar información del error
	SELECT ERROR_MESSAGE(),
			ERROR_SEVERITY(),
			ERROR_STATE()

END CATCH