-- SCRIP PARA INSERTAR NUEVA COLUMNA DE MANEJO DE TIPOS DE CLIENTES EN CARRUSEL DE IMAGENES
BEGIN TRY
    BEGIN TRANSACTION;
		UPDATE DeliveryBackOffice.dbo.MovilAppCarouselImage
		SET IdTypeAccount = (SELECT TacIdTypeAccount FROM DeliveryBackOffice.dbo.CatTypeAccount WHERE TacName = 'Individual')
	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
END CATCH