-- MODIFICACION EN TABLA RegisterUser PARA CODIGO DE VERIFICACION
BEGIN TRY
    BEGIN TRANSACTION;
		ALTER TABLE [DeliveryBackOffice].[dbo].[RegisterUser]
		ADD UsrCodeVerif varchar(100);
	COMMIT TRANSACTION 
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0 ROLLBACK TRANSACTION;
END�CATCH