--screjecutado 8
INSERT INTO [dbo].[Customer]
           ([Name]
           ,[Description]
           ,[Domain]
           ,[RegexSubject]
           ,[RegexEmail]
           ,[RegexFilename]
           ,[Abbreviation]
           ,[IdCustomerType]
           ,[ConditionOfPaymentID]
           ,[CountryID]
           ,[CommercialName]
           ,[CustomerPhone]
           ,[WebsiteURI]
           ,[ContactName]
           ,[ContactEmail]
           ,[NotificationAddress]
           ,[SaleAdvisorID]
           ,[DateUpService]
           ,[DateDownService]
           ,[TypeOfBusinessID]
           ,[BusinessSegmentID]
           ,[BusinessActivityID]
           ,[CommercialSegmentID]
           ,[OperationContactName]
           ,[OperationContactPhone]
           ,[OperationContactEmail]
           ,[LegalSponsorName]
           ,[LegalSponsorLastName]
           ,[LegalSponsorDPI]
           ,[HasAgreement]
           ,[AgreementNumber]
           ,[AgreementDateStart]
           ,[AgreementDateEnd]
           ,[InvoiceName]
           ,[TaxIdentificationNumber]
           ,[FiscalAddress]
           ,[InvoiceEmail]
           ,[InvoiceContactName]
           ,[InvoiceContactPhone]
           ,[InvoiceContactEmail]
           ,[CODAccountBankID]
           ,[CODAccountNumber]
           ,[CODAccountName]
           ,[CODAccountTypeID]
           ,[CODCurrencyID]
           ,[CODContactName]
           ,[CODContactPhone]
           ,[CODContactEmail]
           ,[RowSatus]
           ,[TokenCreated]
           ,[DateCreated]
           ,[TokenUpdated]
           ,[DateUpdated]
           ,[SAPCardCode]
           ,[ExcludePriceShippingCOD]
           ,[ExcludeCommissionCOD]
           ,[CatBatchTypeCODId]
           ,[CatBatchFrequencyCODId]
           ,[CatTMSalesPersonId]
           ,[CutOffDate]
           ,[UpgradeDate]
           ,[CustomerGoalQuantity]
           ,[CatBillingTimeId]
           ,[CatBillingVolumeId]
           ,[BillingCut_offDate]
           ,[NumImgEvidence]
           ,[IsCOD])
     VALUES
           ('FD EXPRESS CENTER HN'
           , 'FD EXPRESS CENTER HN'
           ,''
           ,''
           ,'TMP-'
           ,''
           ,'FORZA DELIVERY EXC HN'
           ,2
           ,NULL
           ,'HN'
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,76
           ,NULL
           ,NULL
           ,16
           ,10
           ,28
           ,7
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,1
           ,'SYS-ERAMIREZ'
           ,'2024-06-12 16:40:00.000'
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,NULL
           ,2
           ,NULL
           ,NULL
           ,NULL)
