
INSERT INTO [DeliveryBackOffice].[dbo].[CatArticleSAP]
	(CatCategoryArticleSAPId, [Name], [Description], SAPCode, RowSatus, TokenCreated, DateCreated, Category)
VALUES
	-- SEGURO
	(1, 'GARANTIA MERCANCIAS', 'GARANTIA MERCANCIAS', 409080101, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	-- ESTANDAR
	(1, 'TARIFA DE ENVIO ESTANDAR', 'TARIFA DE ENVIO ESTANDAR', 409010401, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'TARIFA COLLECT ESTANDAR', 'TARIFA COLLECT ESTANDAR', 409010402, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'RECARGO POR PESO ESTANDAR', 'RECARGO POR PESO ESTANDAR', 409010403, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'RECARGO PAGO CON TARJETA ESTANDAR', 'RECARGO PAGO CON TARJETA ESTANDAR', 409010404, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	-- COD
	(1, 'TARIFA DE ENVIO COD', 'TARIFA DE ENVIO COD', 409020104, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'TARIFA COLLECT COD', 'TARIFA COLLECT COD', 409020105, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'RECARGO POR PESO COD', 'RECARGO POR PESO COD', 409020106, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'RECARGO PAGO CON TARJETA COD', 'RECARGO PAGO CON TARJETA COD', 409020107, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'COMISION COD', 'COMISION COD', 409020108, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	-- FRESH
	(1, 'TARIFA DE ENVIO FRESH', 'TARIFA DE ENVIO FRESH', 409090101, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'TARIFA COLLECT FRESH', 'TARIFA COLLECT FRESH', 409090102, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'RECARGO POR PESO FRESH', 'RECARGO POR PESO FRESH', 409090103, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'RECARGO PAGO CON TARJETA FRESH', 'RECARGO PAGO CON TARJETA FRESH', 409090104, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO'),
	(1, 'COMISION COD FRESH', 'COMISION COD FRESH', 409090105, 1, 'SYS-ARUIZ', GETDATE(), 'SERVICIO')

