---# 1. INSERT [dbo].[CatProductCategory] Categorias

ALTER TABLE CatSubscriptionDescription
ALTER COLUMN [Description] NVARCHAR(2000) NOT NULL;

INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Membresías', N'Membresías', 1, 1, N'evasquez', CAST(N'2023-11-27T00:00:00.000' AS DateTime), N'SYS-BHERRERA', CAST(N'2023-11-29T11:47:41.700' AS DateTime),'Membresías')
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Guías Prepago', N'Guías Prepago', 2, 1, N'evasquez', CAST(N'2023-11-27T00:00:00.000' AS DateTime), N'SYS-BHERRERA', CAST(N'2023-11-29T11:47:36.647' AS DateTime),'Paquetes')
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Giftcard', N'Giftcard', 3, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.747' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Cuponeras', N'Cuponeras', 4, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.787' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Merchandizing', N'Merchandizing', 5, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.797' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Descuentos', N'Descuentos', 6, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.807' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Planes de Descuento', N'Planes de Descuento', 7, 1, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.813' AS DateTime), NULL, NULL,'Planes')

--- # 2. INSERT [dbo].[MarketplaceProductTags] Etiquetas
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'LO MÁS VENDIDO', N'En esta sección, encontrarás una selección de los productos más populares entre nuestros clientes', 1, 1, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.790' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'NOVEDADES', N'En esta sección, encontrarás lo más reciente de nuestra tienda virtual', 2, 1, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.810' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'DESTACADOS', N'Productos que te podrían interesar', 3, 0, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.810' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'TODOS LOS PRODUCTOS', N'Desde membresías, planes con descuento hasta guías prepago con tarifa única todo destino', 4, 1, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.810' AS DateTime), NULL, NULL)



DECLARE @IDLOMÁSVENDIDO INT = (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='LO MÁS VENDIDO' and RowStatus=1 )
DECLARE @IDINOVEDADES INT = (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='NOVEDADES' and RowStatus=1 )
DECLARE @IDDESTACADOS INT =  (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='DESTACADOS' and RowStatus=1 )
DECLARE @IDTODOSLOSPRODUCTOS INT = (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='TODOS LOS PRODUCTOS' and RowStatus=1 )

DECLARE @CatMembershipId INT =(SELECT  IdCatMembership FROM dbo.CatMembership WHERE MembershipName='Club Forza' and RowStatus=1)
DECLARE @PaqueteBasico INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Básico' and RowStatus=1 )
DECLARE @PaquetePlus INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Plus' and RowStatus=1 )
DECLARE @PaqueteGold INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Gold' and RowStatus=1 )
DECLARE @PlanAmigo INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Plan Amigo' and RowStatus=1 )
DECLARE @PaquetePetit INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Petit' and RowStatus=1 )
DECLARE @PaquetePlatino INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Platino' and RowStatus=1 )

---# 3. INSERT [dbo].[MarketplaceTagsByProduct]
---Etiquetas por producto

INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDLOMÁSVENDIDO,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.857' AS DateTime), NULL, NULL, @PaqueteBasico, NULL, 3)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDLOMÁSVENDIDO,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.913' AS DateTime), NULL, NULL, @PaquetePlus, NULL, 4)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDLOMÁSVENDIDO,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL,  @PaquetePetit, NULL, 5)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.950' AS DateTime), NULL, NULL, NULL, @CatMembershipId , 1)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.857' AS DateTime), NULL, NULL, @PaqueteBasico, NULL, 3)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.913' AS DateTime), NULL, NULL, @PaquetePlus, NULL, 4)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaqueteGold, NULL, 5)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDINOVEDADES,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaquetePlatino, NULL, 5)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PlanAmigo, NULL, 6)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaquetePetit, NULL, 2)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaquetePlatino, NULL, 5)





-- # 4. INSERT [dbo].[CatProductImage] Imagenes de productos 

INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/basico-500-347.jpg', N'https://forzadelivery.com/images/Tienda/basico-1200-722.jpg', 1, 1, N'SYS-BHERRERA', CAST(N'2023-12-05T11:04:54.497' AS DateTime), NULL, NULL, @PaqueteBasico, NULL,'https://forzadelivery.com/images/Tienda/basico-2103-521.jpg')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/gold-500-347.jpg', N'https://forzadelivery.com/images/Tienda/gold-1200-722.jpg', 2, 1, N'SYS-BHERRERA', CAST(N'2023-12-05T11:06:08.540' AS DateTime), NULL, NULL, @PaqueteGold, NULL,'https://forzadelivery.com/images/Tienda/gold-2103-521.jpg')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/plus-500-347.jpg', N'https://forzadelivery.com/images/Tienda/plus-1200-722.jpg', 3, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PaquetePlus, NULL,'https://forzadelivery.com/images/Tienda/plus-2103-521.jpg')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/club-500-347.jpg', N'https://forzadelivery.com/images/Tienda/club-1200-722.jpg', 4, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, NULL, @CatMembershipId,'https://forzadelivery.com/images/Tienda/club-2103-521.jpg')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/petit-500-347.jpg', N'https://forzadelivery.com/images/Tienda/petit-1200-722.jpg', 5, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PaquetePetit, NULL,'https://forzadelivery.com/images/Tienda/petit-2103-521.jpg')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/amigo-500-347.jpg', N'https://forzadelivery.com/images/Tienda/amigo-1200-722.jpg', 6, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PlanAmigo, NULL,'https://forzadelivery.com/images/Tienda/amigo-2103-521.jpg')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/platino-500-347.jpg', N'https://forzadelivery.com/images/Tienda/platino-1200-722.jpg', 7, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PaquetePlatino, NULL,'https://forzadelivery.com/images/Tienda/platino-2103-521.jpg')

 

 --- # 5. INSERT [dbo].[MarketplaceCarouselImage]  Imagenes de carusel
INSERT [dbo].[MarketplaceCarouselImage] ( [XXLImageURL], [XLImageURL], [MDImageURL], [XSImageURL], [ImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'https://forzadelivery.com/images/Tienda/slider01-1920-300.jpg', N'https://forzadelivery.com/images/Tienda/slider01-1200-250.jpg', N'https://forzadelivery.com/images/Tienda/slider01-992-200.jpg', N'https://forzadelivery.com/images/Tienda/slider01-575-200.jpg', 1, 1, N'SYS-BHERRERA', CAST(N'2023-11-28T19:46:38.077' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceCarouselImage] ( [XXLImageURL], [XLImageURL], [MDImageURL], [XSImageURL], [ImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'https://forzadelivery.com/images/Tienda/slider02-1920-300.jpg', N'https://forzadelivery.com/images/Tienda/slider02-1200-250.jpg', N'https://forzadelivery.com/images/Tienda/slider02-992-200.jpg', N'https://forzadelivery.com/images/Tienda/slider02-575-200.jpg', 2, 1, N'SYS-BHERRERA', CAST(N'2023-11-28T19:46:38.077' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceCarouselImage] ( [XXLImageURL], [XLImageURL], [MDImageURL], [XSImageURL], [ImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'https://forzadelivery.com/images/Tienda/slider03-1920-300.jpg', N'https://forzadelivery.com/images/Tienda/slider03-1200-250.jpg', N'https://forzadelivery.com/images/Tienda/slider03-992-200.jpg', N'https://forzadelivery.com/images/Tienda/slider03-575-200.jpg', 3, 1, N'SYS-BHERRERA', CAST(N'2023-11-28T19:46:38.077' AS DateTime), NULL, NULL)


---# 6 restricciones

INSERT [dbo].[CatSubscriptionDescription] ( [Title], [Description], [Position], [Type], [CatSubscriptionId], [RowStatus], [DateCreated], [TokenCreated], [DateUpdated], [TokenUpdated]) VALUES ( N'Aplican restricciones', N'En caso de que tu envío exceda el peso, +Q1.00 por libra adicional, consulta los terminos y condiciones.', 5, N'PAQUETE BÁSICO', @PaqueteBasico, 1, CAST(N'2024-03-14T00:00:00.000' AS DateTime), N'SYS-EVASQUEZ', NULL, NULL)
INSERT [dbo].[CatSubscriptionDescription] ( [Title], [Description], [Position], [Type], [CatSubscriptionId], [RowStatus], [DateCreated], [TokenCreated], [DateUpdated], [TokenUpdated]) VALUES ( N'Aplican restricciones', N'En caso de que tu envío exceda el peso, +Q1.00 por libra adicional, consulta los terminos y condiciones.', 5, N'PAQUETE PLUS', @PaquetePlus, 1, CAST(N'2024-03-14T00:00:00.000' AS DateTime), N'SYS-EVASQUEZ', NULL, NULL)
INSERT [dbo].[CatSubscriptionDescription] ( [Title], [Description], [Position], [Type], [CatSubscriptionId], [RowStatus], [DateCreated], [TokenCreated], [DateUpdated], [TokenUpdated]) VALUES ( N'Aplican restricciones', N'En caso de que tu envío exceda el peso, +Q1.00 por libra adicional, consulta los terminos y condiciones.', 5, N'PLAN AMIGO', @PlanAmigo, 1, CAST(N'2024-03-14T00:00:00.000' AS DateTime), N'SYS-EVASQUEZ', NULL, NULL)
INSERT [dbo].[CatSubscriptionDescription] ( [Title], [Description], [Position], [Type], [CatSubscriptionId], [RowStatus], [DateCreated], [TokenCreated], [DateUpdated], [TokenUpdated]) VALUES ( N'Aplican restricciones', N'En caso de que tu envío exceda el peso, +Q1.00 por libra adicional, consulta los terminos y condiciones.', 5, N'PAQUETE GOLD', @PaqueteGold, 1, CAST(N'2024-03-14T00:00:00.000' AS DateTime), N'SYS-EVASQUEZ', NULL, NULL)
INSERT [dbo].[CatSubscriptionDescription] ( [Title], [Description], [Position], [Type], [CatSubscriptionId], [RowStatus], [DateCreated], [TokenCreated], [DateUpdated], [TokenUpdated]) VALUES ( N'Aplican restricciones', N'En caso de que tu envío exceda el peso, +Q1.00 por libra adicional, consulta los terminos y condiciones.', 5, N'PAQUETE PETIT',  @PaquetePetit , 1, CAST(N'2024-03-14T00:00:00.000' AS DateTime), N'SYS-EVASQUEZ', NULL, NULL)
INSERT [dbo].[CatSubscriptionDescription] ( [Title], [Description], [Position], [Type], [CatSubscriptionId], [RowStatus], [DateCreated], [TokenCreated], [DateUpdated], [TokenUpdated]) VALUES ( N'Aplican restricciones', N'En caso de que tu envío exceda el peso, +Q1.00 por libra adicional, consulta los terminos y condiciones.', 5, N'PAQUETE PLATINO',  @PaquetePlatino , 1, CAST(N'2024-03-14T00:00:00.000' AS DateTime), N'SYS-EVASQUEZ', NULL, NULL)