---# 1. INSERT [dbo].[CatProductCategory] Categorias


INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Membresías', N'Membresías', 1, 1, N'evasquez', CAST(N'2023-11-27T00:00:00.000' AS DateTime), N'SYS-BHERRERA', CAST(N'2023-11-29T11:47:41.700' AS DateTime),'Membresías')
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Guías Prepago', N'Guías Prepago', 2, 1, N'evasquez', CAST(N'2023-11-27T00:00:00.000' AS DateTime), N'SYS-BHERRERA', CAST(N'2023-11-29T11:47:36.647' AS DateTime),'Paquetes')
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Giftcard', N'Giftcard', 3, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.747' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Cuponeras', N'Cuponeras', 4, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.787' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Merchandizing', N'Merchandizing', 5, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.797' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Descuentos', N'Descuentos', 6, 0, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.807' AS DateTime), NULL, NULL)
INSERT [dbo].[CatProductCategory] ( [CatProductCategoryName], [CatProductCategoryDescription], [CatProductCategoryOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [TechnicalDescription]) VALUES ( N'Planes de Descuento', N'Planes de Descuento', 7, 1, N'SYS-BHERRERA', CAST(N'2023-11-29T11:46:16.813' AS DateTime), NULL, NULL,'Planes')

--- # 2. INSERT [dbo].[MarketplaceProductTags] Etiquetas
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'LO MÁS VENDIDO', N'Productos que más le gustaron a nuestros clientes', 1, 1, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.790' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'NOVEDADES', N'Productos que te podrían interesar', 2, 1, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.810' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'DESTACADOS', N'Productos que te podrían interesar', 3, 1, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.810' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceProductTags] ( [MarketplaceProductTagsName], [MarketplaceProductTagsDescription], [MarketplaceProductTagsOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'TODOS LOS PRODUCTOS', N'Productos Forza', 4, 1, N'SYS-BHERRERA', CAST(N'2023-12-04T17:55:24.810' AS DateTime), NULL, NULL)



DECLARE @IDLOMÁSVENDIDO INT = (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='LO MÁS VENDIDO' and RowStatus=1 )
DECLARE @IDINOVEDADES INT = (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='NOVEDADES' and RowStatus=1 )
DECLARE @IDDESTACADOS INT =  (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='DESTACADOS' and RowStatus=1 )
DECLARE @IDTODOSLOSPRODUCTOS INT = (SELECT IdMarketplaceProductTags FROM MarketplaceProductTags WHERE MarketplaceProductTagsName='TODOS LOS PRODUCTOS' and RowStatus=1 )

DECLARE @CatMembershipId INT =(SELECT  IdCatMembership FROM dbo.CatMembership WHERE MembershipName='Club Forza' and RowStatus=1)
DECLARE @PaqueteBasico INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Básico' and RowStatus=1 )
DECLARE @PaquetePlus INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Plus' and RowStatus=1 )
DECLARE @PaqueteGold INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Gold' and RowStatus=1 )
DECLARE @PlanAmigo INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Plan Amigo' and RowStatus=1 )
DECLARE @PaquetePetit INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Petit' and RowStatus=1 )
DECLARE @PaquetePlatino INT =(SELECT IdCatSubscription FROM dbo.CatSubscription WHERE SubscriptionName='Paquete Platino' and RowStatus=1 )

---# 3. INSERT [dbo].[MarketplaceTagsByProduct]
---Etiquetas por producto

INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDLOMÁSVENDIDO,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.857' AS DateTime), NULL, NULL, @PaqueteBasico, NULL, 3)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDLOMÁSVENDIDO,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.913' AS DateTime), NULL, NULL, @PaquetePlus, NULL, 4)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDLOMÁSVENDIDO,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaqueteGold, NULL, 5)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDDESTACADOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.950' AS DateTime), NULL, NULL, NULL, @CatMembershipId , 1)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.950' AS DateTime), NULL, NULL, NULL, @CatMembershipId , 1)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.857' AS DateTime), NULL, NULL, @PaqueteBasico, NULL, 3)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.913' AS DateTime), NULL, NULL, @PaquetePlus, NULL, 4)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaqueteGold, NULL, 5)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDINOVEDADES,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaqueteGold, NULL, 5)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PlanAmigo, NULL, 6)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaquetePetit, NULL, 2)
INSERT [dbo].[MarketplaceTagsByProduct] ( [MarketplaceProductTagsId],  [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId], [Position]) VALUES ( @IDTODOSLOSPRODUCTOS,  1, N'SYS-BHERRERA', CAST(N'2023-12-05T10:55:43.923' AS DateTime), NULL, NULL, @PaquetePlatino, NULL, 5)





-- # 4. INSERT [dbo].[CatProductImage] Imagenes de productos 

INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/basico_small_1.jpg', N'https://forzadelivery.com/images/Tienda/basico_big_1.png', 1, 1, N'SYS-BHERRERA', CAST(N'2023-12-05T11:04:54.497' AS DateTime), NULL, NULL, @PaqueteBasico, NULL,'https://forzadelivery.com/images/Tienda/basico_veryBig_1.png')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/gold_small_1.jpg', N'https://forzadelivery.com/images/Tienda/gold_big_1.png', 2, 1, N'SYS-BHERRERA', CAST(N'2023-12-05T11:06:08.540' AS DateTime), NULL, NULL, @PaqueteGold, NULL,'https://forzadelivery.com/images/Tienda/gold_veryBig_1.png')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/plus_small_1.jpg', N'https://forzadelivery.com/images/Tienda/plus_big_1.png', 3, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PaquetePlus, NULL,'https://forzadelivery.com/images/Tienda/plus_veryBig_1.png')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/membrecia_small_1.png', N'https://forzadelivery.com/images/Tienda/membrecia_big_1.png', 4, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, NULL, @CatMembershipId,'https://forzadelivery.com/images/Tienda/membrecia_veryBig_1.png')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/petit_small_1.jpg', N'https://forzadelivery.com/images/Tienda/petit_big_1.png', 5, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PaquetePetit, NULL,'https://forzadelivery.com/images/Tienda/petit_veryBig_1.png')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/amigo_big_1.png', N'https://forzadelivery.com/images/Tienda/amigo_big_1.png', 6, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PlanAmigo, NULL,'https://forzadelivery.com/images/Tienda/amigo_veryBig_1.png')
INSERT [dbo].[CatProductImage] ( [CatProductImageSmallImageURL], [CatProductImageLargeImageURL], [CatProductImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated], [CatSubscriptionId], [CatMembershipId],[CatProductImageBigImageURL]) VALUES ( N'https://forzadelivery.com/images/Tienda/platino_small_1.png', N'https://forzadelivery.com/images/Tienda/platino_big_1.png', 7, 1, N'SYS-BHERRERA', CAST(N'2023-12-13T12:27:27.087' AS DateTime), NULL, NULL, @PaquetePlatino, NULL,'https://forzadelivery.com/images/Tienda/platino_veryBig_1.png')

 

 --- # 5. INSERT [dbo].[MarketplaceCarouselImage]  Imagenes de carusel
INSERT [dbo].[MarketplaceCarouselImage] ( [XXLImageURL], [XLImageURL], [MDImageURL], [XSImageURL], [ImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'https://forzadelivery.com/images/Tienda/imagen1920x300.png', N'https://forzadelivery.com/images/Tienda/imagen1200x250.png', N'https://forzadelivery.com/images/Tienda/imagen992x200.png', N'https://forzadelivery.com/images/Tienda/imagen575x200.png', 1, 1, N'SYS-BHERRERA', CAST(N'2023-11-28T19:46:38.077' AS DateTime), NULL, NULL)
INSERT [dbo].[MarketplaceCarouselImage] ( [XXLImageURL], [XLImageURL], [MDImageURL], [XSImageURL], [ImageOrder], [RowStatus], [TokenCreated], [DateCreated], [TokenUpdated], [DateUpdated]) VALUES ( N'https://forzadelivery.com/images/Tienda/imagen1920x300.png', N'https://forzadelivery.com/images/Tienda/imagen1200x250.png', N'https://forzadelivery.com/images/Tienda/imagen992x200.png', N'https://forzadelivery.com/images/Tienda/imagen575x200.png', 2, 1, N'SYS-BHERRERA', CAST(N'2023-11-28T19:46:38.077' AS DateTime), NULL, NULL)

