INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Qatar',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Ecuador',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Senegal',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Netherlands',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('England',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('IR Iran',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('USA',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Wales',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Argentina',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Saudi Arabia',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Mexico',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Poland',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('France',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Australia',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Denmark',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Tunisia',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Spain',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Costa Rica',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Germany',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Japan',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Belgium',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Canada',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Morocco',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Croatia',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Brazil',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Serbia',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Switzerland',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Cameroon',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Portugal',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Ghana',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Uruguay',2022 ,'SYS-ARUIZ',GETDATE())
INSERT INTO [dbo].[WorldCupPromoCandidate] ([WorldCupCandidateName] ,[WorldCupYear] ,[TokenCreated] ,[DateCreated]) VALUES ('Korea',2022 ,'SYS-ARUIZ',GETDATE())
