UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.573511', HubLongitude ='-90.54653' WHERE HubName = 'GUATEMALA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'GUA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'GTM' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.887006', HubLongitude ='-91.468999' WHERE HubName = 'QUETZALTENANGO' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'QUE' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.539175', HubLongitude ='-91.50883' WHERE HubName = 'MAZATENANGO' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'MAZ' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.027525', HubLongitude ='-91.154505' WHERE HubName = 'SANTA CRUZ DEL QUICHE' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'QUI' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.77241', HubLongitude ='-91.181953' WHERE HubName = 'SOLOLA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'SOL' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.703579', HubLongitude ='-91.855764' WHERE HubName = 'COATEPEQUE' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'COA' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.909007', HubLongitude ='-92.057875' WHERE HubName = 'MALACATAN' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'MAL' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.656991', HubLongitude ='-91.428929' WHERE HubName = 'SOLOMA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'SLM' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.802261', HubLongitude ='-91.314461' WHERE HubName = 'BARILLAS' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'BRL' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.621655', HubLongitude ='-91.885772' WHERE HubName = 'LA DEMOCRACIA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'DEM' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.3031625', HubLongitude ='-91.5148906' WHERE HubName = 'HUEHUETENANGO' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'HUE' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.97087', HubLongitude ='-91.777789' WHERE HubName = 'SAN MARCOS' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'SMA' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.984892', HubLongitude ='-89.717665' WHERE HubName = 'TECULUTAN' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'TEC' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '16.922642', HubLongitude ='-89.905489' WHERE HubName = 'PETEN' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'FRS' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.482162', HubLongitude ='-88.823287' WHERE HubName = 'MORALES' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'MOR' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.7989101', HubLongitude ='-89.5467517' WHERE HubName = 'CHIQUIMULA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'CHQ' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.0999031', HubLongitude ='-90.3210491' WHERE HubName = 'SALAMA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'SAL' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.5652332', HubLongitude ='-89.3526382' WHERE HubName = 'ESQUIPULAS' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'ESQ' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.6336078', HubLongitude ='-89.9840083' WHERE HubName = 'JALAPA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'JAL' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '15.4667516', HubLongitude ='-90.3677419' WHERE HubName = 'COBAN' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'COB' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.3063331', HubLongitude ='-90.7835766' WHERE HubName = 'ESCUINTLA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'ESC' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.335294', HubLongitude ='-91.0252792' WHERE HubName = 'SANTA LUCIA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'SLC' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.3137577', HubLongitude ='-89.8719468' WHERE HubName = 'JUTIAPA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'JUT' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.2968065', HubLongitude ='-90.3424486' WHERE HubName = 'BARBERENA' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'BAR' COLLATE Latin1_General_CI_AI
UPDATE [DeliveryBackOffice].[dbo].[HubLogistics] SET TokenUpdate = 'SYS-ARUIZ', DateUpdated = GETDATE(), HubLatitude = '14.6563135', HubLongitude ='-90.8126349' WHERE HubName = 'CHIMALTENANGO' COLLATE Latin1_General_CI_AI OR HubAbbreviation = 'CHI' COLLATE Latin1_General_CI_AI
