USE [DeliveryBackOffice]
GO

/****** Object:  Index [NonClusteredIndex-20241126-193618]    Script Date: 26/11/2024 19:37:17 ******/
CREATE NONCLUSTERED INDEX [IDX_TknIdUser_20241126] ON [dbo].[TokenLog]
(
	[TknIdUser] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO


