CREATE TABLE [dbo].[UnifiedRouteSettlementDetail] (
    [IdUnifiedRouteSettlementDetail] INT             IDENTITY (1, 1) NOT NULL,
    [UnifiedRouteSettlementId]       INT             NOT NULL,
    [ServiceManagementId]            INT             NOT NULL,
    [GuideSerie]                     NVARCHAR (2)    NOT NULL,
    [GuideNumber]                    INT             NOT NULL,
    [PiecesSettled]                  INT             DEFAULT ((0)) NOT NULL,
    [PiecesMissing]                  INT             DEFAULT ((0)) NOT NULL,
    [ServiceSettlementAmount]        DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [ServiceCODSettlementAmount]     DECIMAL (18, 2) DEFAULT ((0)) NOT NULL,
    [UserSettlement]                 NVARCHAR (50)   NULL,
    [DateSettlement]                 DATETIME        NULL,
    [UserCODSettlement]              NVARCHAR (50)   NULL,
    [DateCODSettlement]              DATETIME        NULL,
    [IsOpenProcess]                  INT             DEFAULT ((0)) NOT NULL,
    [UserProcess]                    NVARCHAR (50)   NULL,
    [IsArrival]                      BIT             DEFAULT ((0)) NOT NULL,
    [IsReturn]                       BIT             DEFAULT ((0)) NOT NULL,
    [IsDelivered]                    BIT             DEFAULT ((0)) NOT NULL,
    [IsTransfered]                   BIT             DEFAULT ((0)) NOT NULL,
    [RowStatus]                      BIT             DEFAULT ((1)) NOT NULL,
    [TokenCreated]                   NVARCHAR (50)   NOT NULL,
    [DateCreated]                    DATETIME        NOT NULL,
    [TokenUpdated]                   NVARCHAR (50)   NULL,
    [DateUpdated]                    DATETIME        NULL,
    [IsLost]                         BIT             CONSTRAINT [DF_UnifiedRouteSettlementDetail_IsLost] DEFAULT ((0)) NOT NULL,
    PRIMARY KEY CLUSTERED ([IdUnifiedRouteSettlementDetail] ASC)
);

